Download
/
Tutorials
/
Documentation
/
Contact
/
FAQ
/
Awards
/
RiSE
Solver Class Reference
Solvers.
Public Member Functions
void Push ()
Creates a backtracking point.
void Pop (uint n=1)
Backtracks n backtracking points.
void Reset ()
Resets the Solver.
void Assert (params BoolExpr[] constraints)
Assert a constraint (or multiple) into the solver.
Status Check (params Expr[] assumptions)
Checks whether the assertions in the solver are consistent or not.
override string ToString ()
A string representation of the solver.
Properties
string Help [get]
A string that describes all available solver parameters.
Params Parameters [set]
Sets the solver parameters.
uint NumScopes [get]
The current number of backtracking points (scopes).
uint NumAssertions [get]
The number of assertions in the solver.
BoolExpr[] Assertions [get]
The set of asserted formulas.
Model Model [get]
The model of the last Check.
Expr Proof [get]
The proof of the last Check.
Expr[] UnsatCore [get]
The unsat core of the last Check.
string ReasonUnknown [get]
A brief justification of why the last call to Check returned UNKNOWN.
Statistics Statistics [get]
Solver statistics.
Detailed Description
Solvers.
Definition at line 29 of file Solver.cs.
Member Function Documentation
void Assert (params BoolExpr[] constraints) [inline]
Assert a constraint (or multiple) into the solver.
Definition at line 97 of file Solver.cs.
Referenced by TestManaged::array_example2(), TestManaged::assert_inj_axiom(), TestManaged::assert_inj_axiom_abs(), TestManaged::bitvector_example2(), TestManaged::check_small(), TestManaged::eval_example1(), TestManaged::eval_example2(), TestManaged::find_model_example1(), TestManaged::find_model_example2(), TestManaged::find_small_model_example(), TestManaged::parser_example1(), TestManaged::parser_example2(), TestManaged::prove(), TestManaged::prove2(), TestManaged::prove_example1(), TestManaged::prove_example2(), TestManaged::push_pop_example1(), TestManaged::quantifier_example1(), TestManaged::quantifier_example1_abs(), and TestManaged::unsat_core_and_proof_example().
        {
            Contract.Requires(constraints != null);
            Contract.Requires(Contract.ForAll(constraints, c => c != null));
            Context.CheckContextMatch(constraints);
            foreach (BoolExpr a in constraints)
            {
                Native.Z3_solver_assert(Context.nCtx, NativeObject, a.NativeObject);
            }
        }
Status Check (params Expr[] assumptions) [inline]
Checks whether the assertions in the solver are consistent or not.
See also:
Model, UnsatCore, Proof
Definition at line 147 of file Solver.cs.
Referenced by TestManaged::check(), TestManaged::check2(), TestManaged::check_small(), TestManaged::eval_example1(), TestManaged::eval_example2(), TestManaged::prove(), TestManaged::prove2(), and TestManaged::unsat_core_and_proof_example().
        {
            Z3_lbool r;
            if (assumptions == null)
                r = (Z3_lbool)Native.Z3_solver_check(Context.nCtx, NativeObject);
            else
                r = (Z3_lbool)Native.Z3_solver_check_assumptions(Context.nCtx, NativeObject, (uint)assumptions.Length, AST.ArrayToNative(assumptions));
            switch (r)
            {
                case Z3_lbool.Z3_L_TRUE: return Status.SATISFIABLE;
                case Z3_lbool.Z3_L_FALSE: return Status.UNSATISFIABLE;
                default: return Status.UNKNOWN;
            }
        }
void Pop (uint n = 1) [inline]
Backtracks n backtracking points.
Note that an exception is thrown if n is not smaller than NumScopes
See also:
Push
Definition at line 80 of file Solver.cs.
Referenced by TestManaged::check_small(), TestManaged::prove(), TestManaged::prove2(), and TestManaged::push_pop_example1().
        {
            Native.Z3_solver_pop(Context.nCtx, NativeObject, n);
        }
void Push () [inline]
Creates a backtracking point.
See also:
Pop
Definition at line 70 of file Solver.cs.
Referenced by TestManaged::check_small(), TestManaged::prove(), TestManaged::prove2(), and TestManaged::push_pop_example1().
        {
            Native.Z3_solver_push(Context.nCtx, NativeObject);
        }
void Reset () [inline]
Resets the Solver.
This removes all assertions from the solver.
Definition at line 89 of file Solver.cs.
        {
            Native.Z3_solver_reset(Context.nCtx, NativeObject);
        }
override string ToString () [inline]
A string representation of the solver.
Definition at line 250 of file Solver.cs.
        {
            return Native.Z3_solver_to_string(Context.nCtx, NativeObject);
        }
Property Documentation
BoolExpr [] Assertions [get]
The set of asserted formulas.
Definition at line 125 of file Solver.cs.
string Help [get]
A string that describes all available solver parameters.
Definition at line 35 of file Solver.cs.
Model Model [get]
The model of the last Check.
The result is null if Check was not invoked before, if its results was not SATISFIABLE, or if model production is not enabled.
Definition at line 170 of file Solver.cs.
Referenced by TestManaged::check(), TestManaged::check2(), TestManaged::check_small(), TestManaged::eval_example1(), TestManaged::eval_example2(), TestManaged::prove(), and TestManaged::prove2().
uint NumAssertions [get]
The number of assertions in the solver.
Definition at line 113 of file Solver.cs.
uint NumScopes [get]
The current number of backtracking points (scopes).
See also:
Pop, Push
Definition at line 62 of file Solver.cs.
Params Parameters [set]
Sets the solver parameters.
Definition at line 46 of file Solver.cs.
Expr Proof [get]
The proof of the last Check.
The result is null if Check was not invoked before, if its results was not UNSATISFIABLE, or if proof production is disabled.
Definition at line 189 of file Solver.cs.
Referenced by TestManaged::prove(), and TestManaged::unsat_core_and_proof_example().
string ReasonUnknown [get]
A brief justification of why the last call to Check returned UNKNOWN.
Definition at line 227 of file Solver.cs.
Statistics Statistics [get]
Solver statistics.
Definition at line 240 of file Solver.cs.
Expr [] UnsatCore [get]
The unsat core of the last Check.
The unsat core is a subset of Assertions The result is empty if Check was not invoked before, if its results was not UNSATISFIABLE, or if core production is disabled.
Definition at line 209 of file Solver.cs.
Referenced by TestManaged::unsat_core_and_proof_example().
Last modified Thu Aug 9 16:34:48 2012