Download
/
Tutorials
/
Documentation
/
Contact
/
FAQ
/
Awards
/
RiSE
Solver Class Reference
Solver for Presburger Arithmetic formulas.
Public Member Functions
Solver ()
Create an instance of a context for the solver.
LinearFormula CoopersAlgorithm (LinearFormula f)
Top-level call of Coopers quantifier elimination algorithm. Eliminates quantifiers starting with the innermost quantified formulas. Returns a formula that is quantifier free and is equivalent to f.
LinearFormula CoopersAlgorithm1 (LinearFormula f)
Assumes that f is in prenex form and variables with the same kind of quantifier are grouped together.
Term ToZ3Term (LinearTerm t)
Convert the given linear term to a Z3 term.
Term ToZ3Formula (LinearFormula t)
Convert the given PA formula t to a Z3 formula (throws ArgumentException if t includes quantifiers).
LBool IsSat (LinearFormula f)
Checks if f is satisfiable without changing the current context. Returns LBool.True if f is satisfiable, returns LBool.Undef upon timeout. (Throws ArgumentException if f includes quantifiers).
LBool Check ()
Returns LBool.True if the current constraints are satisfiable Returns LBool.Undef upon timeout.
LBool IsSat (LinearFormula f, out PAModel model)
Checks if f is satisfiable without changing the current context. Returns LBool.True and a model if f is satisfiable, returns LBool.Undef upon timeout. (Throws ArgumentException if f includes quantifiers).
void Push ()
Pushes the current context as a new backtrack point.
void Pop ()
Returns to the previously pushed context.
void AddConstraint (LinearFormula f)
Adds the constraint f to the current context (throws ArgumentException if f includes quantifiers).
LBool CheckAndGetModel (out PAModel model)
Checks and returns a model if the constraints in the current context are satisfiable (returns LBool.Undef in case of timeout).
Static Public Member Functions
static int LCM (IEnumerable< int > ks)
Calculate the least common multiple of the coefficients in the given enumeration. The enumeration is assumed to contain only nonzero elements. Returns -1 if the enumeration is empty.
static int LCM (int m, int k)
Calculate the least common multiple of m and k (m must be positive and k must be nonzero).
static int GCD (int a, int b)
Euclides algorithm. Calculate the greatest common divisor of a and b. It is assumed that b is greater that 0 and a is non-negative.
Detailed Description
Solver for Presburger Arithmetic formulas.
Definition at line 13 of file Solver.cs.
Constructor & Destructor Documentation
Solver () [inline]
Create an instance of a context for the solver.
Definition at line 21 of file Solver.cs.
        {
            Config par = new Config();
            par.SetParamValue("MODEL", "true");
            par.SetParamValue("ARITH_LAZY_PIVOTING", "0");
            z3 = new Context(par);
            intSort = z3.MkIntSort();
            zero = z3.MkNumeral(0, intSort);
            par.Dispose();
        }
Member Function Documentation
void AddConstraint (LinearFormula f) [inline]
Adds the constraint f to the current context (throws ArgumentException if f includes quantifiers).
Definition at line 630 of file Solver.cs.
Referenced by Solver::IsSat().
        {
            Term zf = ToZ3Formula(f);
            z3.AssertCnstr(zf);
        }
LBool Check () [inline]
Returns LBool.True if the current constraints are satisfiable Returns LBool.Undef upon timeout.
Definition at line 591 of file Solver.cs.
Referenced by Solver::IsSat().
        {
            return z3.Check();
        }
LBool CheckAndGetModel (out PAModel model) [inline]
Checks and returns a model if the constraints in the current context are satisfiable (returns LBool.Undef in case of timeout).
Definition at line 640 of file Solver.cs.
Referenced by Solver::IsSat().
        {
            Model z3model;
            LBool res = z3.CheckAndGetModel(out z3model);
            if (res == LBool.True)
                model = new PAModel(this, z3model);
            else
                model = null;
            return res;
        }
LinearFormula CoopersAlgorithm (LinearFormula f) [inline]
Top-level call of Coopers quantifier elimination algorithm. Eliminates quantifiers starting with the innermost quantified formulas. Returns a formula that is quantifier free and is equivalent to f.
Definition at line 37 of file Solver.cs.
        {
            if (f.IsQuantifierFree)
                return f;
            f = GetPrenexForm(f);
            LinearFormula res = CoopersAlgorithm1(f);
            return res;
        }
LinearFormula CoopersAlgorithm1 (LinearFormula f) [inline]
Assumes that f is in prenex form and variables with the same kind of quantifier are grouped together.
Definition at line 51 of file Solver.cs.
Referenced by Solver::CoopersAlgorithm().
        {
            QuantifiedFormula f1 = f as QuantifiedFormula;
            if (f1 != null)
            {
                LinearFormula f2 = CoopersAlgorithm1(f1.Formula);
                if (f1.IsExists)
                    return EliminateExs(f1.Variables, f2);
                else
                    return ~EliminateExs(f1.Variables, ~f2);
            }
            return f;
        }
static int GCD (int a, int b) [inline, static]
Euclides algorithm. Calculate the greatest common divisor of a and b. It is assumed that b is greater that 0 and a is non-negative.
Definition at line 384 of file Solver.cs.
Referenced by Solver::LCM().
        {
            //if (a == 0)
            //    return b;
            while (b > 0)
            {
                int tmp = b;
                b = a % b;
                a = tmp;
            }
            return a;
        }
LBool IsSat (LinearFormula f, out PAModel model) [inline]
Checks if f is satisfiable without changing the current context. Returns LBool.True and a model if f is satisfiable, returns LBool.Undef upon timeout. (Throws ArgumentException if f includes quantifiers).
Definition at line 601 of file Solver.cs.
        {
            Push();
            AddConstraint(f);
            LBool res = CheckAndGetModel(out model);
            Pop();
            return res;
        }
LBool IsSat (LinearFormula f) [inline]
Checks if f is satisfiable without changing the current context. Returns LBool.True if f is satisfiable, returns LBool.Undef upon timeout. (Throws ArgumentException if f includes quantifiers).
Definition at line 578 of file Solver.cs.
        {
            Push();
            AddConstraint(f);
            LBool res = Check();
            Pop();
            return res;
        }
static int LCM (int m, int k) [inline, static]
Calculate the least common multiple of m and k (m must be positive and k must be nonzero).
Definition at line 370 of file Solver.cs.
        {
            int n = Math.Abs(k);
            if (m < n)
                m = (m / GCD(n, m)) * n;
            else if (m > n)
                m = (n / GCD(m, n)) * m;
            return m;
        }
static int LCM (IEnumerable< int > ks) [inline, static]
Calculate the least common multiple of the coefficients in the given enumeration. The enumeration is assumed to contain only nonzero elements. Returns -1 if the enumeration is empty.
Definition at line 352 of file Solver.cs.
        {
            int m = -1;
            foreach (int k in ks)
            {
                m = Math.Abs(m);
                int n = Math.Abs(k);
                if (m < n)
                    m = (m / GCD(n, m)) * n;
                else if (m > n)
                    m = (n / GCD(m, n)) * m;
            }
            return m;
        }
void Pop () [inline]
Returns to the previously pushed context.
Definition at line 621 of file Solver.cs.
Referenced by Solver::IsSat().
        {
            z3.Pop();
        }
void Push () [inline]
Pushes the current context as a new backtrack point.
Definition at line 613 of file Solver.cs.
Referenced by Solver::IsSat().
        {
            z3.Push();
        }
Term ToZ3Formula (LinearFormula t) [inline]
Convert the given PA formula t to a Z3 formula (throws ArgumentException if t includes quantifiers).
Definition at line 515 of file Solver.cs.
Referenced by Solver::AddConstraint().
        {
            if (t is LinearAtom)
            {
                LE le = t as LE;
                if (le != null)
                    return z3.MkLe(ToZ3Term(le.T), zero);
                DIV div = (DIV)t;
                if (div.IsDiv)
                    return z3MkDiv(z3.MkNumeral(div.D, intSort), ToZ3Term(div.T));
                else
                    return z3.MkNot(z3MkDiv(z3.MkNumeral(div.D, intSort), ToZ3Term(div.T)));
            }
            else
            {
                Disjunction disj = t as Disjunction;
                if (disj != null)
                {
                    Term[] disjs = new Term[disj.fms.Count];
                    int i = 0;
                    foreach (LinearFormula f in disj.fms)
                        disjs[i++] = ToZ3Formula(f);
                    return z3.MkOr(disjs);
                }
                Conjunction conj = t as Conjunction;
                if (conj != null)
                {
                    Term[] conjs = new Term[conj.fms.Count];
                    int i = 0;
                    foreach (LinearFormula f in conj.fms)
                        conjs[i++] = ToZ3Formula(f);
                    return z3.MkAnd(conjs);
                }
                BigOR bq = t as BigOR;
                if (bq != null)
                {
                    List<Term> bounds = new List<Term>();
                    foreach (BoundedVariable v in bq.Vars)
                    {
                        Term bound = z3.MkAnd(z3.MkLe(z3.MkNumeral(v.lower, intSort), z3.MkConst(v.var, intSort)),
                                              z3.MkLe(z3.MkConst(v.var, intSort), z3.MkNumeral(v.upper, intSort)));
                        bounds.Add(bound);
                    }
                    Term divs = ToZ3Formula(bq.Divs);
                    Term f = ToZ3Formula(bq.F);
                    Term bf = z3.MkAnd(new Term[]{z3.MkOr(bounds.ToArray()),divs,f});
                    return bf;
                }
                throw new ArgumentException("Conversion is not supported");
            }
        }
Term ToZ3Term (LinearTerm t) [inline]
Convert the given linear term to a Z3 term.
Definition at line 480 of file Solver.cs.
Referenced by Solver::ToZ3Formula().
        {
            Term c = z3.MkNumeral(t.Constant, intSort);
            if (t.IsConstant)
                return z3.MkNumeral(t.Constant, intSort);
            Term[] args;
            int i = 0;
            if (t.Constant == 0)
            {
                args = new Term[t.NumberOfVariables];
            }
            else
            {
                args = new Term[t.NumberOfVariables + 1];
                args[0] = z3.MkNumeral(t.Constant, intSort);
                i = 1;
            }
            foreach (VarType x in t.Variables)
            {
                args[i++] = z3.MkMul(z3.MkNumeral(t.Coefficient(x), intSort), z3Var(x));
            }
            return z3.MkAdd(args);
        }
Last modified Thu Aug 9 16:34:49 2012