Download
/
Tutorials
/
Documentation
/
Contact
/
FAQ
/
Awards
/
RiSE
Config Class Reference
[Managed (.NET) API]
Configuration.
Public Member Functions
Config ()
Create configuration context.
~Config ()
Configuration destructor.
void SetParamValue (String^name, String^value)
Set parameter to specified value.
Detailed Description
Configuration.
Configuration can be set prior to creating an instance of the Z3 Context.
To set a parameter create an instance of the Params class and call the SetParamValue() method.
The set of legal parameters can be found by executing z3.exe /ini?
Definition at line 592 of file Microsoft.Z3V3.h.
Constructor & Destructor Documentation
Config ()
Create configuration context.
Create a configuration context to supply configurations to the Z3 Context. Callers must explicitly close the configuration in order to collect the resources allocated in the configuration.
~Config ()
Configuration destructor.
Member Function Documentation
void SetParamValue (String^ name, String^ value)
Set parameter to specified value.
The list of all configuration parameters can be obtained using the Z3 executable:
           z3.exe /ini?
Referenced by TestManaged::get_implied_equalities_example(), TestManaged::mk_context(), TestManaged::quantifier_example1(), TestManaged::quantifier_example1_abs(), and TestManaged::unsat_core_and_proof_example().
Last modified Thu Aug 9 16:34:48 2012