Download
/
Tutorials
/
Documentation
/
Contact
/
FAQ
/
Awards
/
RiSE
C API
Types
Most of the types in the C API are opaque pointers.
Z3_config: configuration object used to initialize logical contexts.
Z3_context: manager of all other Z3 objects, global configuration options, etc.
Z3_symbol: Lisp-like symbol used to name types, constants, and functions. A symbol can be created using string or integers.
Z3_ast: abstract syntax tree node. That is, the data-structure used in Z3 to represent terms, formulas and types.
Z3_sort: kind of AST used to represent types.
Z3_func_decl: kind of AST used to represent function symbols.
Z3_app: kind of AST used to represent function applications.
Z3_pattern: kind of AST used to represent pattern and multi-patterns used to guide quantifier instantiation.
Z3_constructor: type constructor for a (recursive) datatype.
Z3_params: parameter set used to configure many components such as: simplifiers, tactics, solvers, etc.
Z3_model: model for the constraints asserted into the logical context.
Z3_func_interp: interpretation of a function in a model.
Z3_func_entry: representation of the value of a Z3_func_interp at a particular point.
Z3_fixedpoint: context for the recursive predicate solver.
Z3_ast_vector: vector of Z3_ast objects.
Z3_ast_map: mapping from Z3_ast to Z3_ast objects.
Z3_goal: set of formulas that can be solved and/or transformed using tactics and solvers.
Z3_tactic: basic building block for creating custom solvers for specific problem domains.
Z3_probe: function/predicate used to inspect a goal and collect information that may be used to decide which solver and/or preprocessing step will be used.
Z3_apply_result: collection of subgoals resulting from applying of a tactic to a goal.
Z3_solver: (incremental) solver, possibly specialized by a particular tactic or logic.
Z3_stats: statistical data for a solver.
enum Z3_lbool
Lifted Boolean type: false, undefined, true.
enum Z3_symbol_kind
The different kinds of symbol. In Z3, a symbol can be represented using integers and strings (See Z3_get_symbol_kind).
enum Z3_parameter_kind
The different kinds of parameters that can be associated with function symbols.
enum Z3_sort_kind
The different kinds of Z3 types (See Z3_get_sort_kind).
enum Z3_ast_kind
The different kinds of Z3 AST (abstract syntax trees). That is, terms, formulas and types.
enum Z3_decl_kind
The different kinds of interpreted function kinds.
enum Z3_search_failure
The different kinds of search failure types.
enum Z3_ast_print_mode
Z3 pretty printing modes (See Z3_set_ast_print_mode).
enum Z3_error_code
Z3 error codes (See Z3_get_error_code).
enum Z3_goal_prec
A Goal is essentially a set of formulas. Z3 provide APIs for building strategies/tactics for solving and transforming Goals. Some of these transformations apply under/over approximations.
typedef int Z3_bool
Z3 Boolean type. It is just an alias for int.
typedef const char * Z3_string
Z3 string type. It is just an alias for const char *.
typedef Z3_string * Z3_string_ptr
typedef void Z3_error_handler (Z3_context c, Z3_error_code e)
Z3 custom error handler (See Z3_set_error_handler).
#define Z3_TRUE 1
True value. It is just an alias for 1.
#define Z3_FALSE 0
False value. It is just an alias for 0.
Types
Most of the types in the C API are opaque pointers.
Z3_config: a configuration object used to initialize logical contexts.
Z3_context: logical context. This is the main Z3 data-structure.
Z3_symbol: a Lisp-link symbol. It is used to name types, constants, and functions. A symbol can be created using string or integers.
Z3_ast: abstract syntax tree node. That is, the data-structure used in Z3 to represent terms, formulas and types.
Z3_sort: a kind of AST used to represent types.
Z3_app: a kind of AST used to represent constant and function declarations.
Z3_pattern: a kind of AST used to represent pattern and multi-patterns used to guide quantifier instantiation.
Z3_model: a model for the constraints asserted into the logical context.
enum Z3_lbool
Lifted Boolean type: false, undefined, true.
enum Z3_symbol_kind
In Z3, a symbol can be represented using integers and strings (See Z3_get_symbol_kind).
enum Z3_parameter_kind
The different kinds of parameters that can be associated with function symbols.
enum Z3_sort_kind
The different kinds of Z3 types (See Z3_get_sort_kind).
enum Z3_ast_kind
The different kinds of Z3 AST (abstract syntax trees). That is, terms, formulas and types.
enum Z3_decl_kind
The different kinds of interpreted function kinds.
enum Z3_search_failure
The different kinds of search failure types.
enum Z3_ast_print_mode
Z3 pretty printing modes (See Z3_set_ast_print_mode).
enum Z3_error_code
Z3 error codes (See Z3_get_error_code).
enum Z3_goal_prec
A Goal is essentially a set of formulas. Z3 provide APIs for building strategies/tactics for solving and transforming Goals. Some of these transformations apply under/over approximations.
typedef int Z3_bool
Z3 Boolean type. It is just an alias for int.
typedef const char * Z3_string
Z3 string type. It is just an alias for const char *.
typedef Z3_string * Z3_string_ptr
typedef void Z3_error_handler (Z3_error_code e)
Z3 custom error handler (See Z3_set_error_handler).
#define Z3_TRUE 1
True value. It is just an alias for 1.
#define Z3_FALSE 0
False value. It is just an alias for 0.
External Theory Plugins
typedef Z3_bool Z3_reduce_eq_callback_fptr (__in Z3_theory t, __in Z3_ast a, __in Z3_ast b, __out Z3_ast *r)
typedef Z3_bool Z3_reduce_app_callback_fptr (__in Z3_theory, __in Z3_func_decl, __in unsigned, __in Z3_ast const [], __out Z3_ast *)
typedef Z3_bool Z3_reduce_distinct_callback_fptr (__in Z3_theory, __in unsigned, __in Z3_ast const [], __out Z3_ast *)
typedef void Z3_theory_callback_fptr (__in Z3_theory t)
typedef Z3_bool Z3_theory_final_check_callback_fptr (__in Z3_theory)
typedef void Z3_theory_ast_callback_fptr (__in Z3_theory, __in Z3_ast)
typedef void Z3_theory_ast_bool_callback_fptr (__in Z3_theory, __in Z3_ast, __in Z3_bool)
typedef void Z3_theory_ast_ast_callback_fptr (__in Z3_theory, __in Z3_ast, __in Z3_ast)
Z3_theory Z3_API Z3_mk_theory (__in Z3_context c, __in Z3_string th_name, __in Z3_theory_data data)
Create a new user defined theory. The new theory will be identified by the name th_name. A theory must be created before asserting any assertion to the given context. Return NULL in case of failure.
Z3_theory_data Z3_API Z3_theory_get_ext_data (__in Z3_theory t)
Return a pointer to the external data-structure supplied to the function Z3_mk_theory.
Z3_sort Z3_API Z3_theory_mk_sort (__in Z3_context c, __in Z3_theory t, __in Z3_symbol s)
Create an interpreted theory sort.
Z3_ast Z3_API Z3_theory_mk_value (__in Z3_context c, __in Z3_theory t, __in Z3_symbol n, __in Z3_sort s)
Create an interpreted theory constant value. Values are assumed to be different from each other.
Z3_ast Z3_API Z3_theory_mk_constant (__in Z3_context c, __in Z3_theory t, __in Z3_symbol n, __in Z3_sort s)
Create an interpreted constant for the given theory.
Z3_func_decl Z3_API Z3_theory_mk_func_decl (__in Z3_context c, __in Z3_theory t, __in Z3_symbol n, __in unsigned domain_size, __in_ecount(domain_size) Z3_sort const domain[], __in Z3_sort range)
Create an interpreted function declaration for the given theory.
Z3_context Z3_API Z3_theory_get_context (__in Z3_theory t)
Return the context where the given theory is installed.
void Z3_API Z3_set_delete_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when theory t is deleted. This callback should be used to delete external data-structures associated with the given theory.
void Z3_API Z3_set_reduce_app_callback (__in Z3_theory t, __in Z3_reduce_app_callback_fptr f)
Set a callback for simplifying operators of the given theory. The callback f is invoked by Z3's simplifier.
void Z3_API Z3_set_reduce_eq_callback (__in Z3_theory t, __in Z3_reduce_eq_callback_fptr f)
Set a callback for simplifying the atom s_1 = s_2, when the sort of s_1 and s_2 is an interpreted sort of the given theory. The callback f is invoked by Z3's simplifier.
void Z3_API Z3_set_reduce_distinct_callback (__in Z3_theory t, __in Z3_reduce_distinct_callback_fptr f)
Set a callback for simplifying the atom distinct(s_1, ..., s_n), when the sort of s_1, ..., s_n is an interpreted sort of the given theory. The callback f is invoked by Z3's simplifier.
void Z3_API Z3_set_new_app_callback (__in Z3_theory t, __in Z3_theory_ast_callback_fptr f)
Set a callback that is invoked when a theory application is finally added into the logical context. Note that, not every application contained in an asserted expression is actually added into the logical context because it may be simplified during a preprocessing step.
void Z3_API Z3_set_new_elem_callback (__in Z3_theory t, __in Z3_theory_ast_callback_fptr f)
Set a callback that is invoked when an expression of sort s, where s is an interpreted sort of the theory t, is finally added into the logical context. Note that, not every expression contained in an asserted expression is actually added into the logical context because it may be simplified during a preprocessing step.
void Z3_API Z3_set_init_search_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when Z3 starts searching for a satisfying assignment.
void Z3_API Z3_set_push_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when Z3 creates a case-split (aka backtracking point).
void Z3_API Z3_set_pop_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when Z3 backtracks a case-split.
void Z3_API Z3_set_restart_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when Z3 restarts the search for a satisfying assignment.
void Z3_API Z3_set_reset_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when the logical context is reset by the user. This callback is useful for reseting any data-structure maintained by the user theory solver.
void Z3_API Z3_set_final_check_callback (__in Z3_theory t, __in Z3_theory_final_check_callback_fptr f)
Set a callback that is invoked before Z3 starts building a model. A theory may use this callback to perform expensive operations.
void Z3_API Z3_set_new_eq_callback (__in Z3_theory t, __in Z3_theory_ast_ast_callback_fptr f)
Set a callback that is invoked when an equality s_1 = s_2 is found by the logical context.
void Z3_API Z3_set_new_diseq_callback (__in Z3_theory t, __in Z3_theory_ast_ast_callback_fptr f)
Set a callback that is invoked when a disequality s_1 != s_2 is found by the logical context.
void Z3_API Z3_set_new_assignment_callback (__in Z3_theory t, __in Z3_theory_ast_bool_callback_fptr f)
Set a callback that is invoked when a theory predicate is assigned to true/false by Z3.
void Z3_API Z3_set_new_relevant_callback (__in Z3_theory t, __in Z3_theory_ast_callback_fptr f)
Set a callback that is invoked when an expression is marked as relevant during the search. This callback is only invoked when relevancy propagation is enabled.
void Z3_API Z3_theory_assert_axiom (__in Z3_theory t, __in Z3_ast ax)
Assert a theory axiom/lemmas during the search.
void Z3_API Z3_theory_assume_eq (__in Z3_theory t, __in Z3_ast lhs, __in Z3_ast rhs)
Inform to the logical context that lhs and rhs have the same interpretation in the model being built by theory t. If lhs = rhs is inconsistent with other theories, then the logical context will backtrack.
void Z3_API Z3_theory_enable_axiom_simplification (__in Z3_theory t, __in Z3_bool flag)
Enable/disable the simplification of theory axioms asserted using Z3_theory_assert_axiom. By default, the simplification of theory specific operators is disabled. That is, the reduce theory callbacks are not invoked for theory axioms. The default behavior is useful when asserting axioms stating properties of theory operators.
Z3_ast Z3_API Z3_theory_get_eqc_root (__in Z3_theory t, __in Z3_ast n)
Return the root of the equivalence class containing n.
Z3_ast Z3_API Z3_theory_get_eqc_next (__in Z3_theory t, __in Z3_ast n)
Return the next element in the equivalence class containing n.
unsigned Z3_API Z3_theory_get_num_parents (__in Z3_theory t, __in Z3_ast n)
Return the number of parents of n that are operators of the given theory.
Z3_ast Z3_API Z3_theory_get_parent (__in Z3_theory t, __in Z3_ast n, __in unsigned i)
Return the i-th parent of n. See Z3_theory_get_num_parents.
Z3_bool Z3_API Z3_theory_is_value (__in Z3_theory t, __in Z3_ast n)
Return Z3_TRUE if n is an interpreted theory value.
Z3_bool Z3_API Z3_theory_is_decl (__in Z3_theory t, __in Z3_func_decl d)
Return Z3_TRUE if d is an interpreted theory declaration.
unsigned Z3_API Z3_theory_get_num_elems (__in Z3_theory t)
Return the number of expressions of the given theory in the logical context. These are the expressions notified using the callback Z3_set_new_elem_callback.
Z3_ast Z3_API Z3_theory_get_elem (__in Z3_theory t, __in unsigned i)
Return the i-th elem of the given theory in the logical context.
unsigned Z3_API Z3_theory_get_num_apps (__in Z3_theory t)
Return the number of theory applications in the logical context. These are the expressions notified using the callback Z3_set_new_app_callback.
Z3_ast Z3_API Z3_theory_get_app (__in Z3_theory t, __in unsigned i)
Return the i-th application of the given theory in the logical context.
Fixedpoint facilities
typedef void Z3_fixedpoint_reduce_assign_callback_fptr (__in void *, __in Z3_func_decl, __in unsigned, __in Z3_ast const [], __in unsigned, __in Z3_ast const [])
The following utilities allows adding user-defined domains.
typedef void Z3_fixedpoint_reduce_app_callback_fptr (__in void *, __in Z3_func_decl, __in unsigned, __in Z3_ast const [], __out Z3_ast *)
Z3_fixedpoint Z3_API Z3_mk_fixedpoint (__in Z3_context c)
Create a new fixedpoint context.
void Z3_API Z3_fixedpoint_inc_ref (__in Z3_context c, __in Z3_fixedpoint d)
Increment the reference counter of the given fixedpoint context.
void Z3_API Z3_fixedpoint_dec_ref (__in Z3_context c, __in Z3_fixedpoint d)
Decrement the reference counter of the given fixedpoint context.
void Z3_API Z3_fixedpoint_add_rule (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_ast rule, __in Z3_symbol name)
Add a universal Horn clause as a named rule. The horn_rule should be of the form:
void Z3_API Z3_fixedpoint_add_fact (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_func_decl r, __in unsigned num_args, __in_ecount(num_args) unsigned args[])
Add a Database fact.
void Z3_API Z3_fixedpoint_assert (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_ast axiom)
Assert a constraint to the fixedpoint context.
Z3_lbool Z3_API Z3_fixedpoint_query (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_ast query)
Pose a query against the asserted rules.
Z3_lbool Z3_API Z3_fixedpoint_query_relations (__in Z3_context c, __in Z3_fixedpoint d, __in unsigned num_relations, __in_ecount(num_relations) Z3_func_decl const relations[])
Pose multiple queries against the asserted rules.
Z3_ast Z3_API Z3_fixedpoint_get_answer (__in Z3_context c, __in Z3_fixedpoint d)
Retrieve a formula that encodes satisfying answers to the query.
Z3_string Z3_API Z3_fixedpoint_get_reason_unknown (__in Z3_context c, __in Z3_fixedpoint d)
Retrieve a string that describes the last status returned by Z3_fixedpoint_query.
Z3_stats Z3_API Z3_fixedpoint_get_statistics (__in Z3_context c, __in Z3_fixedpoint d)
Retrieve statistics information from the last call to Z3_fixedpoint_query.
void Z3_API Z3_fixedpoint_register_relation (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_func_decl f)
Register relation as Fixedpoint defined. Fixedpoint defined relations have least-fixedpoint semantics. For example, the relation is empty if it does not occur in a head or a fact.
void Z3_API Z3_fixedpoint_set_predicate_representation (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_func_decl f, __in unsigned num_relations, __in_ecount(num_relations) Z3_symbol const relation_kinds[])
Configure the predicate representation.
Z3_ast_vector Z3_API Z3_fixedpoint_simplify_rules (__in Z3_context c, __in Z3_fixedpoint f, __in unsigned num_rules, __in_ecount(num_rules) Z3_ast rules[], __in unsigned num_outputs, __in_ecount(num_outputs) Z3_func_decl outputs[])
Simplify rules into a set of new rules that are returned. The simplification routines apply inlining, quantifier elimination, and other algebraic simplifications.
Z3_string Z3_API Z3_fixedpoint_to_string (__in Z3_context c, __in Z3_fixedpoint f, __in unsigned num_queries, __in_ecount(num_queries) Z3_ast queries[])
Print the current rules and background axioms as a string.
void Z3_API Z3_fixedpoint_init (__in Z3_context c, __in Z3_fixedpoint d, __in void *state)
Initialize the context with a user-defined state.
void Z3_API Z3_fixedpoint_set_reduce_assign_callback (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_fixedpoint_reduce_assign_callback_fptr cb)
Register a callback to destructive updates.
void Z3_API Z3_fixedpoint_set_reduce_app_callback (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_fixedpoint_reduce_app_callback_fptr cb)
Register a callback for buildling terms based on the relational operators.
External Theory Plugins
typedef Z3_bool Z3_simplify_ast_fn (__in void *, __in Z3_ast, __out Z3_ast *, __out Z3_ast *)
typedef Z3_bool Z3_reduce_eq_callback_fptr (__in Z3_theory t, __in Z3_ast a, __in Z3_ast b, __out Z3_ast *r)
typedef Z3_bool Z3_reduce_app_callback_fptr (__in Z3_theory, __in Z3_func_decl, __in unsigned, __in Z3_ast const [], __out Z3_ast *)
typedef Z3_bool Z3_reduce_distinct_callback_fptr (__in Z3_theory, __in unsigned, __in Z3_ast const [], __out Z3_ast *)
typedef void Z3_theory_callback_fptr (__in Z3_theory t)
typedef Z3_bool Z3_theory_final_check_callback_fptr (__in Z3_theory)
typedef void Z3_theory_ast_callback_fptr (__in Z3_theory, __in Z3_ast)
typedef void Z3_theory_ast_bool_callback_fptr (__in Z3_theory, __in Z3_ast, __in Z3_bool)
typedef void Z3_theory_ast_ast_callback_fptr (__in Z3_theory, __in Z3_ast, __in Z3_ast)
void Z3_API Z3_set_simplifier_callback (__in Z3_context c, __in void *user_context, __in Z3_simplify_ast_fn *simplifier)
Register a user-supplied simplification function. The simplifier gets invoked during pre-processing.
Z3_theory Z3_API Z3_mk_theory (__in Z3_context c, __in_z Z3_string th_name, __in Z3_theory_data data)
Create a new user defined theory. The new theory will be identified by the name th_name. A theory must be created before asserting any assertion to the given context. Return NULL in case of failure.
Fixedpoint and Datalog facilities
typedef void Z3_datalog_reduce_assign_callback_fptr (__in Z3_context, __in Z3_func_decl, __in unsigned, __in Z3_ast const [], __in unsigned, __in Z3_ast const [])
The following utilities allows adding user-defined domains.
typedef void Z3_datalog_reduce_app_callback_fptr (__in Z3_context, __in Z3_func_decl, __in unsigned, __in Z3_ast const [], __out Z3_ast *)
void Z3_API Z3_datalog_register_relation (__in Z3_context c, __in Z3_func_decl f)
Register relation as Datalog defined. Datalog defined relations have least-fixedpoint semantics. For example, the relation is empty if it does not occur in a head or a fact.
void Z3_API Z3_datalog_add_rule (__in Z3_context c, __in Z3_ast horn_rule, __in Z3_symbol name)
Add a universal Horn clause as a named rule. The horn_rule should be of the form:
Z3_ast Z3_API Z3_datalog_query (__in Z3_context c, __in Z3_ast q)
Pose a query against the asserted rules.
void Z3_API Z3_datalog_set_predicate_representation (__in Z3_context c, __in Z3_func_decl f, __in unsigned num_relations, __in_ecount(num_relations) Z3_symbol const relation_kinds[])
Configure the predicate representation.
void Z3_API Z3_datalog_parse_file (__in Z3_context c, Z3_string filename)
Parse a file in Datalog format and process the queries in it.
Z3_string Z3_API Z3_fixpoint_benchmark_to_string (__in Z3_context c, __in unsigned num_axioms, __in_ecount(num_axioms) Z3_ast axioms[], __in unsigned num_rules, __in_ecount(num_rules) Z3_ast rules[], __in unsigned num_queries, __in_ecount(num_queries) Z3_ast queries[])
Convert a set of axioms, rules and queries to a benchmark in SMT-LIB2 + rules format. This routine can be used for dumping rules.
Z3_asts Z3_API Z3_fixpoint_simplify_rules (__in Z3_context c, __in unsigned num_rules, __in_ecount(num_rules) Z3_ast rules[], __in unsigned num_outputs, __in_ecount(num_outputs) Z3_func_decl outputs[])
Simplify rules into a set of new rules that are returned. The simplification routines apply inlining, quantifier elimination, and other algebraic simplifications.
void Z3_API Z3_del_asts (__in Z3_context c, __in Z3_asts asts)
Delete array of asts.
unsigned Z3_API Z3_asts_count (__in Z3_context c, __in Z3_asts asts)
Retrieve length of asts array.
Z3_ast Z3_API Z3_asts_get (__in Z3_context c, __in Z3_asts asts, __in unsigned index)
Access element of asts array at index.
void Z3_API Z3_datalog_init (__in Z3_context c, __in void *state)
Initialize the context with a user-defined state.
void *Z3_API Z3_datalog_get_context (__in Z3_context c)
Retrieve the user-define state.
void Z3_API Z3_datalog_set_reduce_assign_callback (__in Z3_context c, __in Z3_datalog_reduce_assign_callback_fptr cb)
Register a callback to destructive updates.
void Z3_API Z3_datalog_set_reduce_app_callback (__in Z3_context c, __in Z3_datalog_reduce_app_callback_fptr cb)
Register a callback for buildling terms based on the relational operators.
Create configuration
Z3_config Z3_API Z3_mk_config ()
Create a configuration.
void Z3_API Z3_del_config (__in Z3_config c)
Delete the given configuration object.
void Z3_API Z3_set_param_value (__in Z3_config c, __in Z3_string param_id, __in Z3_string param_value)
Set a configuration parameter.
Create context
Z3_context Z3_API Z3_mk_context (__in Z3_config c)
Create a context using the given configuration.
Z3_context Z3_API Z3_mk_context_rc (__in Z3_config c)
Create a context using the given configuration. This function is similar to Z3_mk_context. However, in the context returned by this function, the user is responsible for managing Z3_ast reference counters. Managing reference counters is a burden and error-prone, but allows the user to use the memory more efficiently. The user must invoke Z3_inc_ref for any Z3_ast returned by Z3, and Z3_dec_ref whenever the Z3_ast is not needed anymore. This idiom is similar to the one used in BDD (binary decision diagrams) packages such as CUDD.
void Z3_API Z3_del_context (__in Z3_context c)
Delete the given logical context.
void Z3_API Z3_inc_ref (__in Z3_context c, __in Z3_ast a)
Increment the reference counter of the given AST. The context c should have been created using Z3_mk_context_rc. This function is a NOOP if c was created using Z3_mk_context.
void Z3_API Z3_dec_ref (__in Z3_context c, __in Z3_ast a)
Decrement the reference counter of the given AST. The context c should have been created using Z3_mk_context_rc. This function is a NOOP if c was created using Z3_mk_context.
void Z3_API Z3_update_param_value (__in Z3_context c, __in Z3_string param_id, __in Z3_string param_value)
Update a mutable configuration parameter.
Z3_bool Z3_API Z3_get_param_value (__in Z3_context c, __in Z3_string param_id, __out Z3_string_ptr param_value)
Get a configuration parameter.
void Z3_API Z3_interrupt (__in Z3_context c)
Interrupt the execution of a Z3 procedure. This procedure can be used to interrupt: solvers, simplifiers and tactics.
Parameters
Z3_params Z3_API Z3_mk_params (__in Z3_context c)
Create a Z3 (empty) parameter set. Starting at Z3 4.0, parameter sets are used to configure many components such as: simplifiers, tactics, solvers, etc.
void Z3_API Z3_params_inc_ref (__in Z3_context c, __in Z3_params p)
Increment the reference counter of the given parameter set.
void Z3_API Z3_params_dec_ref (__in Z3_context c, __in Z3_params p)
Decrement the reference counter of the given parameter set.
void Z3_API Z3_params_set_bool (__in Z3_context c, __in Z3_params p, __in Z3_symbol k, __in Z3_bool v)
Add a Boolean parameter k with value v to the parameter set p.
void Z3_API Z3_params_set_uint (__in Z3_context c, __in Z3_params p, __in Z3_symbol k, __in unsigned v)
Add a unsigned parameter k with value v to the parameter set p.
void Z3_API Z3_params_set_double (__in Z3_context c, __in Z3_params p, __in Z3_symbol k, __in double v)
Add a double parameter k with value v to the parameter set p.
void Z3_API Z3_params_set_symbol (__in Z3_context c, __in Z3_params p, __in Z3_symbol k, __in Z3_symbol v)
Add a symbol parameter k with value v to the parameter set p.
Z3_string Z3_API Z3_params_to_string (__in Z3_context c, __in Z3_params p)
Convert a parameter set into a string. This function is mainly used for printing the contents of a parameter set.
Symbols
Z3_symbol Z3_API Z3_mk_int_symbol (__in Z3_context c, __in int i)
Create a Z3 symbol using an integer.
Z3_symbol Z3_API Z3_mk_string_symbol (__in Z3_context c, __in Z3_string s)
Create a Z3 symbol using a C string.
Sorts
Z3_sort Z3_API Z3_mk_uninterpreted_sort (__in Z3_context c, __in Z3_symbol s)
Create a free (uninterpreted) type using the given name (symbol).
Z3_sort Z3_API Z3_mk_bool_sort (__in Z3_context c)
Create the Boolean type.
Z3_sort Z3_API Z3_mk_int_sort (__in Z3_context c)
Create the integer type.
Z3_sort Z3_API Z3_mk_real_sort (__in Z3_context c)
Create the real type.
Z3_sort Z3_API Z3_mk_bv_sort (__in Z3_context c, __in unsigned sz)
Create a bit-vector type of the given size.
Z3_sort Z3_API Z3_mk_finite_domain_sort (__in Z3_context c, __in Z3_symbol name, __in unsigned __int64 size)
Create a named finite domain sort.
Z3_sort Z3_API Z3_mk_array_sort (__in Z3_context c, __in Z3_sort domain, __in Z3_sort range)
Create an array type.
Z3_sort Z3_API Z3_mk_tuple_sort (__in Z3_context c, __in Z3_symbol mk_tuple_name, __in unsigned num_fields, __in_ecount(num_fields) Z3_symbol const field_names[], __in_ecount(num_fields) Z3_sort const field_sorts[], __out Z3_func_decl *mk_tuple_decl, __out_ecount(num_fields) Z3_func_decl proj_decl[])
Create a tuple type.
Z3_sort Z3_API Z3_mk_enumeration_sort (__in Z3_context c, __in Z3_symbol name, __in unsigned n, __in_ecount(n) Z3_symbol const enum_names[], __out_ecount(n) Z3_func_decl enum_consts[], __out_ecount(n) Z3_func_decl enum_testers[])
Create a enumeration sort.
Z3_sort Z3_API Z3_mk_list_sort (__in Z3_context c, __in Z3_symbol name, __in Z3_sort elem_sort, __out Z3_func_decl *nil_decl, __out Z3_func_decl *is_nil_decl, __out Z3_func_decl *cons_decl, __out Z3_func_decl *is_cons_decl, __out Z3_func_decl *head_decl, __out Z3_func_decl *tail_decl)
Create a list sort.
BEGIN_MLAPI_EXCLUDE
Z3_constructor Z3_API Z3_mk_constructor (__in Z3_context c, __in Z3_symbol name, __in Z3_symbol recognizer, __in unsigned num_fields, __in_ecount(num_fields) Z3_symbol const field_names[], __in_ecount(num_fields) Z3_sort_opt const sorts[], __in_ecount(num_fields) unsigned sort_refs[])
Create a constructor.
void Z3_API Z3_del_constructor (__in Z3_context c, __in Z3_constructor constr)
Reclaim memory allocated to constructor.
Z3_sort Z3_API Z3_mk_datatype (__in Z3_context c, __in Z3_symbol name, __in unsigned num_constructors, __inout_ecount(num_constructors) Z3_constructor constructors[])
Create datatype, such as lists, trees, records, enumerations or unions of records. The datatype may be recursive. Return the datatype sort.
Z3_constructor_list Z3_API Z3_mk_constructor_list (__in Z3_context c, __in unsigned num_constructors, __in_ecount(num_constructors) Z3_constructor const constructors[])
Create list of constructors.
void Z3_API Z3_del_constructor_list (__in Z3_context c, __in Z3_constructor_list clist)
Reclaim memory allocated for constructor list.
void Z3_API Z3_mk_datatypes (__in Z3_context c, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __out_ecount(num_sorts) Z3_sort sorts[], __inout_ecount(num_sorts) Z3_constructor_list constructor_lists[])
Create mutually recursive datatypes.
void Z3_API Z3_query_constructor (__in Z3_context c, __in Z3_constructor constr, __in unsigned num_fields, __out Z3_func_decl *constructor, __out Z3_func_decl *tester, __out_ecount(num_fields) Z3_func_decl accessors[])
Query constructor for declared functions.
Constants and Applications
Z3_func_decl Z3_API Z3_mk_func_decl (__in Z3_context c, __in Z3_symbol s, __in unsigned domain_size, __in_ecount(domain_size) Z3_sort const domain[], __in Z3_sort range)
Declare a constant or function.
Z3_ast Z3_API Z3_mk_app (__in Z3_context c, __in Z3_func_decl d, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create a constant or function application.
Z3_ast Z3_API Z3_mk_const (__in Z3_context c, __in Z3_symbol s, __in Z3_sort ty)
Declare and create a constant.
Z3_func_decl Z3_API Z3_mk_fresh_func_decl (__in Z3_context c, __in Z3_string prefix, __in unsigned domain_size, __in_ecount(domain_size) Z3_sort const domain[], __in Z3_sort range)
Declare a fresh constant or function.
Z3_ast Z3_API Z3_mk_fresh_const (__in Z3_context c, __in Z3_string prefix, __in Z3_sort ty)
Declare and create a fresh constant.
Propositional Logic and Equality
Z3_ast Z3_API Z3_mk_true (__in Z3_context c)
Create an AST node representing true.
Z3_ast Z3_API Z3_mk_false (__in Z3_context c)
Create an AST node representing false.
Z3_ast Z3_API Z3_mk_eq (__in Z3_context c, __in Z3_ast l, __in Z3_ast r)
Create an AST node representing l = r.
Z3_ast Z3_API Z3_mk_distinct (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing distinct(args[0], ..., args[num_args-1]).
Z3_ast Z3_API Z3_mk_not (__in Z3_context c, __in Z3_ast a)
Create an AST node representing not(a).
Z3_ast Z3_API Z3_mk_ite (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2, __in Z3_ast t3)
Create an AST node representing an if-then-else: ite(t1, t2, t3).
Z3_ast Z3_API Z3_mk_iff (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create an AST node representing t1 iff t2.
Z3_ast Z3_API Z3_mk_implies (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create an AST node representing t1 implies t2.
Z3_ast Z3_API Z3_mk_xor (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create an AST node representing t1 xor t2.
Z3_ast Z3_API Z3_mk_and (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing args[0] and ... and args[num_args-1].
Z3_ast Z3_API Z3_mk_or (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing args[0] or ... or args[num_args-1].
Arithmetic: Integers and Reals
Z3_ast Z3_API Z3_mk_add (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing args[0] + ... + args[num_args-1].
Z3_ast Z3_API Z3_mk_mul (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing args[0] * ... * args[num_args-1].
Z3_ast Z3_API Z3_mk_sub (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing args[0] - ... - args[num_args - 1].
Z3_ast Z3_API Z3_mk_unary_minus (__in Z3_context c, __in Z3_ast arg)
Create an AST node representing -arg.
Z3_ast Z3_API Z3_mk_div (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Create an AST node representing arg1 div arg2.
Z3_ast Z3_API Z3_mk_mod (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Create an AST node representing arg1 mod arg2.
Z3_ast Z3_API Z3_mk_rem (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Create an AST node representing arg1 rem arg2.
Z3_ast Z3_API Z3_mk_power (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Create an AST node representing arg1^arg2.
Z3_ast Z3_API Z3_mk_lt (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create less than.
Z3_ast Z3_API Z3_mk_le (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create less than or equal to.
Z3_ast Z3_API Z3_mk_gt (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create greater than.
Z3_ast Z3_API Z3_mk_ge (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create greater than or equal to.
Z3_ast Z3_API Z3_mk_int2real (__in Z3_context c, __in Z3_ast t1)
Coerce an integer to a real.
Z3_ast Z3_API Z3_mk_real2int (__in Z3_context c, __in Z3_ast t1)
Coerce a real to an integer.
Z3_ast Z3_API Z3_mk_is_int (__in Z3_context c, __in Z3_ast t1)
Check if a real number is an integer.
Bit-vectors
Z3_ast Z3_API Z3_mk_bvnot (__in Z3_context c, __in Z3_ast t1)
Bitwise negation.
Z3_ast Z3_API Z3_mk_bvredand (__in Z3_context c, __in Z3_ast t1)
Take conjunction of bits in vector, return vector of length 1.
Z3_ast Z3_API Z3_mk_bvredor (__in Z3_context c, __in Z3_ast t1)
Take disjunction of bits in vector, return vector of length 1.
Z3_ast Z3_API Z3_mk_bvand (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise and.
Z3_ast Z3_API Z3_mk_bvor (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise or.
Z3_ast Z3_API Z3_mk_bvxor (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise exclusive-or.
Z3_ast Z3_API Z3_mk_bvnand (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise nand.
Z3_ast Z3_API Z3_mk_bvnor (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise nor.
Z3_ast Z3_API Z3_mk_bvxnor (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise xnor.
Z3_ast Z3_API Z3_mk_bvneg (__in Z3_context c, __in Z3_ast t1)
Standard two's complement unary minus.
Z3_ast Z3_API Z3_mk_bvadd (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Standard two's complement addition.
Z3_ast Z3_API Z3_mk_bvsub (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Standard two's complement subtraction.
Z3_ast Z3_API Z3_mk_bvmul (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Standard two's complement multiplication.
Z3_ast Z3_API Z3_mk_bvudiv (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned division.
Z3_ast Z3_API Z3_mk_bvsdiv (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed division.
Z3_ast Z3_API Z3_mk_bvurem (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned remainder.
Z3_ast Z3_API Z3_mk_bvsrem (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed remainder (sign follows dividend).
Z3_ast Z3_API Z3_mk_bvsmod (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed remainder (sign follows divisor).
Z3_ast Z3_API Z3_mk_bvult (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned less than.
Z3_ast Z3_API Z3_mk_bvslt (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed less than.
Z3_ast Z3_API Z3_mk_bvule (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned less than or equal to.
Z3_ast Z3_API Z3_mk_bvsle (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed less than or equal to.
Z3_ast Z3_API Z3_mk_bvuge (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned greater than or equal to.
Z3_ast Z3_API Z3_mk_bvsge (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed greater than or equal to.
Z3_ast Z3_API Z3_mk_bvugt (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned greater than.
Z3_ast Z3_API Z3_mk_bvsgt (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed greater than.
Z3_ast Z3_API Z3_mk_concat (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Concatenate the given bit-vectors.
Z3_ast Z3_API Z3_mk_extract (__in Z3_context c, __in unsigned high, __in unsigned low, __in Z3_ast t1)
Extract the bits high down to low from a bitvector of size m to yield a new bitvector of size n, where n = high - low + 1.
Z3_ast Z3_API Z3_mk_sign_ext (__in Z3_context c, __in unsigned i, __in Z3_ast t1)
Sign-extend of the given bit-vector to the (signed) equivalent bitvector of size m+i, where m is the size of the given bit-vector.
Z3_ast Z3_API Z3_mk_zero_ext (__in Z3_context c, __in unsigned i, __in Z3_ast t1)
Extend the given bit-vector with zeros to the (unsigned) equivalent bitvector of size m+i, where m is the size of the given bit-vector.
Z3_ast Z3_API Z3_mk_repeat (__in Z3_context c, __in unsigned i, __in Z3_ast t1)
Repeat the given bit-vector up length i.
Z3_ast Z3_API Z3_mk_bvshl (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Shift left.
Z3_ast Z3_API Z3_mk_bvlshr (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Logical shift right.
Z3_ast Z3_API Z3_mk_bvashr (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Arithmetic shift right.
Z3_ast Z3_API Z3_mk_rotate_left (__in Z3_context c, __in unsigned i, __in Z3_ast t1)
Rotate bits of t1 to the left i times.
Z3_ast Z3_API Z3_mk_rotate_right (__in Z3_context c, __in unsigned i, __in Z3_ast t1)
Rotate bits of t1 to the right i times.
Z3_ast Z3_API Z3_mk_ext_rotate_left (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Rotate bits of t1 to the left t2 times.
Z3_ast Z3_API Z3_mk_ext_rotate_right (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Rotate bits of t1 to the right t2 times.
Z3_ast Z3_API Z3_mk_int2bv (__in Z3_context c, __in unsigned n, __in Z3_ast t1)
Create an n bit bit-vector from the integer argument t1.
Z3_ast Z3_API Z3_mk_bv2int (__in Z3_context c, __in Z3_ast t1, Z3_bool is_signed)
Create an integer from the bit-vector argument t1. If is_signed is false, then the bit-vector t1 is treated as unsigned. So the result is non-negative and in the range [0..2^N-1], where N are the number of bits in t1. If is_signed is true, t1 is treated as a signed bit-vector.
Z3_ast Z3_API Z3_mk_bvadd_no_overflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2, Z3_bool is_signed)
Create a predicate that checks that the bit-wise addition of t1 and t2 does not overflow.
Z3_ast Z3_API Z3_mk_bvadd_no_underflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create a predicate that checks that the bit-wise signed addition of t1 and t2 does not underflow.
Z3_ast Z3_API Z3_mk_bvsub_no_overflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create a predicate that checks that the bit-wise signed subtraction of t1 and t2 does not overflow.
Z3_ast Z3_API Z3_mk_bvsub_no_underflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2, Z3_bool is_signed)
Create a predicate that checks that the bit-wise subtraction of t1 and t2 does not underflow.
Z3_ast Z3_API Z3_mk_bvsdiv_no_overflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create a predicate that checks that the bit-wise signed division of t1 and t2 does not overflow.
Z3_ast Z3_API Z3_mk_bvneg_no_overflow (__in Z3_context c, __in Z3_ast t1)
Check that bit-wise negation does not overflow when t1 is interpreted as a signed bit-vector.
Z3_ast Z3_API Z3_mk_bvmul_no_overflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2, Z3_bool is_signed)
Create a predicate that checks that the bit-wise multiplication of t1 and t2 does not overflow.
Z3_ast Z3_API Z3_mk_bvmul_no_underflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create a predicate that checks that the bit-wise signed multiplication of t1 and t2 does not underflow.
Arrays
Z3_ast Z3_API Z3_mk_select (__in Z3_context c, __in Z3_ast a, __in Z3_ast i)
Array read. The argument a is the array and i is the index of the array that gets read.
Z3_ast Z3_API Z3_mk_store (__in Z3_context c, __in Z3_ast a, __in Z3_ast i, __in Z3_ast v)
Array update.
Z3_ast Z3_API Z3_mk_const_array (__in Z3_context c, __in Z3_sort domain, __in Z3_ast v)
Create the constant array.
Z3_ast Z3_API Z3_mk_map (__in Z3_context c, __in Z3_func_decl f, unsigned n, __in Z3_ast const *args)
map f on the the argument arrays.
Z3_ast Z3_API Z3_mk_array_default (__in Z3_context c, __in Z3_ast array)
Access the array default value. Produces the default range value, for arrays that can be represented as finite maps with a default range value.
Sets
Z3_sort Z3_API Z3_mk_set_sort (__in Z3_context c, __in Z3_sort ty)
Create Set type.
Z3_ast Z3_API Z3_mk_empty_set (__in Z3_context c, __in Z3_sort domain)
Create the empty set.
Z3_ast Z3_API Z3_mk_full_set (__in Z3_context c, __in Z3_sort domain)
Create the full set.
Z3_ast Z3_API Z3_mk_set_add (__in Z3_context c, __in Z3_ast set, __in Z3_ast elem)
Add an element to a set.
Z3_ast Z3_API Z3_mk_set_del (__in Z3_context c, __in Z3_ast set, __in Z3_ast elem)
Remove an element to a set.
Z3_ast Z3_API Z3_mk_set_union (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Take the union of a list of sets.
Z3_ast Z3_API Z3_mk_set_intersect (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Take the intersection of a list of sets.
Z3_ast Z3_API Z3_mk_set_difference (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Take the set difference between two sets.
Z3_ast Z3_API Z3_mk_set_complement (__in Z3_context c, __in Z3_ast arg)
Take the complement of a set.
Z3_ast Z3_API Z3_mk_set_member (__in Z3_context c, __in Z3_ast elem, __in Z3_ast set)
Check for set membership.
Z3_ast Z3_API Z3_mk_set_subset (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Check for subsetness of sets.
Numerals
Z3_ast Z3_API Z3_mk_numeral (__in Z3_context c, __in Z3_string numeral, __in Z3_sort ty)
Create a numeral of a given sort.
Z3_ast Z3_API Z3_mk_real (__in Z3_context c, __in int num, __in int den)
Create a real from a fraction.
Z3_ast Z3_API Z3_mk_int (__in Z3_context c, __in int v, __in Z3_sort ty)
Create a numeral of an int, bit-vector, or finite-domain sort.
Z3_ast Z3_API Z3_mk_unsigned_int (__in Z3_context c, __in unsigned v, __in Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
Z3_ast Z3_API Z3_mk_int64 (__in Z3_context c, __in __int64 v, __in Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
Z3_ast Z3_API Z3_mk_unsigned_int64 (__in Z3_context c, __in unsigned __int64 v, __in Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
Quantifiers
Z3_pattern Z3_API Z3_mk_pattern (__in Z3_context c, __in unsigned num_patterns, __in_ecount(num_patterns) Z3_ast const terms[])
Create a pattern for quantifier instantiation.
Z3_ast Z3_API Z3_mk_bound (__in Z3_context c, __in unsigned index, __in Z3_sort ty)
Create a bound variable.
Z3_ast Z3_API Z3_mk_forall (__in Z3_context c, __in unsigned weight, __in unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in unsigned num_decls, __in_ecount(num_decls) Z3_sort const sorts[], __in_ecount(num_decls) Z3_symbol const decl_names[], __in Z3_ast body)
Create a forall formula. It takes an expression body that contains bound variables of the same sorts as the sorts listed in the array sorts. The bound variables are de-Bruijn indices created using Z3_mk_bound. The array decl_names contains the names that the quantified formula uses for the bound variables. Z3 applies the convention that the last element in the decl_names and sorts array refers to the variable with index 0, the second to last element of decl_names and sorts refers to the variable with index 1, etc.
Z3_ast Z3_API Z3_mk_exists (__in Z3_context c, __in unsigned weight, __in unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in unsigned num_decls, __in_ecount(num_decls) Z3_sort const sorts[], __in_ecount(num_decls) Z3_symbol const decl_names[], __in Z3_ast body)
Create an exists formula. Similar to Z3_mk_forall.
Z3_ast Z3_API Z3_mk_quantifier (__in Z3_context c, __in Z3_bool is_forall, __in unsigned weight, __in unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in unsigned num_decls, __in_ecount(num_decls) Z3_sort const sorts[], __in_ecount(num_decls) Z3_symbol const decl_names[], __in Z3_ast body)
Create a quantifier - universal or existential, with pattern hints. See the documentation for Z3_mk_forall for an explanation of the parameters.
Z3_ast Z3_API Z3_mk_quantifier_ex (__in Z3_context c, __in Z3_bool is_forall, __in unsigned weight, __in Z3_symbol quantifier_id, __in Z3_symbol skolem_id, __in unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in unsigned num_no_patterns, __in_ecount(num_no_patterns) Z3_ast const no_patterns[], __in unsigned num_decls, __in_ecount(num_decls) Z3_sort const sorts[], __in_ecount(num_decls) Z3_symbol const decl_names[], __in Z3_ast body)
Create a quantifier - universal or existential, with pattern hints, no patterns, and attributes.
Z3_ast Z3_API Z3_mk_forall_const (__in Z3_context c, unsigned weight, unsigned num_bound, __in_ecount(num_bound) Z3_app const bound[], unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in Z3_ast body)
Create a universal quantifier using a list of constants that will form the set of bound variables.
Z3_ast Z3_API Z3_mk_exists_const (__in Z3_context c, unsigned weight, unsigned num_bound, __in_ecount(num_bound) Z3_app const bound[], unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in Z3_ast body)
Similar to Z3_mk_forall_const.
Z3_ast Z3_API Z3_mk_quantifier_const (__in Z3_context c, Z3_bool is_forall, unsigned weight, unsigned num_bound, __in_ecount(num_bound) Z3_app const bound[], unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in Z3_ast body)
Create a universal or existential quantifier using a list of constants that will form the set of bound variables.
Z3_ast Z3_API Z3_mk_quantifier_const_ex (__in Z3_context c, Z3_bool is_forall, unsigned weight, __in Z3_symbol quantifier_id, __in Z3_symbol skolem_id, unsigned num_bound, __in_ecount(num_bound) Z3_app const bound[], unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], unsigned num_no_patterns, __in_ecount(num_no_patterns) Z3_ast const no_patterns[], __in Z3_ast body)
Create a universal or existential quantifier using a list of constants that will form the set of bound variables.
Accessors
Z3_symbol_kind Z3_API Z3_get_symbol_kind (__in Z3_context c, __in Z3_symbol s)
Return Z3_INT_SYMBOL if the symbol was constructed using Z3_mk_int_symbol, and Z3_STRING_SYMBOL if the symbol was constructed using Z3_mk_string_symbol.
int Z3_API Z3_get_symbol_int (__in Z3_context c, __in Z3_symbol s)
Return the symbol int value.
Z3_string Z3_API Z3_get_symbol_string (__in Z3_context c, __in Z3_symbol s)
Return the symbol name.
Z3_symbol Z3_API Z3_get_sort_name (__in Z3_context c, __in Z3_sort d)
Return the sort name as a symbol.
unsigned Z3_API Z3_get_sort_id (__in Z3_context c, Z3_sort s)
Return a unique identifier for s.
Z3_ast Z3_API Z3_sort_to_ast (__in Z3_context c, __in Z3_sort s)
Convert a Z3_sort into Z3_ast. This is just type casting.
Z3_bool Z3_API Z3_is_eq_sort (__in Z3_context c, __in Z3_sort s1, __in Z3_sort s2)
compare sorts.
Z3_sort_kind Z3_API Z3_get_sort_kind (__in Z3_context c, __in Z3_sort t)
Return the sort kind (e.g., array, tuple, int, bool, etc).
unsigned Z3_API Z3_get_bv_sort_size (__in Z3_context c, __in Z3_sort t)
Return the size of the given bit-vector sort.
Z3_bool Z3_API Z3_get_finite_domain_sort_size (__in Z3_context c, __in Z3_sort s, __out unsigned __int64 *r)
Store the size of the sort in r. Return Z3_FALSE if the call failed.That is, Z3_get_sort_kind(s) == Z3_FINITE_DOMAIN_SORT.
Z3_sort Z3_API Z3_get_array_sort_domain (__in Z3_context c, __in Z3_sort t)
Return the domain of the given array sort.
Z3_sort Z3_API Z3_get_array_sort_range (__in Z3_context c, __in Z3_sort t)
Return the range of the given array sort.
Z3_func_decl Z3_API Z3_get_tuple_sort_mk_decl (__in Z3_context c, __in Z3_sort t)
Return the constructor declaration of the given tuple sort.
unsigned Z3_API Z3_get_tuple_sort_num_fields (__in Z3_context c, __in Z3_sort t)
Return the number of fields of the given tuple sort.
Z3_func_decl Z3_API Z3_get_tuple_sort_field_decl (__in Z3_context c, __in Z3_sort t, __in unsigned i)
Return the i-th field declaration (i.e., projection function declaration) of the given tuple sort.
unsigned Z3_API Z3_get_datatype_sort_num_constructors (__in Z3_context c, __in Z3_sort t)
Return number of constructors for datatype.
Z3_func_decl Z3_API Z3_get_datatype_sort_constructor (__in Z3_context c, __in Z3_sort t, unsigned idx)
Return idx'th constructor.
Z3_func_decl Z3_API Z3_get_datatype_sort_recognizer (__in Z3_context c, __in Z3_sort t, unsigned idx)
Return idx'th recognizer.
Z3_func_decl Z3_API Z3_get_datatype_sort_constructor_accessor (__in Z3_context c, __in Z3_sort t, unsigned idx_c, unsigned idx_a)
Return idx_a'th accessor for the idx_c'th constructor.
unsigned Z3_API Z3_get_relation_arity (__in Z3_context c, __in Z3_sort s)
Return arity of relation.
Z3_sort Z3_API Z3_get_relation_column (__in Z3_context c, __in Z3_sort s, unsigned col)
Return sort at i'th column of relation sort.
Z3_ast Z3_API Z3_func_decl_to_ast (__in Z3_context c, __in Z3_func_decl f)
Convert a Z3_func_decl into Z3_ast. This is just type casting.
Z3_bool Z3_API Z3_is_eq_func_decl (__in Z3_context c, __in Z3_func_decl f1, Z3_func_decl f2)
compare terms.
unsigned Z3_API Z3_get_func_decl_id (__in Z3_context c, Z3_func_decl f)
Return a unique identifier for f.
Z3_symbol Z3_API Z3_get_decl_name (__in Z3_context c, __in Z3_func_decl d)
Return the constant declaration name as a symbol.
Z3_decl_kind Z3_API Z3_get_decl_kind (__in Z3_context c, __in Z3_func_decl d)
Return declaration kind corresponding to declaration.
unsigned Z3_API Z3_get_domain_size (__in Z3_context c, __in Z3_func_decl d)
Return the number of parameters of the given declaration.
unsigned Z3_API Z3_get_arity (__in Z3_context c, __in Z3_func_decl d)
Alias for Z3_get_domain_size.
Z3_sort Z3_API Z3_get_domain (__in Z3_context c, __in Z3_func_decl d, __in unsigned i)
Return the sort of the i-th parameter of the given function declaration.
Z3_sort Z3_API Z3_get_range (__in Z3_context c, __in Z3_func_decl d)
Return the range of the given declaration.
unsigned Z3_API Z3_get_decl_num_parameters (__in Z3_context c, __in Z3_func_decl d)
Return the number of parameters associated with a declaration.
Z3_parameter_kind Z3_API Z3_get_decl_parameter_kind (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the parameter type associated with a declaration.
int Z3_API Z3_get_decl_int_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the integer value associated with an integer parameter.
double Z3_API Z3_get_decl_double_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the double value associated with an double parameter.
Z3_symbol Z3_API Z3_get_decl_symbol_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the double value associated with an double parameter.
Z3_sort Z3_API Z3_get_decl_sort_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the sort value associated with a sort parameter.
Z3_ast Z3_API Z3_get_decl_ast_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the expresson value associated with an expression parameter.
Z3_func_decl Z3_API Z3_get_decl_func_decl_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the expresson value associated with an expression parameter.
Z3_string Z3_API Z3_get_decl_rational_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the rational value, as a string, associated with a rational parameter.
Z3_ast Z3_API Z3_app_to_ast (__in Z3_context c, __in Z3_app a)
Convert a Z3_app into Z3_ast. This is just type casting.
Z3_func_decl Z3_API Z3_get_app_decl (__in Z3_context c, __in Z3_app a)
Return the declaration of a constant or function application.
unsigned Z3_API Z3_get_app_num_args (__in Z3_context c, __in Z3_app a)
Return the number of argument of an application. If t is an constant, then the number of arguments is 0.
Z3_ast Z3_API Z3_get_app_arg (__in Z3_context c, __in Z3_app a, __in unsigned i)
Return the i-th argument of the given application.
Z3_bool Z3_API Z3_is_eq_ast (__in Z3_context c, __in Z3_ast t1, Z3_ast t2)
compare terms.
unsigned Z3_API Z3_get_ast_id (__in Z3_context c, Z3_ast t)
Return a unique identifier for t.
unsigned Z3_API Z3_get_ast_hash (__in Z3_context c, __in Z3_ast a)
Return a hash code for the given AST.
Z3_sort Z3_API Z3_get_sort (__in Z3_context c, __in Z3_ast a)
Return the sort of an AST node.
Z3_bool Z3_API Z3_is_well_sorted (__in Z3_context c, __in Z3_ast t)
Return true if the given expression t is well sorted.
Z3_lbool Z3_API Z3_get_bool_value (__in Z3_context c, __in Z3_ast a)
Return Z3_L_TRUE if a is true, Z3_L_FALSE if it is false, and Z3_L_UNDEF otherwise.
Z3_ast_kind Z3_API Z3_get_ast_kind (__in Z3_context c, __in Z3_ast a)
Return the kind of the given AST.
Z3_bool Z3_API Z3_is_app (__in Z3_context c, __in Z3_ast a)
Z3_bool Z3_API Z3_is_numeral_ast (__in Z3_context c, __in Z3_ast a)
Z3_bool Z3_API Z3_is_algebraic_number (__in Z3_context c, __in Z3_ast a)
Return true if the give AST is a real algebraic number.
Z3_app Z3_API Z3_to_app (__in Z3_context c, __in Z3_ast a)
Convert an ast into an APP_AST. This is just type casting.
Z3_func_decl Z3_API Z3_to_func_decl (__in Z3_context c, __in Z3_ast a)
Convert an AST into a FUNC_DECL_AST. This is just type casting.
Z3_string Z3_API Z3_get_numeral_string (__in Z3_context c, __in Z3_ast a)
Return numeral value, as a string of a numeric constant term.
Z3_string Z3_API Z3_get_numeral_decimal_string (__in Z3_context c, __in Z3_ast a, __in unsigned precision)
Return numeral as a string in decimal notation. The result has at most precision decimal places.
Z3_ast Z3_API Z3_get_numerator (__in Z3_context c, __in Z3_ast a)
Return the numerator (as a numeral AST) of a numeral AST of sort Real.
Z3_ast Z3_API Z3_get_denominator (__in Z3_context c, __in Z3_ast a)
Return the denominator (as a numeral AST) of a numeral AST of sort Real.
Z3_bool Z3_API Z3_get_numeral_small (__in Z3_context c, __in Z3_ast a, __out __int64 *num, __out __int64 *den)
Return numeral value, as a pair of 64 bit numbers if the representation fits.
Z3_bool Z3_API Z3_get_numeral_int (__in Z3_context c, __in Z3_ast v, __out int *i)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine int. Return Z3_TRUE if the call succeeded.
Z3_bool Z3_API Z3_get_numeral_uint (__in Z3_context c, __in Z3_ast v, __out unsigned *u)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine unsigned int. Return Z3_TRUE if the call succeeded.
Z3_bool Z3_API Z3_get_numeral_uint64 (__in Z3_context c, __in Z3_ast v, __out unsigned __int64 *u)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine unsigned __int64 int. Return Z3_TRUE if the call succeeded.
Z3_bool Z3_API Z3_get_numeral_int64 (__in Z3_context c, __in Z3_ast v, __out __int64 *i)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine __int64 int. Return Z3_TRUE if the call succeeded.
Z3_bool Z3_API Z3_get_numeral_rational_int64 (__in Z3_context c, __in Z3_ast v, __out __int64 *num, __out __int64 *den)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit as a rational number as machine __int64 int. Return Z3_TRUE if the call succeeded.
Z3_ast Z3_API Z3_get_algebraic_number_lower (__in Z3_context c, __in Z3_ast a, __in unsigned precision)
Return a lower bound for the given real algebraic number. The interval isolating the number is smaller than 1/10^precision. The result is a numeral AST of sort Real.
Z3_ast Z3_API Z3_get_algebraic_number_upper (Z3_context c, Z3_ast a, unsigned precision)
Return a upper bound for the given real algebraic number. The interval isolating the number is smaller than 1/10^precision. The result is a numeral AST of sort Real.
Z3_ast Z3_API Z3_pattern_to_ast (__in Z3_context c, __in Z3_pattern p)
Convert a Z3_pattern into Z3_ast. This is just type casting.
unsigned Z3_API Z3_get_pattern_num_terms (__in Z3_context c, __in Z3_pattern p)
Return number of terms in pattern.
Z3_ast Z3_API Z3_get_pattern (__in Z3_context c, __in Z3_pattern p, __in unsigned idx)
Return i'th ast in pattern.
unsigned Z3_API Z3_get_index_value (__in Z3_context c, __in Z3_ast a)
Return index of de-Brujin bound variable.
Z3_bool Z3_API Z3_is_quantifier_forall (__in Z3_context c, __in Z3_ast a)
Determine if quantifier is universal.
unsigned Z3_API Z3_get_quantifier_weight (__in Z3_context c, __in Z3_ast a)
Obtain weight of quantifier.
unsigned Z3_API Z3_get_quantifier_num_patterns (__in Z3_context c, __in Z3_ast a)
Return number of patterns used in quantifier.
Z3_pattern Z3_API Z3_get_quantifier_pattern_ast (__in Z3_context c, __in Z3_ast a, unsigned i)
Return i'th pattern.
unsigned Z3_API Z3_get_quantifier_num_no_patterns (__in Z3_context c, __in Z3_ast a)
Return number of no_patterns used in quantifier.
Z3_ast Z3_API Z3_get_quantifier_no_pattern_ast (__in Z3_context c, __in Z3_ast a, unsigned i)
Return i'th no_pattern.
Z3_symbol Z3_API Z3_get_quantifier_bound_name (__in Z3_context c, __in Z3_ast a, unsigned i)
Return symbol of the i'th bound variable.
Z3_sort Z3_API Z3_get_quantifier_bound_sort (__in Z3_context c, __in Z3_ast a, unsigned i)
Return sort of the i'th bound variable.
Z3_ast Z3_API Z3_get_quantifier_body (__in Z3_context c, __in Z3_ast a)
Return body of quantifier.
unsigned Z3_API Z3_get_quantifier_num_bound (__in Z3_context c, __in Z3_ast a)
Return number of bound variables of quantifier.
Z3_ast Z3_API Z3_simplify (__in Z3_context c, __in Z3_ast a)
Interface to simplifier.
Z3_ast Z3_API Z3_simplify_ex (__in Z3_context c, __in Z3_ast a, __in Z3_params p)
Interface to simplifier.
Z3_string Z3_API Z3_simplify_get_help (__in Z3_context c)
Return a string describing all available parameters.
Modifiers
Z3_ast Z3_API Z3_update_term (__in Z3_context c, __in Z3_ast a, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Update the arguments of term a using the arguments args. The number of arguments num_args should coincide with the number of arguments to a. If a is a quantifier, then num_args has to be 1.
Z3_ast Z3_API Z3_substitute (__in Z3_context c, __in Z3_ast a, __in unsigned num_exprs, __in_ecount(num_exprs) Z3_ast const from[], __in_ecount(num_exprs) Z3_ast const to[])
Substitute every occurrence of from[i] in a with to[i], for i smaller than num_exprs. The result is the new AST. The arrays from and to must have size num_exprs. For every i smaller than num_exprs, we must have that sort of from[i] must be equal to sort of to[i].
Z3_ast Z3_API Z3_substitute_vars (__in Z3_context c, __in Z3_ast a, __in unsigned num_exprs, __in_ecount(num_exprs) Z3_ast const to[])
Substitute the free variables in a with the expressions in to. For every i smaller than num_exprs, the variable with de-Bruijn index i is replaced with term to[i].
Z3_ast Z3_API Z3_translate (__in Z3_context source, __in Z3_ast a, __in Z3_context target)
Translate/Copy the AST a from context source to context target. AST a must have been created using context source.
Models
void Z3_API Z3_model_inc_ref (__in Z3_context c, __in Z3_model m)
Increment the reference counter of the given model.
void Z3_API Z3_model_dec_ref (__in Z3_context c, __in Z3_model m)
Decrement the reference counter of the given model.
Z3_bool Z3_API Z3_model_eval (__in Z3_context c, __in Z3_model m, __in Z3_ast t, __in Z3_bool model_completion, __out Z3_ast *v)
Evaluate the AST node t in the given model. Return Z3_TRUE if succeeded, and store the result in v.
Z3_ast Z3_API Z3_model_get_const_interp (__in Z3_context c, __in Z3_model m, __in Z3_func_decl a)
Return the interpretation (i.e., assignment) of constant a in the model m. Return NULL, if the model does not assign an interpretation for a. That should be interpreted as: the value of a does not matter.
Z3_func_interp Z3_API Z3_model_get_func_interp (__in Z3_context c, __in Z3_model m, __in Z3_func_decl f)
Return the interpretation of the function f in the model m. Return NULL, if the model does not assign an interpretation for f. That should be interpreted as: the f does not matter.
unsigned Z3_API Z3_model_get_num_consts (__in Z3_context c, __in Z3_model m)
Return the number of constants assigned by the given model.
Z3_func_decl Z3_API Z3_model_get_const_decl (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the i-th constant in the given model.
unsigned Z3_API Z3_model_get_num_funcs (__in Z3_context c, __in Z3_model m)
Return the number of function interpretations in the given model.
Z3_func_decl Z3_API Z3_model_get_func_decl (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the declaration of the i-th function in the given model.
unsigned Z3_API Z3_model_get_num_sorts (__in Z3_context c, __in Z3_model m)
Return the number of uninterpreted sorts that m assigs an interpretation to.
Z3_sort Z3_API Z3_model_get_sort (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return a uninterpreted sort that m assigns an interpretation.
Z3_ast_vector Z3_API Z3_model_get_sort_universe (__in Z3_context c, __in Z3_model m, __in Z3_sort s)
Return the finite set of distinct values that represent the interpretation for sort s.
Z3_bool Z3_API Z3_is_as_array (__in Z3_context c, __in Z3_ast a)
The (_ as-array f) AST node is a construct for assigning interpretations for arrays in Z3. It is the array such that forall indices i we have that (select (_ as-array f) i) is equal to (f i). This procedure returns Z3_TRUE if the a is an as-array AST node.
Z3_func_decl Z3_API Z3_get_as_array_func_decl (__in Z3_context c, __in Z3_ast a)
Return the function declaration f associated with a (_ as_array f) node.
void Z3_API Z3_func_interp_inc_ref (__in Z3_context c, __in Z3_func_interp f)
Increment the reference counter of the given Z3_func_interp object.
void Z3_API Z3_func_interp_dec_ref (__in Z3_context c, __in Z3_func_interp f)
Decrement the reference counter of the given Z3_func_interp object.
unsigned Z3_API Z3_func_interp_get_num_entries (__in Z3_context c, __in Z3_func_interp f)
Return the number of entries in the given function interpretation.
Z3_func_entry Z3_API Z3_func_interp_get_entry (__in Z3_context c, __in Z3_func_interp f, unsigned i)
Return a "point" of the given function intepretation. It represents the value of f in a particular point.
Z3_ast Z3_API Z3_func_interp_get_else (__in Z3_context c, __in Z3_func_interp f)
Return the 'else' value of the given function interpretation.
unsigned Z3_API Z3_func_interp_get_arity (__in Z3_context c, __in Z3_func_interp f)
Return the arity (number of arguments) of the given function interpretation.
void Z3_API Z3_func_entry_inc_ref (__in Z3_context c, __in Z3_func_entry e)
Increment the reference counter of the given Z3_func_entry object.
void Z3_API Z3_func_entry_dec_ref (__in Z3_context c, __in Z3_func_entry e)
Decrement the reference counter of the given Z3_func_entry object.
Z3_ast Z3_API Z3_func_entry_get_value (__in Z3_context c, __in Z3_func_entry e)
Return the value of this point.
unsigned Z3_API Z3_func_entry_get_num_args (__in Z3_context c, __in Z3_func_entry e)
Return the number of arguments in a Z3_func_entry object.
Z3_ast Z3_API Z3_func_entry_get_arg (__in Z3_context c, __in Z3_func_entry e, __in unsigned i)
Return an argument of a Z3_func_entry object.
Interaction logging.
Z3_bool Z3_API Z3_open_log (__in Z3_string filename)
Log interaction to a file.
void Z3_API Z3_append_log (__in Z3_string string)
Append user-defined string to interaction log.
void Z3_API Z3_close_log ()
Close interaction log.
void Z3_API Z3_toggle_warning_messages (__in Z3_bool enabled)
Enable/disable printing warning messages to the console.
String conversion
void Z3_API Z3_set_ast_print_mode (__in Z3_context c, __in Z3_ast_print_mode mode)
Select mode for the format used for pretty-printing AST nodes.
Z3_string Z3_API Z3_ast_to_string (__in Z3_context c, __in Z3_ast a)
Convert the given AST node into a string.
Z3_string Z3_API Z3_pattern_to_string (__in Z3_context c, __in Z3_pattern p)
Z3_string Z3_API Z3_sort_to_string (__in Z3_context c, __in Z3_sort s)
Z3_string Z3_API Z3_func_decl_to_string (__in Z3_context c, __in Z3_func_decl d)
Z3_string Z3_API Z3_model_to_string (__in Z3_context c, __in Z3_model m)
Convert the given model into a string.
Z3_string Z3_API Z3_benchmark_to_smtlib_string (__in Z3_context c, __in Z3_string name, __in Z3_string logic, __in Z3_string status, __in Z3_string attributes, __in unsigned num_assumptions, __in_ecount(num_assumptions) Z3_ast const assumptions[], __in Z3_ast formula)
Convert the given benchmark into SMT-LIB formatted string.
Parser interface
Z3_ast Z3_API Z3_parse_smtlib2_string (__in Z3_context c, __in Z3_string str, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Parse the given string using the SMT-LIB2 parser.
Z3_ast Z3_API Z3_parse_smtlib2_file (__in Z3_context c, __in Z3_string file_name, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Similar to Z3_parse_smtlib2_string, but reads the benchmark from a file.
void Z3_API Z3_parse_smtlib_string (__in Z3_context c, __in Z3_string str, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Parse the given string using the SMT-LIB parser.
void Z3_API Z3_parse_smtlib_file (__in Z3_context c, __in Z3_string file_name, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Similar to Z3_parse_smtlib_string, but reads the benchmark from a file.
unsigned Z3_API Z3_get_smtlib_num_formulas (__in Z3_context c)
Return the number of SMTLIB formulas parsed by the last call to Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Z3_ast Z3_API Z3_get_smtlib_formula (__in Z3_context c, __in unsigned i)
Return the i-th formula parsed by the last call to Z3_parse_smtlib_string or Z3_parse_smtlib_file.
unsigned Z3_API Z3_get_smtlib_num_assumptions (__in Z3_context c)
Return the number of SMTLIB assumptions parsed by Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Z3_ast Z3_API Z3_get_smtlib_assumption (__in Z3_context c, __in unsigned i)
Return the i-th assumption parsed by the last call to Z3_parse_smtlib_string or Z3_parse_smtlib_file.
unsigned Z3_API Z3_get_smtlib_num_decls (__in Z3_context c)
Return the number of declarations parsed by Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Z3_func_decl Z3_API Z3_get_smtlib_decl (__in Z3_context c, __in unsigned i)
Return the i-th declaration parsed by the last call to Z3_parse_smtlib_string or Z3_parse_smtlib_file.
unsigned Z3_API Z3_get_smtlib_num_sorts (__in Z3_context c)
Return the number of sorts parsed by Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Z3_sort Z3_API Z3_get_smtlib_sort (__in Z3_context c, __in unsigned i)
Return the i-th sort parsed by the last call to Z3_parse_smtlib_string or Z3_parse_smtlib_file.
BEGIN_MLAPI_EXCLUDE Z3_string
Z3_API Z3_get_smtlib_error (__in Z3_context c)
Retrieve that last error message information generated from parsing.
END_MLAPI_EXCLUDE Z3_ast Z3_API Z3_parse_z3_string (__in Z3_context c, __in Z3_string str)
Parse the given string using the Z3 native parser.
Z3_ast Z3_API Z3_parse_z3_file (__in Z3_context c, __in Z3_string file_name)
Similar to Z3_parse_z3_string, but reads the benchmark from a file.
Error Handling
Z3_error_code Z3_API Z3_get_error_code (__in Z3_context c)
Return the error code for the last API call.
void Z3_API Z3_set_error_handler (__in Z3_context c, __in Z3_error_handler h)
Register a Z3 error handler.
void Z3_API Z3_set_error (__in Z3_context c, __in Z3_error_code e)
Set an error.
Z3_string Z3_API Z3_get_error_msg (__in Z3_error_code err)
Return a string describing the given error code.
BEGIN_MLAPI_EXCLUDE Z3_string
Z3_API Z3_get_error_msg_ex (__in Z3_context c, __in Z3_error_code err)
Return a string describing the given error code.
Miscellaneous
void Z3_API Z3_get_version (__out unsigned *major, __out unsigned *minor, __out unsigned *build_number, __out unsigned *revision_number)
Return Z3 version number information.
void Z3_API Z3_reset_memory (void)
Reset all allocated resources.
AST vectors
Z3_ast_vector Z3_API Z3_mk_ast_vector (__in Z3_context c)
Return an empty AST vector.
void Z3_API Z3_ast_vector_inc_ref (__in Z3_context c, __in Z3_ast_vector v)
Increment the reference counter of the given AST vector.
void Z3_API Z3_ast_vector_dec_ref (__in Z3_context c, __in Z3_ast_vector v)
Decrement the reference counter of the given AST vector.
unsigned Z3_API Z3_ast_vector_size (__in Z3_context c, __in Z3_ast_vector v)
Return the size of the given AST vector.
Z3_ast Z3_API Z3_ast_vector_get (__in Z3_context c, __in Z3_ast_vector v, __in unsigned i)
Return the AST at position i in the AST vector v.
void Z3_API Z3_ast_vector_set (__in Z3_context c, __in Z3_ast_vector v, __in unsigned i, __in Z3_ast a)
Update position i of the AST vector v with the AST a.
void Z3_API Z3_ast_vector_resize (__in Z3_context c, __in Z3_ast_vector v, __in unsigned n)
Resize the AST vector v.
void Z3_API Z3_ast_vector_push (__in Z3_context c, __in Z3_ast_vector v, __in Z3_ast a)
Add the AST a in the end of the AST vector v. The size of v is increased by one.
Z3_ast_vector Z3_API Z3_ast_vector_translate (__in Z3_context s, __in Z3_ast_vector v, __in Z3_context t)
Translate the AST vector v from context s into an AST vector in context t.
Z3_string Z3_API Z3_ast_vector_to_string (__in Z3_context c, __in Z3_ast_vector v)
Convert AST vector into a string.
AST maps
Z3_ast_map Z3_API Z3_mk_ast_map (__in Z3_context c)
Return an empty mapping from AST to AST.
void Z3_API Z3_ast_map_inc_ref (__in Z3_context c, __in Z3_ast_map m)
Increment the reference counter of the given AST map.
void Z3_API Z3_ast_map_dec_ref (__in Z3_context c, __in Z3_ast_map m)
Decrement the reference counter of the given AST map.
Z3_bool Z3_API Z3_ast_map_contains (__in Z3_context c, __in Z3_ast_map m, __in Z3_ast k)
Return true if the map m contains the AST key k.
Z3_ast Z3_API Z3_ast_map_find (__in Z3_context c, __in Z3_ast_map m, __in Z3_ast k)
Return the value associated with the key k.
void Z3_API Z3_ast_map_insert (__in Z3_context c, __in Z3_ast_map m, __in Z3_ast k, __in Z3_ast v)
Store/Replace a new key, value pair in the given map.
void Z3_API Z3_ast_map_erase (__in Z3_context c, __in Z3_ast_map m, __in Z3_ast k)
Erase a key from the map.
void Z3_API Z3_ast_map_reset (__in Z3_context c, __in Z3_ast_map m)
Remove all keys from the given map.
unsigned Z3_API Z3_ast_map_size (__in Z3_context c, __in Z3_ast_map m)
Return the size of the given map.
Z3_ast_vector Z3_API Z3_ast_map_keys (__in Z3_context c, __in Z3_ast_map m)
Return the keys stored in the given map.
Z3_string Z3_API Z3_ast_map_to_string (__in Z3_context c, __in Z3_ast_map m)
Convert the given map into a string.
Goals
Z3_goal Z3_API Z3_mk_goal (__in Z3_context c, __in Z3_bool models, __in Z3_bool unsat_cores, __in Z3_bool proofs)
Create a goal (aka problem). A goal is essentially a set of formulas, that can be solved and/or transformed using tactics and solvers.
void Z3_API Z3_goal_inc_ref (__in Z3_context c, __in Z3_goal g)
Increment the reference counter of the given goal.
void Z3_API Z3_goal_dec_ref (__in Z3_context c, __in Z3_goal g)
Decrement the reference counter of the given goal.
Z3_goal_prec Z3_API Z3_goal_precision (__in Z3_context c, __in Z3_goal g)
Return the "precision" of the given goal. Goals can be transformed using over and under approximations. A under approximation is applied when the objective is to find a model for a given goal. An over approximation is applied when the objective is to find a proof for a given goal.
void Z3_API Z3_goal_assert (__in Z3_context c, __in Z3_goal g, __in Z3_ast a)
Add a new formula a to the given goal.
Z3_bool Z3_API Z3_goal_inconsistent (__in Z3_context c, __in Z3_goal g)
Return true if the given goal contains the formula false.
unsigned Z3_API Z3_goal_depth (__in Z3_context c, __in Z3_goal g)
Return the depth of the given goal. It tracks how many transformations were applied to it.
void Z3_API Z3_goal_reset (__in Z3_context c, __in Z3_goal g)
Erase all formulas from the given goal.
unsigned Z3_API Z3_goal_size (__in Z3_context c, __in Z3_goal g)
Return the number of formulas in the given goal.
Z3_ast Z3_API Z3_goal_formula (__in Z3_context c, __in Z3_goal g, __in unsigned idx)
Return a formula from the given goal.
unsigned Z3_API Z3_goal_num_exprs (__in Z3_context c, __in Z3_goal g)
Return the number of formulas, subformulas and terms in the given goal.
Z3_bool Z3_API Z3_goal_is_decided_sat (__in Z3_context c, __in Z3_goal g)
Return true if the goal is empty, and it is precise or the product of a under approximation.
Z3_bool Z3_API Z3_goal_is_decided_unsat (__in Z3_context c, __in Z3_goal g)
Return true if the goal contains false, and it is precise or the product of an over approximation.
Z3_goal Z3_API Z3_goal_translate (__in Z3_context source, __in Z3_goal g, __in Z3_context target)
Copy a goal g from the context source to a the context target.
Z3_string Z3_API Z3_goal_to_string (__in Z3_context c, __in Z3_goal g)
Convert a goal into a string.
Tactics and Probes
Z3_tactic Z3_API Z3_mk_tactic (__in Z3_context c, __in Z3_string name)
Return a tactic associated with the given name. The complete list of tactics may be obtained using the procedures Z3_get_num_tactics and Z3_get_tactic_name. It may also be obtained using the command (help-tactics) in the SMT 2.0 front-end.
void Z3_API Z3_tactic_inc_ref (__in Z3_context c, __in Z3_tactic t)
Increment the reference counter of the given tactic.
void Z3_API Z3_tactic_dec_ref (__in Z3_context c, __in Z3_tactic g)
Decrement the reference counter of the given tactic.
Z3_probe Z3_API Z3_mk_probe (__in Z3_context c, __in Z3_string name)
Return a probe associated with the given name. The complete list of probes may be obtained using the procedures Z3_get_num_probes and Z3_get_probe_name. It may also be obtained using the command (help-tactics) in the SMT 2.0 front-end.
void Z3_API Z3_probe_inc_ref (__in Z3_context c, __in Z3_probe p)
Increment the reference counter of the given probe.
void Z3_API Z3_probe_dec_ref (__in Z3_context c, __in Z3_probe p)
Decrement the reference counter of the given probe.
Z3_tactic Z3_API Z3_tactic_and_then (__in Z3_context c, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that applies t1 to a given goal and t2 to every subgoal produced by t1.
Z3_tactic Z3_API Z3_tactic_or_else (__in Z3_context c, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that first applies t1 to a given goal, if it fails then returns the result of t2 applied to the given goal.
Z3_tactic Z3_API Z3_tactic_par_or (__in Z3_context c, __in unsigned num, __in_ecount(num) Z3_tactic const ts[])
Return a tactic that applies the given tactics in parallel.
Z3_tactic Z3_API Z3_tactic_par_and_then (__in Z3_context c, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that applies t1 to a given goal and then t2 to every subgoal produced by t1. The subgoals are processed in parallel.
Z3_tactic Z3_API Z3_tactic_try_for (__in Z3_context c, __in Z3_tactic t, __in unsigned ms)
Return a tactic that applies t to a given goal for ms milliseconds. If t does not terminate in ms milliseconds, then it fails.
Z3_tactic Z3_API Z3_tactic_when (__in Z3_context c, __in Z3_probe p, __in Z3_tactic t)
Return a tactic that applies t to a given goal is the probe p evaluates to true. If p evaluates to false, then the new tactic behaves like the skip tactic.
Z3_tactic Z3_API Z3_tactic_cond (__in Z3_context c, __in Z3_probe p, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that applies t1 to a given goal if the probe p evaluates to true, and t2 if p evaluates to false.
Z3_tactic Z3_API Z3_tactic_repeat (__in Z3_context c, __in Z3_tactic t, unsigned max)
Return a tactic that keeps applying t until the goal is not modified anymore or the maximum number of iterations max is reached.
Z3_tactic Z3_API Z3_tactic_skip (__in Z3_context c)
Return a tactic that just return the given goal.
Z3_tactic Z3_API Z3_tactic_fail (__in Z3_context c)
Return a tactic that always fails.
Z3_tactic Z3_API Z3_tactic_fail_if (__in Z3_context c, __in Z3_probe p)
Return a tactic that fails if the probe p evaluates to false.
Z3_tactic Z3_API Z3_tactic_fail_if_not_decided (__in Z3_context c)
Return a tactic that fails if the goal is not trivially satisfiable (i.e., empty) or trivially unsatisfiable (i.e., contains false).
Z3_tactic Z3_API Z3_tactic_using_params (__in Z3_context c, __in Z3_tactic t, __in Z3_params p)
Return a tactic that applies t using the given set of parameters.
Z3_probe Z3_API Z3_probe_const (__in Z3_context x, __in double val)
Return a probe that always evaluates to val.
Z3_probe Z3_API Z3_probe_lt (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than the value returned by p2.
Z3_probe Z3_API Z3_probe_gt (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than the value returned by p2.
Z3_probe Z3_API Z3_probe_le (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than or equal to the value returned by p2.
Z3_probe Z3_API Z3_probe_ge (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than or equal to the value returned by p2.
Z3_probe Z3_API Z3_probe_eq (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is equal to the value returned by p2.
Z3_probe Z3_API Z3_probe_and (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when p1 and p2 evaluates to true.
Z3_probe Z3_API Z3_probe_or (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when p1 or p2 evaluates to true.
Z3_probe Z3_API Z3_probe_not (__in Z3_context x, __in Z3_probe p)
Return a probe that evaluates to "true" when p does not evaluate to true.
unsigned Z3_API Z3_get_num_tactics (__in Z3_context c)
Return the number of builtin tactics available in Z3.
Z3_string Z3_API Z3_get_tactic_name (__in Z3_context c, unsigned i)
Return the name of the idx tactic.
unsigned Z3_API Z3_get_num_probes (__in Z3_context c)
Return the number of builtin probes available in Z3.
Z3_string Z3_API Z3_get_probe_name (__in Z3_context c, unsigned i)
Return the name of the i probe.
Z3_string Z3_API Z3_tactic_get_help (__in Z3_context c, __in Z3_tactic t)
Return a string containing a description of parameters accepted by the given tactic.
Z3_string Z3_API Z3_tactic_get_descr (__in Z3_context c, __in Z3_string name)
Return a string containing a description of the tactic with the given name.
Z3_string Z3_API Z3_probe_get_descr (__in Z3_context c, __in Z3_string name)
Return a string containing a description of the probe with the given name.
double Z3_API Z3_probe_apply (__in Z3_context c, __in Z3_probe p, __in Z3_goal g)
Execute the probe over the goal. The probe always produce a double value. "Boolean" probes return 0.0 for false, and a value different from 0.0 for true.
Z3_apply_result Z3_API Z3_tactic_apply (__in Z3_context c, __in Z3_tactic t, __in Z3_goal g)
Apply tactic t to the goal g.
Z3_apply_result Z3_API Z3_tactic_apply_ex (Z3_context c, Z3_tactic t, Z3_goal g, Z3_params p)
Apply tactic t to the goal g using the parameter set p.
void Z3_API Z3_apply_result_inc_ref (__in Z3_context c, __in Z3_apply_result r)
Increment the reference counter of the given Z3_apply_result object.
void Z3_API Z3_apply_result_dec_ref (__in Z3_context c, __in Z3_apply_result r)
Decrement the reference counter of the given Z3_apply_result object.
Z3_string Z3_API Z3_apply_result_to_string (__in Z3_context c, __in Z3_apply_result r)
Convert the Z3_apply_result object returned by Z3_tactic_apply into a string.
unsigned Z3_API Z3_apply_result_get_num_subgoals (__in Z3_context c, __in Z3_apply_result r)
Return the number of subgoals in the Z3_apply_result object returned by Z3_tactic_apply.
Z3_goal Z3_API Z3_apply_result_get_subgoal (__in Z3_context c, __in Z3_apply_result r, __in unsigned i)
Return one of the subgoals in the Z3_apply_result object returned by Z3_tactic_apply.
Z3_model Z3_API Z3_apply_result_convert_model (__in Z3_context c, __in Z3_apply_result r, __in unsigned i, __in Z3_model m)
Convert a model for the subgoal Z3_apply_result_get_subgoal(c, r, i) into a model for the original goal g. Where g is the goal used to create r using Z3_tactic_apply(c, t, g).
Solvers
Z3_solver Z3_API Z3_mk_solver (__in Z3_context c)
Create a new (incremental) solver. This solver also uses a set of builtin tactics for handling the first check-sat command, and check-sat commands that take more than a given number of milliseconds to be solved.
Z3_solver Z3_API Z3_mk_simple_solver (__in Z3_context c)
Create a new (incremental) solver.
Z3_solver Z3_API Z3_mk_solver_for_logic (__in Z3_context c, __in Z3_symbol logic)
Create a new solver customized for the given logic. It behaves like Z3_mk_solver if the logic is unknown or unsupported.
Z3_solver Z3_API Z3_mk_solver_from_tactic (__in Z3_context c, __in Z3_tactic t)
Create a new solver that is implemented using the given tactic. The solver supports the commands Z3_solver_push and Z3_solver_pop, but it will always solve each Z3_solver_check from scratch.
Z3_string Z3_API Z3_solver_get_help (__in Z3_context c, __in Z3_solver s)
Return a string describing all solver available parameters.
void Z3_API Z3_solver_set_params (__in Z3_context c, __in Z3_solver s, __in Z3_params p)
Set the given solver using the given parameters.
void Z3_API Z3_solver_inc_ref (__in Z3_context c, __in Z3_solver s)
Increment the reference counter of the given solver.
void Z3_API Z3_solver_dec_ref (__in Z3_context c, __in Z3_solver s)
Decrement the reference counter of the given solver.
void Z3_API Z3_solver_push (__in Z3_context c, __in Z3_solver s)
Create a backtracking point.
void Z3_API Z3_solver_pop (__in Z3_context c, __in Z3_solver s, unsigned n)
Backtrack n backtracking points.
void Z3_API Z3_solver_reset (__in Z3_context c, __in Z3_solver s)
Remove all assertions from the solver.
unsigned Z3_API Z3_solver_get_num_scopes (__in Z3_context c, __in Z3_solver s)
Return the number of backtracking points.
void Z3_API Z3_solver_assert (__in Z3_context c, __in Z3_solver s, __in Z3_ast a)
Assert a constraint into the solver.
Z3_ast_vector Z3_API Z3_solver_get_assertions (__in Z3_context c, __in Z3_solver s)
Return the set of asserted formulas as a goal object.
Z3_lbool Z3_API Z3_solver_check (__in Z3_context c, __in Z3_solver s)
Check whether the assertions in a given solver are consistent or not.
Z3_lbool Z3_API Z3_solver_check_assumptions (__in Z3_context c, __in Z3_solver s, __in unsigned num_assumptions, __in_ecount(num_assumptions) Z3_ast const assumptions[])
Check whether the assertions in the given solver and optional assumptions are consistent or not.
Z3_model Z3_API Z3_solver_get_model (__in Z3_context c, __in Z3_solver s)
Retrieve the model for the last Z3_solver_check or Z3_solver_check_assumptions.
Z3_ast Z3_API Z3_solver_get_proof (__in Z3_context c, __in Z3_solver s)
Retrieve the proof for the last Z3_solver_check or Z3_solver_check_assumptions.
Z3_ast_vector Z3_API Z3_solver_get_unsat_core (__in Z3_context c, __in Z3_solver s)
Retrieve the unsat core for the last Z3_solver_check_assumptions The unsat core is a subset of the assumptions a.
Z3_string Z3_API Z3_solver_get_reason_unknown (__in Z3_context c, __in Z3_solver s)
Return a brief justification for an "unknown" result (i.e., Z3_L_UNDEF) for the commands Z3_solver_check and Z3_solver_check_assumptions.
Z3_stats Z3_API Z3_solver_get_statistics (__in Z3_context c, __in Z3_solver s)
Return statistics for the given solver.
Z3_string Z3_API Z3_solver_to_string (__in Z3_context c, __in Z3_solver s)
Convert a solver into a string.
Statistics
Z3_string Z3_API Z3_stats_to_string (__in Z3_context c, __in Z3_stats s)
Convert a statistics into a string.
void Z3_API Z3_stats_inc_ref (__in Z3_context c, __in Z3_stats s)
Increment the reference counter of the given statistics object.
void Z3_API Z3_stats_dec_ref (__in Z3_context c, __in Z3_stats s)
Decrement the reference counter of the given statistics object.
unsigned Z3_API Z3_stats_size (__in Z3_context c, __in Z3_stats s)
Return the number of statistical data in s.
Z3_string Z3_API Z3_stats_get_key (__in Z3_context c, __in Z3_stats s, __in unsigned idx)
Return the key (a string) for a particular statistical data.
Z3_bool Z3_API Z3_stats_is_uint (__in Z3_context c, __in Z3_stats s, __in unsigned idx)
Return Z3_TRUE if the given statistical data is a unsigned integer.
Z3_bool Z3_API Z3_stats_is_double (__in Z3_context c, __in Z3_stats s, __in unsigned idx)
Return Z3_TRUE if the given statistical data is a double.
unsigned Z3_API Z3_stats_get_uint_value (__in Z3_context c, __in Z3_stats s, __in unsigned idx)
Return the unsigned value of the given statistical data.
double Z3_API Z3_stats_get_double_value (__in Z3_context c, __in Z3_stats s, __in unsigned idx)
Return the double value of the given statistical data.
Deprecated Injective functions API
Z3_func_decl Z3_API Z3_mk_injective_function (__in Z3_context c, __in Z3_symbol s, unsigned domain_size, __in_ecount(domain_size) Z3_sort const domain[], __in Z3_sort range)
Create injective function declaration.
Deprecated Constraints API
Z3_bool Z3_API Z3_set_logic (__in Z3_context c, __in Z3_string logic)
Set the SMTLIB logic to be used in the given logical context. It is incorrect to invoke this function after invoking Z3_check, Z3_check_and_get_model, Z3_check_assumptions and Z3_push. Return Z3_TRUE if the logic was changed successfully, and Z3_FALSE otherwise.
void Z3_API Z3_push (__in Z3_context c)
Create a backtracking point.
void Z3_API Z3_pop (__in Z3_context c, __in unsigned num_scopes)
Backtrack.
unsigned Z3_API Z3_get_num_scopes (__in Z3_context c)
Retrieve the current scope level.
void Z3_API Z3_persist_ast (__in Z3_context c, __in Z3_ast a, __in unsigned num_scopes)
Persist AST through num_scopes pops. This function is only relevant if c was created using Z3_mk_context. If c was created using Z3_mk_context_rc, this function is a NOOP.
void Z3_API Z3_assert_cnstr (__in Z3_context c, __in Z3_ast a)
Assert a constraint into the logical context.
Z3_lbool Z3_API Z3_check_and_get_model (__in Z3_context c, __out Z3_model *m)
Check whether the given logical context is consistent or not.
Z3_lbool Z3_API Z3_check (__in Z3_context c)
Check whether the given logical context is consistent or not.
Z3_lbool Z3_API Z3_check_assumptions (__in Z3_context c, __in unsigned num_assumptions, __in_ecount(num_assumptions) Z3_ast const assumptions[], __out Z3_model *m, __out Z3_ast *proof, __inout unsigned *core_size, __inout_ecount(num_assumptions) Z3_ast core[])
Check whether the given logical context and optional assumptions is consistent or not.
Z3_lbool Z3_API Z3_get_implied_equalities (__in Z3_context c, __in unsigned num_terms, __in_ecount(num_terms) Z3_ast const terms[], __out_ecount(num_terms) unsigned class_ids[])
Retrieve congruence class representatives for terms.
void Z3_API Z3_del_model (__in Z3_context c, __in Z3_model m)
Delete a model object.
Deprecated Search control API
void Z3_API Z3_soft_check_cancel (__in Z3_context c)
Cancel an ongoing check.
Z3_search_failure Z3_API Z3_get_search_failure (__in Z3_context c)
Retrieve reason for search failure.
Deprecated Labels API
Z3_ast Z3_API Z3_mk_label (__in Z3_context c, __in Z3_symbol s, Z3_bool is_pos, Z3_ast f)
Create a labeled formula.
Z3_literals Z3_API Z3_get_relevant_labels (__in Z3_context c)
Retrieve the set of labels that were relevant in the context of the current satisfied context.
Z3_literals Z3_API Z3_get_relevant_literals (__in Z3_context c)
Retrieve the set of literals that satisfy the current context.
Z3_literals Z3_API Z3_get_guessed_literals (__in Z3_context c)
Retrieve the set of literals that whose assignment were guess, but not propagated during the search.
void Z3_API Z3_del_literals (__in Z3_context c, __in Z3_literals lbls)
Delete a labels context.
unsigned Z3_API Z3_get_num_literals (__in Z3_context c, __in Z3_literals lbls)
Retrieve the number of label symbols that were returned.
Z3_symbol Z3_API Z3_get_label_symbol (__in Z3_context c, __in Z3_literals lbls, __in unsigned idx)
Retrieve label symbol at idx.
Z3_ast Z3_API Z3_get_literal (__in Z3_context c, __in Z3_literals lbls, __in unsigned idx)
Retrieve literal expression at idx.
void Z3_API Z3_disable_literal (__in Z3_context c, __in Z3_literals lbls, __in unsigned idx)
Disable label.
void Z3_API Z3_block_literals (__in Z3_context c, __in Z3_literals lbls)
Block subsequent checks using the remaining enabled labels.
Deprecated Model API
unsigned Z3_API Z3_get_model_num_constants (__in Z3_context c, __in Z3_model m)
Return the number of constants assigned by the given model.
Z3_func_decl Z3_API Z3_get_model_constant (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the i-th constant in the given model.
unsigned Z3_API Z3_get_model_num_funcs (__in Z3_context c, __in Z3_model m)
Return the number of function interpretations in the given model.
Z3_func_decl Z3_API Z3_get_model_func_decl (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the declaration of the i-th function in the given model.
Z3_bool Z3_API Z3_eval_func_decl (__in Z3_context c, __in Z3_model m, __in Z3_func_decl decl, __out Z3_ast *v)
Return the value of the given constant or function in the given model.
Z3_bool Z3_API Z3_is_array_value (__in Z3_context c, __in Z3_model m, __in Z3_ast v, __out unsigned *num_entries)
Determine whether the term encodes an array value. A term encodes an array value if it is a nested sequence of applications of store on top of a constant array. The indices to the stores have to be values (for example, integer constants) so that equality between the indices can be evaluated. Array values are useful for representing interpretations for arrays.
void Z3_API Z3_get_array_value (__in Z3_context c, __in Z3_model m, __in Z3_ast v, __in unsigned num_entries, __inout_ecount(num_entries) Z3_ast indices[], __inout_ecount(num_entries) Z3_ast values[], __out Z3_ast *else_value)
An array values is represented as a dictionary plus a default (else) value. This function returns the array graph.
Z3_ast Z3_API Z3_get_model_func_else (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the 'else' value of the i-th function interpretation in the given model.
unsigned Z3_API Z3_get_model_func_num_entries (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the number of entries of the i-th function interpretation in the given model.
unsigned Z3_API Z3_get_model_func_entry_num_args (__in Z3_context c, __in Z3_model m, __in unsigned i, __in unsigned j)
Return the number of arguments of the j-th entry of the i-th function interpretation in the given model.
Z3_ast Z3_API Z3_get_model_func_entry_arg (__in Z3_context c, __in Z3_model m, __in unsigned i, __in unsigned j, __in unsigned k)
Return the k-th argument of the j-th entry of the i-th function interpretation in the given model.
Z3_ast Z3_API Z3_get_model_func_entry_value (__in Z3_context c, __in Z3_model m, __in unsigned i, __in unsigned j)
Return the return value of the j-th entry of the i-th function interpretation in the given model.
Z3_bool Z3_API Z3_eval (__in Z3_context c, __in Z3_model m, __in Z3_ast t, __out Z3_ast *v)
Evaluate the AST node t in the given model. Return Z3_TRUE if succeeded, and store the result in v.
Z3_bool Z3_API Z3_eval_decl (__in Z3_context c, __in Z3_model m, __in Z3_func_decl d, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[], __out Z3_ast *v)
Evaluate declaration given values.
Deprecated String conversion API
Z3_string Z3_API Z3_context_to_string (__in Z3_context c)
Convert the given logical context into a string.
Z3_string Z3_API Z3_statistics_to_string (__in Z3_context c)
Return runtime statistics as a string.
Z3_ast Z3_API Z3_get_context_assignment (__in Z3_context c)
Extract satisfying assignment from context as a conjunction.
Create configuration
void Z3_API Z3_set_param_value (__in Z3_config c, __in_z Z3_string param_id, __in_z Z3_string param_value)
Set a configuration parameter.
Create context
Z3_bool Z3_API Z3_set_logic (__in Z3_context c, __in_z Z3_string logic)
Set the SMTLIB logic to be used in the given logical context. It is incorrect to invoke this function after invoking Z3_check, Z3_check_and_get_model, Z3_check_assumptions and Z3_push. Return Z3_TRUE if the logic was changed successfully, and Z3_FALSE otherwise.
void Z3_API Z3_update_param_value (__in Z3_context c, __in_z Z3_string param_id, __in_z Z3_string param_value)
Update a mutable configuration parameter.
Z3_bool Z3_API Z3_get_param_value (__in Z3_context c, __in_z Z3_string param_id, __out_z Z3_string_ptr param_value)
Get a configuration parameter.
Symbols
Z3_symbol Z3_API Z3_mk_string_symbol (__in Z3_context c, __in_z Z3_string s)
Create a Z3 symbol using a C string.
Sorts
Z3_constructor Z3_API Z3_mk_constructor (__in Z3_context c, __in Z3_symbol name, __in Z3_symbol recognizer, __in unsigned num_fields, __in_ecount(num_fields) Z3_symbol const field_names[], __in_ecount(num_fields) Z3_sort const sorts[], __in_ecount(num_fields) unsigned sort_refs[])
Create a constructor.
Constants and Applications
Z3_func_decl Z3_API Z3_mk_fresh_func_decl (__in Z3_context c, __in_z Z3_string prefix, __in unsigned domain_size, __in_ecount(domain_size) Z3_sort const domain[], __in Z3_sort range)
Declare a fresh constant or function.
Z3_ast Z3_API Z3_mk_fresh_const (__in Z3_context c, __in_z Z3_string prefix, __in Z3_sort ty)
Declare and create a fresh constant.
Numerals
Z3_ast Z3_API Z3_mk_numeral (__in Z3_context c, __in_z Z3_string numeral, __in Z3_sort ty)
Create a numeral of a given sort.
Z3_ast Z3_API Z3_mk_real (__in Z3_context c, __in_z int num, __in_z int den)
Create a real from a fraction.
Interaction logging.
Z3_bool Z3_API Z3_open_log (__in_z Z3_string filename)
Log interaction to a file.
void Z3_API Z3_append_log (__in_z Z3_string string)
Append user-defined string to interaction log.
String conversion
Z3_string Z3_API Z3_benchmark_to_smtlib_string (__in Z3_context c, __in_z Z3_string name, __in_z Z3_string logic, __in_z Z3_string status, __in_z Z3_string attributes, __in unsigned num_assumptions, __in_ecount(num_assumptions) Z3_ast const assumptions[], __in Z3_ast formula)
Convert the given benchmark into SMT-LIB formatted string.
Parser interface
void Z3_API Z3_parse_smtlib_string (__in Z3_context c, __in_z Z3_string str, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Parse the given string using the SMT-LIB parser.
void Z3_API Z3_parse_smtlib_file (__in Z3_context c, __in_z Z3_string file_name, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Similar to Z3_parse_smtlib_string, but reads the benchmark from a file.
Z3_ast Z3_API Z3_parse_z3_string (__in Z3_context c, __in_z Z3_string str)
Parse the given string using the Z3 native parser.
Z3_ast Z3_API Z3_parse_z3_file (__in Z3_context c, __in_z Z3_string file_name)
Similar to Z3_parse_z3_string, but reads the benchmark from a file.
Z3_ast Z3_API Z3_parse_smtlib2_string (__in Z3_context c, __in_z Z3_string str, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Parse the given string using the SMT-LIB2 parser.
Z3_ast Z3_API Z3_parse_smtlib2_file (__in Z3_context c, __in_z Z3_string file_name, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Similar to Z3_parse_smtlib2_string, but reads the benchmark from a file.
Goals
void Z3_API Z3_goal_assert_ex (__in Z3_context c, __in Z3_goal g, __in Z3_ast a)
Similar to Z3_goal_assert, but the given formula is tracked during unsat core generation. Unsat core generation must have been enabled when the given goal was created.
Tactics and Probes
Z3_tactic Z3_API Z3_mk_tactic (__in Z3_context c, __in_z Z3_string name)
Return a tactic associated with the given name. The complete list of tactics may be obtained using the procedures Z3_get_num_tactics and Z3_get_tactic_name. It may also be obtained using the command (help-tactics) in the SMT 2.0 front-end.
Z3_probe Z3_API Z3_mk_probe (__in Z3_context c, __in_z Z3_string name)
Return a probe associated with the given name. The complete list of probes may be obtained using the procedures Z3_get_num_probes and Z3_get_probe_name. It may also be obtained using the command (help-tactics) in the SMT 2.0 front-end.
Z3_tactic Z3_API Z3_and_then_tactic (__in Z3_context c, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that applies t1 to a given goal and t2 to every subgoal produced by t1.
Z3_tactic Z3_API Z3_or_else_tactic (__in Z3_context c, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that first applies t1 to a given goal, if it fails then returns the result of t2 applied to the given goal.
Z3_tactic Z3_API Z3_try_for_tactic (__in Z3_context c, __in Z3_tactic t, __in unsigned ms)
Return a tactic that applies t to a given goal for ms milliseconds. If t does not terminate in ms milliseconds, then it fails.
Z3_tactic Z3_API Z3_when_tactic (__in Z3_context c, __in Z3_probe p, __in Z3_tactic t)
Return a tactic that applies t to a given goal is the probe p evaluates to true. If p evaluates to false, then the new tactic behaves like the skip tactic.
Z3_tactic Z3_API Z3_cond_tactic (__in Z3_context c, __in Z3_probe p, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that applies t1 to a given goal if the probe p evaluates to true, and t2 if p evaluates to false.
Z3_tactic Z3_API Z3_repeat_tactic (__in Z3_context c, __in Z3_tactic t, unsigned max)
Return a tactic that keeps applying t until the goal is not modified anymore or the maximum number of iterations max is reached.
Z3_tactic Z3_API Z3_skip_tactic (__in Z3_context c)
Return a tactic that just return the given goal.
Z3_tactic Z3_API Z3_fail_tactic (__in Z3_context c)
Return a tactic that always fails.
Z3_tactic Z3_API Z3_fail_if_tactic (__in Z3_context c, __in Z3_probe p)
Return a tactic that fails if the probe p evaluates to false.
Z3_tactic Z3_API Z3_fail_if_not_decided_tactic (__in Z3_context c)
Return a tactic that fails if the goal is not trivially satisfiable (i.e., empty) or trivially unsatisfiable (i.e., contains false).
Z3_tactic Z3_API Z3_using_params_tactic (__in Z3_context c, __in Z3_tactic t, __in Z3_params p)
Return a tactic that applies t using the given set of parameters.
Z3_tactic Z3_API Z3_echo_tactic (__in Z3_context c, __in_z Z3_string msg)
Return a tactic that just displays the given message in the standard output. This tactic should be used for debugging purposes only.
Z3_tactic Z3_API Z3_echo_probe (__in Z3_context c, __in Z3_probe val)
Return a tactic that just displays the value of the given probe in the standard output. This tactic should be used for debugging purposes only.
Z3_probe Z3_API Z3_const_probe (__in Z3_context x, __in double val)
Return a probe that always evaluates to val.
Z3_probe Z3_API Z3_lt_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than the value returned by p2.
Z3_probe Z3_API Z3_gt_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than the value returned by p2.
Z3_probe Z3_API Z3_le_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than or equal to the value returned by p2.
Z3_probe Z3_API Z3_ge_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than or equal to the value returned by p2.
Z3_probe Z3_API Z3_eq_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is equal to the value returned by p2.
Z3_probe Z3_API Z3_and_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when p1 and p2 evaluates to true.
Z3_probe Z3_API Z3_or_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when p1 or p2 evaluates to true.
Z3_probe Z3_API Z3_not_probe (__in Z3_context x, __in Z3_probe p)
Return a probe that evaluates to "true" when p does not evaluate to true.
Z3_string Z3_API Z3_get_tactic_help (__in Z3_context c, __in_z Z3_string name)
Return a string containing a description of the tactic with the given name.
Z3_string Z3_API Z3_get_probe_help (__in Z3_context c, __in_z Z3_string name)
Return a string containing a description of the probe with the given name.
Define Documentation
#define Z3_FALSE 0
False value. It is just an alias for 0.
Definition at line 87 of file z3_api.h.
#define Z3_FALSE 0
False value. It is just an alias for 0.
Definition at line 122 of file z3_api.h.
Referenced by assert_retractable_cnstr(), bitvector_example1(), enum_example(), ext_check(), list_example(), PATh_final_check(), PATh_reduce_app(), prove_example1(), prove_example2(), reassert_cnstr(), Th_reduce_app(), tree_example(), and tuple_example1().
#define Z3_TRUE 1
True value. It is just an alias for 1.
Definition at line 82 of file z3_api.h.
#define Z3_TRUE 1
True value. It is just an alias for 1.
Definition at line 117 of file z3_api.h.
Referenced by array_example1(), binary_tree_example(), enum_example(), forest_example(), get_num_disabled_soft_constraints(), list_example(), numeral_example(), parser_example3(), PATh_final_check(), PATh_reduce_app(), prove_example1(), prove_example2(), quantifier_example1(), retract_cnstr(), Th_final_check(), Th_reduce_app(), tree_example(), and tuple_example1().
Typedef Documentation
typedef int Z3_bool
Z3 Boolean type. It is just an alias for int.
Definition at line 55 of file z3_api.h.
typedef int Z3_bool
Z3 Boolean type. It is just an alias for int.
Definition at line 97 of file z3_api.h.
typedef void Z3_datalog_reduce_assign_callback_fptr(__in Z3_context, __in Z3_func_decl, __in unsigned, __in Z3_ast const [], __in unsigned, __in Z3_ast const [])
The following utilities allows adding user-defined domains.
Definition at line 4961 of file z3_api.h.
typedef void Z3_error_handler(Z3_error_code e)
Z3 custom error handler (See Z3_set_error_handler).
Definition at line 1028 of file z3_api.h.
typedef void Z3_error_handler(Z3_context c, Z3_error_code e)
Z3 custom error handler (See Z3_set_error_handler).
Definition at line 1083 of file z3_api.h.
typedef void Z3_fixedpoint_reduce_assign_callback_fptr(__in void *, __in Z3_func_decl, __in unsigned, __in Z3_ast const [], __in unsigned, __in Z3_ast const [])
The following utilities allows adding user-defined domains.
Definition at line 4896 of file z3_api.h.
typedef const char* Z3_string
Z3 string type. It is just an alias for const char *.
Definition at line 67 of file z3_api.h.
typedef const char* Z3_string
Z3 string type. It is just an alias for const char *.
Definition at line 106 of file z3_api.h.
Enumeration Type Documentation
enum Z3_ast_kind
The different kinds of Z3 AST (abstract syntax trees). That is, terms, formulas and types.
Z3_APP_AST: constant and applications
Z3_NUMERAL_AST: numeral constants
Z3_VAR_AST: bound variables
Z3_QUANTIFIER_AST: quantifiers
Z3_SORT_AST: sort
Z3_FUNC_DECL_AST: function declaration
Z3_UNKNOWN_AST: internal
Definition at line 165 of file z3_api.h.
{
    Z3_NUMERAL_AST,
    Z3_APP_AST,
    Z3_VAR_AST,
    Z3_QUANTIFIER_AST,
    Z3_SORT_AST,
    Z3_FUNC_DECL_AST,
    Z3_UNKNOWN_AST = 1000
} Z3_ast_kind;
enum Z3_ast_kind
The different kinds of Z3 AST (abstract syntax trees). That is, terms, formulas and types.
Z3_APP_AST: constant and applications
Z3_NUMERAL_AST: numeral constants
Z3_VAR_AST: bound variables
Z3_QUANTIFIER_AST: quantifiers
Z3_SORT_AST: sort
Z3_FUNC_DECL_AST: function declaration
Z3_UNKNOWN_AST: internal
Definition at line 207 of file z3_api.h.
{
    Z3_NUMERAL_AST,
    Z3_APP_AST,
    Z3_VAR_AST,
    Z3_QUANTIFIER_AST,
    Z3_SORT_AST,
    Z3_FUNC_DECL_AST,
    Z3_UNKNOWN_AST = 1000
} Z3_ast_kind;
enum Z3_ast_print_mode
Z3 pretty printing modes (See Z3_set_ast_print_mode).
Z3_PRINT_SMTLIB_FULL: Print AST nodes in SMTLIB verbose format.
Z3_PRINT_LOW_LEVEL: Print AST nodes using a low-level format.
Z3_PRINT_SMTLIB_COMPLIANT: Print AST nodes in SMTLIB 1.x compliant format.
Z3_PRINT_SMTLIB2_COMPLIANT: Print AST nodes in SMTLIB 2.x compliant format.
Definition at line 983 of file z3_api.h.
             {
    Z3_PRINT_SMTLIB_FULL,
    Z3_PRINT_LOW_LEVEL,
    Z3_PRINT_SMTLIB_COMPLIANT,
    Z3_PRINT_SMTLIB2_COMPLIANT
} Z3_ast_print_mode;
enum Z3_ast_print_mode
Z3 pretty printing modes (See Z3_set_ast_print_mode).
Z3_PRINT_SMTLIB_FULL: Print AST nodes in SMTLIB verbose format.
Z3_PRINT_LOW_LEVEL: Print AST nodes using a low-level format.
Z3_PRINT_SMTLIB_COMPLIANT: Print AST nodes in SMTLIB 1.x compliant format.
Z3_PRINT_SMTLIB2_COMPLIANT: Print AST nodes in SMTLIB 2.x compliant format.
Definition at line 1033 of file z3_api.h.
             {
    Z3_PRINT_SMTLIB_FULL,
    Z3_PRINT_LOW_LEVEL,
    Z3_PRINT_SMTLIB_COMPLIANT,
    Z3_PRINT_SMTLIB2_COMPLIANT
} Z3_ast_print_mode;
enum Z3_decl_kind
The different kinds of interpreted function kinds.
(*
Z3_OP_TRUE The constant true.
Z3_OP_FALSE The constant false.
Z3_OP_EQ The equality predicate.
Z3_OP_DISTINCT The n-ary distinct predicate (every argument is mutually distinct).
Z3_OP_ITE The ternary if-then-else term.
Z3_OP_AND n-ary conjunction.
Z3_OP_OR n-ary disjunction.
Z3_OP_IFF equivalence (binary).
Z3_OP_XOR Exclusive or.
Z3_OP_NOT Negation.
Z3_OP_IMPLIES Implication.
Z3_OP_OEQ Binary equivalence modulo namings. This binary predicate is used in proof terms. It captures equisatisfiability and equivalence modulo renamings.
Z3_OP_ANUM Arithmetic numeral.
Z3_OP_LE <=.
Z3_OP_GE >=.
Z3_OP_LT <.
Z3_OP_GT >.
Z3_OP_ADD Addition - Binary.
Z3_OP_SUB Binary subtraction.
Z3_OP_UMINUS Unary minus.
Z3_OP_MUL Multiplication - Binary.
Z3_OP_DIV Division - Binary.
Z3_OP_IDIV Integer division - Binary.
Z3_OP_REM Remainder - Binary.
Z3_OP_MOD Modulus - Binary.
Z3_OP_TO_REAL Coercion of integer to real - Unary.
Z3_OP_TO_INT Coercion of real to integer - Unary.
Z3_OP_IS_INT Check if real is also an integer - Unary.
Z3_OP_STORE Array store. It satisfies select(store(a,i,v),j) = if i = j then v else select(a,j). Array store takes at least 3 arguments.
Z3_OP_SELECT Array select.
Z3_OP_CONST_ARRAY The constant array. For example, select(const(v),i) = v holds for every v and i. The function is unary.
Z3_OP_ARRAY_DEFAULT Default value of arrays. For example default(const(v)) = v. The function is unary.
Z3_OP_ARRAY_MAP Array map operator. It satisfies map[f](a1,..,a_n)[i] = f(a1[i],...,a_n[i]) for every i.
Z3_OP_SET_UNION Set union between two Booelan arrays (two arrays whose range type is Boolean). The function is binary.
Z3_OP_SET_INTERSECT Set intersection between two Boolean arrays. The function is binary.
Z3_OP_SET_DIFFERENCE Set difference between two Boolean arrays. The function is binary.
Z3_OP_SET_COMPLEMENT Set complement of a Boolean array. The function is unary.
Z3_OP_SET_SUBSET Subset predicate between two Boolean arrays. The relation is binary.
Z3_OP_AS_ARRAY An array value that behaves as the function graph of the function passed as parameter.
Z3_OP_BNUM Bit-vector numeral.
Z3_OP_BIT1 One bit bit-vector.
Z3_OP_BIT0 Zero bit bit-vector.
Z3_OP_BNEG Unary minus.
Z3_OP_BADD Binary addition.
Z3_OP_BSUB Binary subtraction.
Z3_OP_BMUL Binary multiplication.
Z3_OP_BSDIV Binary signed division.
Z3_OP_BUDIV Binary unsigned division.
Z3_OP_BSREM Binary signed remainder.
Z3_OP_BUREM Binary unsigned remainder.
Z3_OP_BSMOD Binary signed modulus.
Z3_OP_BSDIV0 Unary function. bsdiv(x,0) is congruent to bsdiv0(x).
Z3_OP_BUDIV0 Unary function. budiv(x,0) is congruent to budiv0(x).
Z3_OP_BSREM0 Unary function. bsrem(x,0) is congruent to bsrem0(x).
Z3_OP_BUREM0 Unary function. burem(x,0) is congruent to burem0(x).
Z3_OP_BSMOD0 Unary function. bsmod(x,0) is congruent to bsmod0(x).
Z3_OP_ULEQ Unsigned bit-vector <= - Binary relation.
Z3_OP_SLEQ Signed bit-vector <= - Binary relation.
Z3_OP_UGEQ Unsigned bit-vector >= - Binary relation.
Z3_OP_SGEQ Signed bit-vector >= - Binary relation.
Z3_OP_ULT Unsigned bit-vector < - Binary relation.
Z3_OP_SLT Signed bit-vector < - Binary relation.
Z3_OP_UGT Unsigned bit-vector > - Binary relation.
Z3_OP_SGT Signed bit-vector > - Binary relation.
Z3_OP_BAND Bit-wise and - Binary.
Z3_OP_BOR Bit-wise or - Binary.
Z3_OP_BNOT Bit-wise not - Unary.
Z3_OP_BXOR Bit-wise xor - Binary.
Z3_OP_BNAND Bit-wise nand - Binary.
Z3_OP_BNOR Bit-wise nor - Binary.
Z3_OP_BXNOR Bit-wise xnor - Binary.
Z3_OP_CONCAT Bit-vector concatenation - Binary.
Z3_OP_SIGN_EXT Bit-vector sign extension.
Z3_OP_ZERO_EXT Bit-vector zero extension.
Z3_OP_EXTRACT Bit-vector extraction.
Z3_OP_REPEAT Repeat bit-vector n times.
Z3_OP_BREDOR Bit-vector reduce or - Unary.
Z3_OP_BREDAND Bit-vector reduce and - Unary.
Z3_OP_BCOMP .
Z3_OP_BSHL Shift left.
Z3_OP_BLSHR Logical shift right.
Z3_OP_BASHR Arithmetical shift right.
Z3_OP_ROTATE_LEFT Left rotation.
Z3_OP_ROTATE_RIGHT Right rotation.
Z3_OP_EXT_ROTATE_LEFT (extended) Left rotation. Similar to Z3_OP_ROTATE_LEFT, but it is a binary operator instead of a parametric one.
Z3_OP_EXT_ROTATE_RIGHT (extended) Right rotation. Similar to Z3_OP_ROTATE_RIGHT, but it is a binary operator instead of a parametric one.
Z3_OP_INT2BV Coerce integer to bit-vector. NB. This function is not supported by the decision procedures. Only the most rudimentary simplification rules are applied to this function.
Z3_OP_BV2INT Coerce bit-vector to integer. NB. This function is not supported by the decision procedures. Only the most rudimentary simplification rules are applied to this function.
Z3_OP_CARRY Compute the carry bit in a full-adder. The meaning is given by the equivalence (carry l1 l2 l3) <=> (or (and l1 l2) (and l1 l3) (and l2 l3)))
Z3_OP_XOR3 Compute ternary XOR. The meaning is given by the equivalence (xor3 l1 l2 l3) <=> (xor (xor l1 l2) l3)
Z3_OP_PR_TRUE: Proof for the expression 'true'.
Z3_OP_PR_ASSERTED: Proof for a fact asserted by the user.
Z3_OP_PR_GOAL: Proof for a fact (tagged as goal) asserted by the user.
Z3_OP_PR_MODUS_PONENS: Given a proof for p and a proof for (implies p q), produces a proof for q.
          T1: p
          T2: (implies p q)
          [mp T1 T2]: q
The second antecedents may also be a proof for (iff p q).
Z3_OP_PR_REFLEXIVITY: A proof for (R t t), where R is a reflexive relation. This proof object has no antecedents. The only reflexive relations that are used are equivalence modulo namings, equality and equivalence. That is, R is either '~', '=' or 'iff'.
Z3_OP_PR_SYMMETRY: Given an symmetric relation R and a proof for (R t s), produces a proof for (R s t).
          T1: (R t s)
          [symmetry T1]: (R s t)
T1 is the antecedent of this proof object.
Z3_OP_PR_TRANSITIVITY: Given a transitive relation R, and proofs for (R t s) and (R s u), produces a proof for (R t u).
       T1: (R t s)
       T2: (R s u)
       [trans T1 T2]: (R t u)
Z3_OP_PR_TRANSITIVITY_STAR: Condensed transitivity proof. This proof object is only used if the parameter PROOF_MODE is 1. It combines several symmetry and transitivity proofs.
Example:
          T1: (R a b)
          T2: (R c b)
          T3: (R c d)
          [trans* T1 T2 T3]: (R a d)
R must be a symmetric and transitive relation.
Assuming that this proof object is a proof for (R s t), then a proof checker must check if it is possible to prove (R s t) using the antecedents, symmetry and transitivity. That is, if there is a path from s to t, if we view every antecedent (R a b) as an edge between a and b.
Z3_OP_PR_MONOTONICITY: Monotonicity proof object.
          T1: (R t_1 s_1)
          ...
          Tn: (R t_n s_n)
          [monotonicity T1 ... Tn]: (R (f t_1 ... t_n) (f s_1 ... s_n))
Remark: if t_i == s_i, then the antecedent Ti is suppressed. That is, reflexivity proofs are supressed to save space.
Z3_OP_PR_QUANT_INTRO: Given a proof for (~ p q), produces a proof for (~ (forall (x) p) (forall (x) q)).
T1: (~ p q) [quant-intro T1]: (~ (forall (x) p) (forall (x) q))
Z3_OP_PR_DISTRIBUTIVITY: Distributivity proof object. Given that f (= or) distributes over g (= and), produces a proof for
(= (f a (g c d)) (g (f a c) (f a d)))
If f and g are associative, this proof also justifies the following equality:
(= (f (g a b) (g c d)) (g (f a c) (f a d) (f b c) (f b d)))
where each f and g can have arbitrary number of arguments.
This proof object has no antecedents. Remark. This rule is used by the CNF conversion pass and instantiated by f = or, and g = and.
Z3_OP_PR_AND_ELIM: Given a proof for (and l_1 ... l_n), produces a proof for l_i
       T1: (and l_1 ... l_n)
       [and-elim T1]: l_i
Z3_OP_PR_NOT_OR_ELIM: Given a proof for (not (or l_1 ... l_n)), produces a proof for (not l_i).
       T1: (not (or l_1 ... l_n))
       [not-or-elim T1]: (not l_i)
Z3_OP_PR_REWRITE: A proof for a local rewriting step (= t s). The head function symbol of t is interpreted.
This proof object has no antecedents. The conclusion of a rewrite rule is either an equality (= t s), an equivalence (iff t s), or equi-satisfiability (~ t s). Remark: if f is bool, then = is iff.
Examples:
          (= (+ x 0) x)
          (= (+ x 1 2) (+ 3 x))
          (iff (or x false) x)
Z3_OP_PR_REWRITE_STAR: A proof for rewriting an expression t into an expression s. This proof object is used if the parameter PROOF_MODE is 1. This proof object can have n antecedents. The antecedents are proofs for equalities used as substitution rules. The object is also used in a few cases if the parameter PROOF_MODE is 2. The cases are:
When applying contextual simplification (CONTEXT_SIMPLIFIER=true)
When converting bit-vectors to Booleans (BIT2BOOL=true)
When pulling ite expression up (PULL_CHEAP_ITE_TREES=true)
Z3_OP_PR_PULL_QUANT: A proof for (iff (f (forall (x) q(x)) r) (forall (x) (f (q x) r))). This proof object has no antecedents.
Z3_OP_PR_PULL_QUANT_STAR: A proof for (iff P Q) where Q is in prenex normal form. This proof object is only used if the parameter PROOF_MODE is 1. This proof object has no antecedents.
Z3_OP_PR_PUSH_QUANT: A proof for:
          (iff (forall (x_1 ... x_m) (and p_1[x_1 ... x_m] ... p_n[x_1 ... x_m]))
               (and (forall (x_1 ... x_m) p_1[x_1 ... x_m])
                 ...
               (forall (x_1 ... x_m) p_n[x_1 ... x_m])))
This proof object has no antecedents.
Z3_OP_PR_ELIM_UNUSED_VARS: A proof for (iff (forall (x_1 ... x_n y_1 ... y_m) p[x_1 ... x_n]) (forall (x_1 ... x_n) p[x_1 ... x_n]))
It is used to justify the elimination of unused variables. This proof object has no antecedents.
Z3_OP_PR_DER: A proof for destructive equality resolution: (iff (forall (x) (or (not (= x t)) P[x])) P[t]) if x does not occur in t.
This proof object has no antecedents.
Several variables can be eliminated simultaneously.
Z3_OP_PR_QUANT_INST: A proof of (or (not (forall (x) (P x))) (P a))
Z3_OP_PR_HYPOTHESIS: Mark a hypothesis in a natural deduction style proof.
Z3_OP_PR_LEMMA:
          T1: false
          [lemma T1]: (or (not l_1) ... (not l_n))
This proof object has one antecedent: a hypothetical proof for false. It converts the proof in a proof for (or (not l_1) ... (not l_n)), when T1 contains the hypotheses: l_1, ..., l_n.
Z3_OP_PR_UNIT_RESOLUTION:
          T1:      (or l_1 ... l_n l_1' ... l_m')
          T2:      (not l_1)
          ...
          T(n+1):  (not l_n)
          [unit-resolution T1 ... T(n+1)]: (or l_1' ... l_m')
Z3_OP_PR_IFF_TRUE:
       T1: p
       [iff-true T1]: (iff p true)
Z3_OP_PR_IFF_FALSE:
       T1: (not p)
       [iff-false T1]: (iff p false)
Z3_OP_PR_COMMUTATIVITY:
[comm]: (= (f a b) (f b a))
f is a commutative operator.
This proof object has no antecedents. Remark: if f is bool, then = is iff.
Z3_OP_PR_DEF_AXIOM: Proof object used to justify Tseitin's like axioms:
          (or (not (and p q)) p)
          (or (not (and p q)) q)
          (or (not (and p q r)) p)
          (or (not (and p q r)) q)
          (or (not (and p q r)) r)
          ...
          (or (and p q) (not p) (not q))
          (or (not (or p q)) p q)
          (or (or p q) (not p))
          (or (or p q) (not q))
          (or (not (iff p q)) (not p) q)
          (or (not (iff p q)) p (not q))
          (or (iff p q) (not p) (not q))
          (or (iff p q) p q)
          (or (not (ite a b c)) (not a) b)
          (or (not (ite a b c)) a c)
          (or (ite a b c) (not a) (not b))
          (or (ite a b c) a (not c))
          (or (not (not a)) (not a))
          (or (not a) a)
This proof object has no antecedents. Note: all axioms are propositional tautologies. Note also that 'and' and 'or' can take multiple arguments. You can recover the propositional tautologies by unfolding the Boolean connectives in the axioms a small bounded number of steps (=3).
Z3_OP_PR_DEF_INTRO: Introduces a name for a formula/term. Suppose e is an expression with free variables x, and def-intro introduces the name n(x). The possible cases are:
When e is of Boolean type: [def-intro]: (and (or n (not e)) (or (not n) e))
or: [def-intro]: (or (not n) e) when e only occurs positively.
When e is of the form (ite cond th el): [def-intro]: (and (or (not cond) (= n th)) (or cond (= n el)))
Otherwise: [def-intro]: (= n e)
Z3_OP_PR_APPLY_DEF: [apply-def T1]: F ~ n F is 'equivalent' to n, given that T1 is a proof that n is a name for F.
Z3_OP_PR_IFF_OEQ: T1: (iff p q) [iff~ T1]: (~ p q)
Z3_OP_PR_NNF_POS: Proof for a (positive) NNF step. Example:
          T1: (not s_1) ~ r_1
          T2: (not s_2) ~ r_2
          T3: s_1 ~ r_1'
          T4: s_2 ~ r_2'
          [nnf-pos T1 T2 T3 T4]: (~ (iff s_1 s_2)
                                    (and (or r_1 r_2') (or r_1' r_2)))
The negation normal form steps NNF_POS and NNF_NEG are used in the following cases: (a) When creating the NNF of a positive force quantifier. The quantifier is retained (unless the bound variables are eliminated). Example
           T1: q ~ q_new
           [nnf-pos T1]: (~ (forall (x T) q) (forall (x T) q_new))
(b) When recursively creating NNF over Boolean formulas, where the top-level connective is changed during NNF conversion. The relevant Boolean connectives for NNF_POS are 'implies', 'iff', 'xor', 'ite'. NNF_NEG furthermore handles the case where negation is pushed over Boolean connectives 'and' and 'or'.
Z3_OP_PR_NFF_NEG: Proof for a (negative) NNF step. Examples:
          T1: (not s_1) ~ r_1
          ...
          Tn: (not s_n) ~ r_n
         [nnf-neg T1 ... Tn]: (not (and s_1 ... s_n)) ~ (or r_1 ... r_n)
      and
          T1: (not s_1) ~ r_1
          ...
          Tn: (not s_n) ~ r_n
         [nnf-neg T1 ... Tn]: (not (or s_1 ... s_n)) ~ (and r_1 ... r_n)
      and
          T1: (not s_1) ~ r_1
          T2: (not s_2) ~ r_2
          T3: s_1 ~ r_1'
          T4: s_2 ~ r_2'
         [nnf-neg T1 T2 T3 T4]: (~ (not (iff s_1 s_2))
                                   (and (or r_1 r_2) (or r_1' r_2')))
Z3_OP_PR_NNF_STAR: A proof for (~ P Q) where Q is in negation normal form.
This proof object is only used if the parameter PROOF_MODE is 1.
This proof object may have n antecedents. Each antecedent is a PR_DEF_INTRO.
Z3_OP_PR_CNF_STAR: A proof for (~ P Q) where Q is in conjunctive normal form. This proof object is only used if the parameter PROOF_MODE is 1. This proof object may have n antecedents. Each antecedent is a PR_DEF_INTRO.
Z3_OP_PR_SKOLEMIZE: Proof for:
          [sk]: (~ (not (forall x (p x y))) (not (p (sk y) y)))
          [sk]: (~ (exists x (p x y)) (p (sk y) y))
This proof object has no antecedents.
Z3_OP_PR_MODUS_PONENS_OEQ: Modus ponens style rule for equi-satisfiability.
          T1: p
          T2: (~ p q)
          [mp~ T1 T2]: q
Z3_OP_PR_TH_LEMMA: Generic proof for theory lemmas.
The theory lemma function comes with one or more parameters. The first parameter indicates the name of the theory. For the theory of arithmetic, additional parameters provide hints for checking the theory lemma. The hints for arithmetic are:
farkas - followed by rational coefficients. Multiply the coefficients to the inequalities in the lemma, add the (negated) inequalities and obtain a contradiction.
triangle-eq - Indicates a lemma related to the equivalence:
            (iff (= t1 t2) (and (<= t1 t2) (<= t2 t1)))
gcd-test - Indicates an integer linear arithmetic lemma that uses a gcd test.
Z3_OP_RA_STORE: Insert a record into a relation. The function takes n+1 arguments, where the first argument is the relation and the remaining n elements correspond to the n columns of the relation.
Z3_OP_RA_EMPTY: Creates the empty relation.
Z3_OP_RA_IS_EMPTY: Tests if the relation is empty.
Z3_OP_RA_JOIN: Create the relational join.
Z3_OP_RA_UNION: Create the union or convex hull of two relations. The function takes two arguments.
Z3_OP_RA_WIDEN: Widen two relations. The function takes two arguments.
Z3_OP_RA_PROJECT: Project the columns (provided as numbers in the parameters). The function takes one argument.
Z3_OP_RA_FILTER: Filter (restrict) a relation with respect to a predicate. The first argument is a relation. The second argument is a predicate with free de-Brujin indices corresponding to the columns of the relation. So the first column in the relation has index 0.
Z3_OP_RA_NEGATION_FILTER: Intersect the first relation with respect to negation of the second relation (the function takes two arguments). Logically, the specification can be described by a function
target = filter_by_negation(pos, neg, columns)
where columns are pairs c1, d1, .., cN, dN of columns from pos and neg, such that target are elements in x in pos, such that there is no y in neg that agrees with x on the columns c1, d1, .., cN, dN.
Z3_OP_RA_RENAME: rename columns in the relation. The function takes one argument. The parameters contain the renaming as a cycle.
Z3_OP_RA_COMPLEMENT: Complement the relation.
Z3_OP_RA_SELECT: Check if a record is an element of the relation. The function takes n+1 arguments, where the first argument is a relation, and the remaining n arguments correspond to a record.
Z3_OP_RA_CLONE: Create a fresh copy (clone) of a relation. The function is logically the identity, but in the context of a register machine allows for Z3_OP_RA_UNION to perform destructive updates to the first argument.
Z3_OP_FD_LT: A less than predicate over the finite domain Z3_FINITE_DOMAIN_SORT.
Z3_OP_LABEL: A label (used by the Boogie Verification condition generator). The label has two parameters, a string and a Boolean polarity. It takes one argument, a formula.
Z3_OP_LABEL_LIT: A label literal (used by the Boogie Verification condition generator). A label literal has a set of string parameters. It takes no arguments.
)
Definition at line 780 of file z3_api.h.
             {
    Z3_OP_TRUE = 0x100,
    Z3_OP_FALSE,
    Z3_OP_EQ,
    Z3_OP_DISTINCT,
    Z3_OP_ITE,
    Z3_OP_AND,
    Z3_OP_OR,
    Z3_OP_IFF,
    Z3_OP_XOR,
    Z3_OP_NOT,
    Z3_OP_IMPLIES,
    Z3_OP_OEQ,
    Z3_OP_ANUM = 0x200,
    Z3_OP_AGNUM,
    Z3_OP_LE,
    Z3_OP_GE,
    Z3_OP_LT,
    Z3_OP_GT,
    Z3_OP_ADD,
    Z3_OP_SUB,
    Z3_OP_UMINUS,
    Z3_OP_MUL,
    Z3_OP_DIV,
    Z3_OP_IDIV,
    Z3_OP_REM,
    Z3_OP_MOD,
    Z3_OP_TO_REAL,
    Z3_OP_TO_INT,
    Z3_OP_IS_INT,
    Z3_OP_POWER,
    Z3_OP_STORE = 0x300,
    Z3_OP_SELECT,
    Z3_OP_CONST_ARRAY,
    Z3_OP_ARRAY_MAP,
    Z3_OP_ARRAY_DEFAULT,
    Z3_OP_SET_UNION,
    Z3_OP_SET_INTERSECT,
    Z3_OP_SET_DIFFERENCE,
    Z3_OP_SET_COMPLEMENT,
    Z3_OP_SET_SUBSET,
    Z3_OP_AS_ARRAY,
    Z3_OP_BNUM = 0x400,
    Z3_OP_BIT1,
    Z3_OP_BIT0,
    Z3_OP_BNEG,
    Z3_OP_BADD,
    Z3_OP_BSUB,
    Z3_OP_BMUL,
    Z3_OP_BSDIV,
    Z3_OP_BUDIV,
    Z3_OP_BSREM,
    Z3_OP_BUREM,
    Z3_OP_BSMOD,
    // special functions to record the division by 0 cases
    // these are internal functions
    Z3_OP_BSDIV0,
    Z3_OP_BUDIV0,
    Z3_OP_BSREM0,
    Z3_OP_BUREM0,
    Z3_OP_BSMOD0,
    Z3_OP_ULEQ,
    Z3_OP_SLEQ,
    Z3_OP_UGEQ,
    Z3_OP_SGEQ,
    Z3_OP_ULT,
    Z3_OP_SLT,
    Z3_OP_UGT,
    Z3_OP_SGT,
    Z3_OP_BAND,
    Z3_OP_BOR,
    Z3_OP_BNOT,
    Z3_OP_BXOR,
    Z3_OP_BNAND,
    Z3_OP_BNOR,
    Z3_OP_BXNOR,
    Z3_OP_CONCAT,
    Z3_OP_SIGN_EXT,
    Z3_OP_ZERO_EXT,
    Z3_OP_EXTRACT,
    Z3_OP_REPEAT,
    Z3_OP_BREDOR,
    Z3_OP_BREDAND,
    Z3_OP_BCOMP,
    Z3_OP_BSHL,
    Z3_OP_BLSHR,
    Z3_OP_BASHR,
    Z3_OP_ROTATE_LEFT,
    Z3_OP_ROTATE_RIGHT,
    Z3_OP_EXT_ROTATE_LEFT,
    Z3_OP_EXT_ROTATE_RIGHT,
    Z3_OP_INT2BV,
    Z3_OP_BV2INT,
    Z3_OP_CARRY,
    Z3_OP_XOR3,
    Z3_OP_PR_UNDEF = 0x500,
    Z3_OP_PR_TRUE,
    Z3_OP_PR_ASSERTED,
    Z3_OP_PR_GOAL,
    Z3_OP_PR_MODUS_PONENS,
    Z3_OP_PR_REFLEXIVITY,
    Z3_OP_PR_SYMMETRY,
    Z3_OP_PR_TRANSITIVITY,
    Z3_OP_PR_TRANSITIVITY_STAR,
    Z3_OP_PR_MONOTONICITY,
    Z3_OP_PR_QUANT_INTRO,
    Z3_OP_PR_DISTRIBUTIVITY,
    Z3_OP_PR_AND_ELIM,
    Z3_OP_PR_NOT_OR_ELIM,
    Z3_OP_PR_REWRITE,
    Z3_OP_PR_REWRITE_STAR,
    Z3_OP_PR_PULL_QUANT,
    Z3_OP_PR_PULL_QUANT_STAR,
    Z3_OP_PR_PUSH_QUANT,
    Z3_OP_PR_ELIM_UNUSED_VARS,
    Z3_OP_PR_DER,
    Z3_OP_PR_QUANT_INST,
    Z3_OP_PR_HYPOTHESIS,
    Z3_OP_PR_LEMMA,
    Z3_OP_PR_UNIT_RESOLUTION,
    Z3_OP_PR_IFF_TRUE,
    Z3_OP_PR_IFF_FALSE,
    Z3_OP_PR_COMMUTATIVITY,
    Z3_OP_PR_DEF_AXIOM,
    Z3_OP_PR_DEF_INTRO,
    Z3_OP_PR_APPLY_DEF,
    Z3_OP_PR_IFF_OEQ,
    Z3_OP_PR_NNF_POS,
    Z3_OP_PR_NNF_NEG,
    Z3_OP_PR_NNF_STAR,
    Z3_OP_PR_CNF_STAR,
    Z3_OP_PR_SKOLEMIZE,
    Z3_OP_PR_MODUS_PONENS_OEQ,
    Z3_OP_PR_TH_LEMMA,
    Z3_OP_RA_STORE = 0x600,
    Z3_OP_RA_EMPTY,
    Z3_OP_RA_IS_EMPTY,
    Z3_OP_RA_JOIN,
    Z3_OP_RA_UNION,
    Z3_OP_RA_WIDEN,
    Z3_OP_RA_PROJECT,
    Z3_OP_RA_FILTER,
    Z3_OP_RA_NEGATION_FILTER,
    Z3_OP_RA_RENAME,
    Z3_OP_RA_COMPLEMENT,
    Z3_OP_RA_SELECT,
    Z3_OP_RA_CLONE,
    Z3_OP_FD_LT,
    Z3_OP_LABEL = 0x700,
    Z3_OP_LABEL_LIT,
    Z3_OP_UNINTERPRETED
} Z3_decl_kind;
enum Z3_decl_kind
The different kinds of interpreted function kinds.
Z3_OP_TRUE The constant true.
Z3_OP_FALSE The constant false.
Z3_OP_EQ The equality predicate.
Z3_OP_DISTINCT The n-ary distinct predicate (every argument is mutually distinct).
Z3_OP_ITE The ternary if-then-else term.
Z3_OP_AND n-ary conjunction.
Z3_OP_OR n-ary disjunction.
Z3_OP_IFF equivalence (binary).
Z3_OP_XOR Exclusive or.
Z3_OP_NOT Negation.
Z3_OP_IMPLIES Implication.
Z3_OP_OEQ Binary equivalence modulo namings. This binary predicate is used in proof terms. It captures equisatisfiability and equivalence modulo renamings.
Z3_OP_ANUM Arithmetic numeral.
Z3_OP_AGNUM Arithmetic algebraic numeral. Algebraic numbers are used to represent irrational numbers in Z3.
Z3_OP_LE <=.
Z3_OP_GE >=.
Z3_OP_LT <.
Z3_OP_GT >.
Z3_OP_ADD Addition - Binary.
Z3_OP_SUB Binary subtraction.
Z3_OP_UMINUS Unary minus.
Z3_OP_MUL Multiplication - Binary.
Z3_OP_DIV Division - Binary.
Z3_OP_IDIV Integer division - Binary.
Z3_OP_REM Remainder - Binary.
Z3_OP_MOD Modulus - Binary.
Z3_OP_TO_REAL Coercion of integer to real - Unary.
Z3_OP_TO_INT Coercion of real to integer - Unary.
Z3_OP_IS_INT Check if real is also an integer - Unary.
Z3_OP_POWER Power operator x^y.
Z3_OP_STORE Array store. It satisfies select(store(a,i,v),j) = if i = j then v else select(a,j). Array store takes at least 3 arguments.
Z3_OP_SELECT Array select.
Z3_OP_CONST_ARRAY The constant array. For example, select(const(v),i) = v holds for every v and i. The function is unary.
Z3_OP_ARRAY_DEFAULT Default value of arrays. For example default(const(v)) = v. The function is unary.
Z3_OP_ARRAY_MAP Array map operator. It satisfies map[f](a1,..,a_n)[i] = f(a1[i],...,a_n[i]) for every i.
Z3_OP_SET_UNION Set union between two Booelan arrays (two arrays whose range type is Boolean). The function is binary.
Z3_OP_SET_INTERSECT Set intersection between two Boolean arrays. The function is binary.
Z3_OP_SET_DIFFERENCE Set difference between two Boolean arrays. The function is binary.
Z3_OP_SET_COMPLEMENT Set complement of a Boolean array. The function is unary.
Z3_OP_SET_SUBSET Subset predicate between two Boolean arrays. The relation is binary.
Z3_OP_AS_ARRAY An array value that behaves as the function graph of the function passed as parameter.
Z3_OP_BNUM Bit-vector numeral.
Z3_OP_BIT1 One bit bit-vector.
Z3_OP_BIT0 Zero bit bit-vector.
Z3_OP_BNEG Unary minus.
Z3_OP_BADD Binary addition.
Z3_OP_BSUB Binary subtraction.
Z3_OP_BMUL Binary multiplication.
Z3_OP_BSDIV Binary signed division.
Z3_OP_BUDIV Binary unsigned division.
Z3_OP_BSREM Binary signed remainder.
Z3_OP_BUREM Binary unsigned remainder.
Z3_OP_BSMOD Binary signed modulus.
Z3_OP_BSDIV0 Unary function. bsdiv(x,0) is congruent to bsdiv0(x).
Z3_OP_BUDIV0 Unary function. budiv(x,0) is congruent to budiv0(x).
Z3_OP_BSREM0 Unary function. bsrem(x,0) is congruent to bsrem0(x).
Z3_OP_BUREM0 Unary function. burem(x,0) is congruent to burem0(x).
Z3_OP_BSMOD0 Unary function. bsmod(x,0) is congruent to bsmod0(x).
Z3_OP_ULEQ Unsigned bit-vector <= - Binary relation.
Z3_OP_SLEQ Signed bit-vector <= - Binary relation.
Z3_OP_UGEQ Unsigned bit-vector >= - Binary relation.
Z3_OP_SGEQ Signed bit-vector >= - Binary relation.
Z3_OP_ULT Unsigned bit-vector < - Binary relation.
Z3_OP_SLT Signed bit-vector < - Binary relation.
Z3_OP_UGT Unsigned bit-vector > - Binary relation.
Z3_OP_SGT Signed bit-vector > - Binary relation.
Z3_OP_BAND Bit-wise and - Binary.
Z3_OP_BOR Bit-wise or - Binary.
Z3_OP_BNOT Bit-wise not - Unary.
Z3_OP_BXOR Bit-wise xor - Binary.
Z3_OP_BNAND Bit-wise nand - Binary.
Z3_OP_BNOR Bit-wise nor - Binary.
Z3_OP_BXNOR Bit-wise xnor - Binary.
Z3_OP_CONCAT Bit-vector concatenation - Binary.
Z3_OP_SIGN_EXT Bit-vector sign extension.
Z3_OP_ZERO_EXT Bit-vector zero extension.
Z3_OP_EXTRACT Bit-vector extraction.
Z3_OP_REPEAT Repeat bit-vector n times.
Z3_OP_BREDOR Bit-vector reduce or - Unary.
Z3_OP_BREDAND Bit-vector reduce and - Unary.
Z3_OP_BCOMP .
Z3_OP_BSHL Shift left.
Z3_OP_BLSHR Logical shift right.
Z3_OP_BASHR Arithmetical shift right.
Z3_OP_ROTATE_LEFT Left rotation.
Z3_OP_ROTATE_RIGHT Right rotation.
Z3_OP_EXT_ROTATE_LEFT (extended) Left rotation. Similar to Z3_OP_ROTATE_LEFT, but it is a binary operator instead of a parametric one.
Z3_OP_EXT_ROTATE_RIGHT (extended) Right rotation. Similar to Z3_OP_ROTATE_RIGHT, but it is a binary operator instead of a parametric one.
Z3_OP_INT2BV Coerce integer to bit-vector. NB. This function is not supported by the decision procedures. Only the most rudimentary simplification rules are applied to this function.
Z3_OP_BV2INT Coerce bit-vector to integer. NB. This function is not supported by the decision procedures. Only the most rudimentary simplification rules are applied to this function.
Z3_OP_CARRY Compute the carry bit in a full-adder. The meaning is given by the equivalence (carry l1 l2 l3) <=> (or (and l1 l2) (and l1 l3) (and l2 l3)))
Z3_OP_XOR3 Compute ternary XOR. The meaning is given by the equivalence (xor3 l1 l2 l3) <=> (xor (xor l1 l2) l3)
Z3_OP_PR_UNDEF: Undef/Null proof object.
Z3_OP_PR_TRUE: Proof for the expression 'true'.
Z3_OP_PR_ASSERTED: Proof for a fact asserted by the user.
Z3_OP_PR_GOAL: Proof for a fact (tagged as goal) asserted by the user.
Z3_OP_PR_MODUS_PONENS: Given a proof for p and a proof for (implies p q), produces a proof for q.
          T1: p
          T2: (implies p q)
          [mp T1 T2]: q
The second antecedents may also be a proof for (iff p q).
Z3_OP_PR_REFLEXIVITY: A proof for (R t t), where R is a reflexive relation. This proof object has no antecedents. The only reflexive relations that are used are equivalence modulo namings, equality and equivalence. That is, R is either '~', '=' or 'iff'.
Z3_OP_PR_SYMMETRY: Given an symmetric relation R and a proof for (R t s), produces a proof for (R s t).
          T1: (R t s)
          [symmetry T1]: (R s t)
T1 is the antecedent of this proof object.
Z3_OP_PR_TRANSITIVITY: Given a transitive relation R, and proofs for (R t s) and (R s u), produces a proof for (R t u).
       T1: (R t s)
       T2: (R s u)
       [trans T1 T2]: (R t u)
Z3_OP_PR_TRANSITIVITY_STAR: Condensed transitivity proof. This proof object is only used if the parameter PROOF_MODE is 1. It combines several symmetry and transitivity proofs.
Example:
          T1: (R a b)
          T2: (R c b)
          T3: (R c d)
          [trans* T1 T2 T3]: (R a d)
R must be a symmetric and transitive relation.
Assuming that this proof object is a proof for (R s t), then a proof checker must check if it is possible to prove (R s t) using the antecedents, symmetry and transitivity. That is, if there is a path from s to t, if we view every antecedent (R a b) as an edge between a and b.
Z3_OP_PR_MONOTONICITY: Monotonicity proof object.
          T1: (R t_1 s_1)
          ...
          Tn: (R t_n s_n)
          [monotonicity T1 ... Tn]: (R (f t_1 ... t_n) (f s_1 ... s_n))
Remark: if t_i == s_i, then the antecedent Ti is suppressed. That is, reflexivity proofs are supressed to save space.
Z3_OP_PR_QUANT_INTRO: Given a proof for (~ p q), produces a proof for (~ (forall (x) p) (forall (x) q)).
T1: (~ p q) [quant-intro T1]: (~ (forall (x) p) (forall (x) q))
Z3_OP_PR_DISTRIBUTIVITY: Distributivity proof object. Given that f (= or) distributes over g (= and), produces a proof for
(= (f a (g c d)) (g (f a c) (f a d)))
If f and g are associative, this proof also justifies the following equality:
(= (f (g a b) (g c d)) (g (f a c) (f a d) (f b c) (f b d)))
where each f and g can have arbitrary number of arguments.
This proof object has no antecedents. Remark. This rule is used by the CNF conversion pass and instantiated by f = or, and g = and.
Z3_OP_PR_AND_ELIM: Given a proof for (and l_1 ... l_n), produces a proof for l_i
       T1: (and l_1 ... l_n)
       [and-elim T1]: l_i
Z3_OP_PR_NOT_OR_ELIM: Given a proof for (not (or l_1 ... l_n)), produces a proof for (not l_i).
       T1: (not (or l_1 ... l_n))
       [not-or-elim T1]: (not l_i)
Z3_OP_PR_REWRITE: A proof for a local rewriting step (= t s). The head function symbol of t is interpreted.
This proof object has no antecedents. The conclusion of a rewrite rule is either an equality (= t s), an equivalence (iff t s), or equi-satisfiability (~ t s). Remark: if f is bool, then = is iff.
Examples:
          (= (+ x 0) x)
          (= (+ x 1 2) (+ 3 x))
          (iff (or x false) x)
Z3_OP_PR_REWRITE_STAR: A proof for rewriting an expression t into an expression s. This proof object is used if the parameter PROOF_MODE is 1. This proof object can have n antecedents. The antecedents are proofs for equalities used as substitution rules. The object is also used in a few cases if the parameter PROOF_MODE is 2. The cases are:
When applying contextual simplification (CONTEXT_SIMPLIFIER=true)
When converting bit-vectors to Booleans (BIT2BOOL=true)
When pulling ite expression up (PULL_CHEAP_ITE_TREES=true)
Z3_OP_PR_PULL_QUANT: A proof for (iff (f (forall (x) q(x)) r) (forall (x) (f (q x) r))). This proof object has no antecedents.
Z3_OP_PR_PULL_QUANT_STAR: A proof for (iff P Q) where Q is in prenex normal form. This proof object is only used if the parameter PROOF_MODE is 1. This proof object has no antecedents.
Z3_OP_PR_PUSH_QUANT: A proof for:
          (iff (forall (x_1 ... x_m) (and p_1[x_1 ... x_m] ... p_n[x_1 ... x_m]))
               (and (forall (x_1 ... x_m) p_1[x_1 ... x_m])
                 ...
               (forall (x_1 ... x_m) p_n[x_1 ... x_m])))
This proof object has no antecedents.
Z3_OP_PR_ELIM_UNUSED_VARS: A proof for (iff (forall (x_1 ... x_n y_1 ... y_m) p[x_1 ... x_n]) (forall (x_1 ... x_n) p[x_1 ... x_n]))
It is used to justify the elimination of unused variables. This proof object has no antecedents.
Z3_OP_PR_DER: A proof for destructive equality resolution: (iff (forall (x) (or (not (= x t)) P[x])) P[t]) if x does not occur in t.
This proof object has no antecedents.
Several variables can be eliminated simultaneously.
Z3_OP_PR_QUANT_INST: A proof of (or (not (forall (x) (P x))) (P a))
Z3_OP_PR_HYPOTHESIS: Mark a hypothesis in a natural deduction style proof.
Z3_OP_PR_LEMMA:
          T1: false
          [lemma T1]: (or (not l_1) ... (not l_n))
This proof object has one antecedent: a hypothetical proof for false. It converts the proof in a proof for (or (not l_1) ... (not l_n)), when T1 contains the hypotheses: l_1, ..., l_n.
Z3_OP_PR_UNIT_RESOLUTION:
          T1:      (or l_1 ... l_n l_1' ... l_m')
          T2:      (not l_1)
          ...
          T(n+1):  (not l_n)
          [unit-resolution T1 ... T(n+1)]: (or l_1' ... l_m')
Z3_OP_PR_IFF_TRUE:
       T1: p
       [iff-true T1]: (iff p true)
Z3_OP_PR_IFF_FALSE:
       T1: (not p)
       [iff-false T1]: (iff p false)
Z3_OP_PR_COMMUTATIVITY:
[comm]: (= (f a b) (f b a))
f is a commutative operator.
This proof object has no antecedents. Remark: if f is bool, then = is iff.
Z3_OP_PR_DEF_AXIOM: Proof object used to justify Tseitin's like axioms:
          (or (not (and p q)) p)
          (or (not (and p q)) q)
          (or (not (and p q r)) p)
          (or (not (and p q r)) q)
          (or (not (and p q r)) r)
          ...
          (or (and p q) (not p) (not q))
          (or (not (or p q)) p q)
          (or (or p q) (not p))
          (or (or p q) (not q))
          (or (not (iff p q)) (not p) q)
          (or (not (iff p q)) p (not q))
          (or (iff p q) (not p) (not q))
          (or (iff p q) p q)
          (or (not (ite a b c)) (not a) b)
          (or (not (ite a b c)) a c)
          (or (ite a b c) (not a) (not b))
          (or (ite a b c) a (not c))
          (or (not (not a)) (not a))
          (or (not a) a)
This proof object has no antecedents. Note: all axioms are propositional tautologies. Note also that 'and' and 'or' can take multiple arguments. You can recover the propositional tautologies by unfolding the Boolean connectives in the axioms a small bounded number of steps (=3).
Z3_OP_PR_DEF_INTRO: Introduces a name for a formula/term. Suppose e is an expression with free variables x, and def-intro introduces the name n(x). The possible cases are:
When e is of Boolean type: [def-intro]: (and (or n (not e)) (or (not n) e))
or: [def-intro]: (or (not n) e) when e only occurs positively.
When e is of the form (ite cond th el): [def-intro]: (and (or (not cond) (= n th)) (or cond (= n el)))
Otherwise: [def-intro]: (= n e)
Z3_OP_PR_APPLY_DEF: [apply-def T1]: F ~ n F is 'equivalent' to n, given that T1 is a proof that n is a name for F.
Z3_OP_PR_IFF_OEQ: T1: (iff p q) [iff~ T1]: (~ p q)
Z3_OP_PR_NNF_POS: Proof for a (positive) NNF step. Example:
          T1: (not s_1) ~ r_1
          T2: (not s_2) ~ r_2
          T3: s_1 ~ r_1'
          T4: s_2 ~ r_2'
          [nnf-pos T1 T2 T3 T4]: (~ (iff s_1 s_2)
                                    (and (or r_1 r_2') (or r_1' r_2)))
The negation normal form steps NNF_POS and NNF_NEG are used in the following cases: (a) When creating the NNF of a positive force quantifier. The quantifier is retained (unless the bound variables are eliminated). Example
           T1: q ~ q_new
           [nnf-pos T1]: (~ (forall (x T) q) (forall (x T) q_new))
(b) When recursively creating NNF over Boolean formulas, where the top-level connective is changed during NNF conversion. The relevant Boolean connectives for NNF_POS are 'implies', 'iff', 'xor', 'ite'. NNF_NEG furthermore handles the case where negation is pushed over Boolean connectives 'and' and 'or'.
Z3_OP_PR_NFF_NEG: Proof for a (negative) NNF step. Examples:
          T1: (not s_1) ~ r_1
          ...
          Tn: (not s_n) ~ r_n
         [nnf-neg T1 ... Tn]: (not (and s_1 ... s_n)) ~ (or r_1 ... r_n)
      and
          T1: (not s_1) ~ r_1
          ...
          Tn: (not s_n) ~ r_n
         [nnf-neg T1 ... Tn]: (not (or s_1 ... s_n)) ~ (and r_1 ... r_n)
      and
          T1: (not s_1) ~ r_1
          T2: (not s_2) ~ r_2
          T3: s_1 ~ r_1'
          T4: s_2 ~ r_2'
         [nnf-neg T1 T2 T3 T4]: (~ (not (iff s_1 s_2))
                                   (and (or r_1 r_2) (or r_1' r_2')))
Z3_OP_PR_NNF_STAR: A proof for (~ P Q) where Q is in negation normal form.
This proof object is only used if the parameter PROOF_MODE is 1.
This proof object may have n antecedents. Each antecedent is a PR_DEF_INTRO.
Z3_OP_PR_CNF_STAR: A proof for (~ P Q) where Q is in conjunctive normal form. This proof object is only used if the parameter PROOF_MODE is 1. This proof object may have n antecedents. Each antecedent is a PR_DEF_INTRO.
Z3_OP_PR_SKOLEMIZE: Proof for:
          [sk]: (~ (not (forall x (p x y))) (not (p (sk y) y)))
          [sk]: (~ (exists x (p x y)) (p (sk y) y))
This proof object has no antecedents.
Z3_OP_PR_MODUS_PONENS_OEQ: Modus ponens style rule for equi-satisfiability.
          T1: p
          T2: (~ p q)
          [mp~ T1 T2]: q
Z3_OP_PR_TH_LEMMA: Generic proof for theory lemmas.
The theory lemma function comes with one or more parameters. The first parameter indicates the name of the theory. For the theory of arithmetic, additional parameters provide hints for checking the theory lemma. The hints for arithmetic are:
farkas - followed by rational coefficients. Multiply the coefficients to the inequalities in the lemma, add the (negated) inequalities and obtain a contradiction.
triangle-eq - Indicates a lemma related to the equivalence:
            (iff (= t1 t2) (and (<= t1 t2) (<= t2 t1)))
gcd-test - Indicates an integer linear arithmetic lemma that uses a gcd test.
Z3_OP_RA_STORE: Insert a record into a relation. The function takes n+1 arguments, where the first argument is the relation and the remaining n elements correspond to the n columns of the relation.
Z3_OP_RA_EMPTY: Creates the empty relation.
Z3_OP_RA_IS_EMPTY: Tests if the relation is empty.
Z3_OP_RA_JOIN: Create the relational join.
Z3_OP_RA_UNION: Create the union or convex hull of two relations. The function takes two arguments.
Z3_OP_RA_WIDEN: Widen two relations. The function takes two arguments.
Z3_OP_RA_PROJECT: Project the columns (provided as numbers in the parameters). The function takes one argument.
Z3_OP_RA_FILTER: Filter (restrict) a relation with respect to a predicate. The first argument is a relation. The second argument is a predicate with free de-Brujin indices corresponding to the columns of the relation. So the first column in the relation has index 0.
Z3_OP_RA_NEGATION_FILTER: Intersect the first relation with respect to negation of the second relation (the function takes two arguments). Logically, the specification can be described by a function
target = filter_by_negation(pos, neg, columns)
where columns are pairs c1, d1, .., cN, dN of columns from pos and neg, such that target are elements in x in pos, such that there is no y in neg that agrees with x on the columns c1, d1, .., cN, dN.
Z3_OP_RA_RENAME: rename columns in the relation. The function takes one argument. The parameters contain the renaming as a cycle.
Z3_OP_RA_COMPLEMENT: Complement the relation.
Z3_OP_RA_SELECT: Check if a record is an element of the relation. The function takes n+1 arguments, where the first argument is a relation, and the remaining n arguments correspond to a record.
Z3_OP_RA_CLONE: Create a fresh copy (clone) of a relation. The function is logically the identity, but in the context of a register machine allows for Z3_OP_RA_UNION to perform destructive updates to the first argument.
Z3_OP_FD_LT: A less than predicate over the finite domain Z3_FINITE_DOMAIN_SORT.
Z3_OP_LABEL: A label (used by the Boogie Verification condition generator). The label has two parameters, a string and a Boolean polarity. It takes one argument, a formula.
Z3_OP_LABEL_LIT: A label literal (used by the Boogie Verification condition generator). A label literal has a set of string parameters. It takes no arguments.
Z3_OP_UNINTERPRETED: kind used for uninterpreted symbols.
Definition at line 828 of file z3_api.h.
             {
    Z3_OP_TRUE = 0x100,
    Z3_OP_FALSE,
    Z3_OP_EQ,
    Z3_OP_DISTINCT,
    Z3_OP_ITE,
    Z3_OP_AND,
    Z3_OP_OR,
    Z3_OP_IFF,
    Z3_OP_XOR,
    Z3_OP_NOT,
    Z3_OP_IMPLIES,
    Z3_OP_OEQ,
    Z3_OP_ANUM = 0x200,
    Z3_OP_AGNUM,
    Z3_OP_LE,
    Z3_OP_GE,
    Z3_OP_LT,
    Z3_OP_GT,
    Z3_OP_ADD,
    Z3_OP_SUB,
    Z3_OP_UMINUS,
    Z3_OP_MUL,
    Z3_OP_DIV,
    Z3_OP_IDIV,
    Z3_OP_REM,
    Z3_OP_MOD,
    Z3_OP_TO_REAL,
    Z3_OP_TO_INT,
    Z3_OP_IS_INT,
    Z3_OP_POWER,
    Z3_OP_STORE = 0x300,
    Z3_OP_SELECT,
    Z3_OP_CONST_ARRAY,
    Z3_OP_ARRAY_MAP,
    Z3_OP_ARRAY_DEFAULT,
    Z3_OP_SET_UNION,
    Z3_OP_SET_INTERSECT,
    Z3_OP_SET_DIFFERENCE,
    Z3_OP_SET_COMPLEMENT,
    Z3_OP_SET_SUBSET,
    Z3_OP_AS_ARRAY,
    Z3_OP_BNUM = 0x400,
    Z3_OP_BIT1,
    Z3_OP_BIT0,
    Z3_OP_BNEG,
    Z3_OP_BADD,
    Z3_OP_BSUB,
    Z3_OP_BMUL,
    Z3_OP_BSDIV,
    Z3_OP_BUDIV,
    Z3_OP_BSREM,
    Z3_OP_BUREM,
    Z3_OP_BSMOD,
    // special functions to record the division by 0 cases
    // these are internal functions
    Z3_OP_BSDIV0,
    Z3_OP_BUDIV0,
    Z3_OP_BSREM0,
    Z3_OP_BUREM0,
    Z3_OP_BSMOD0,
    Z3_OP_ULEQ,
    Z3_OP_SLEQ,
    Z3_OP_UGEQ,
    Z3_OP_SGEQ,
    Z3_OP_ULT,
    Z3_OP_SLT,
    Z3_OP_UGT,
    Z3_OP_SGT,
    Z3_OP_BAND,
    Z3_OP_BOR,
    Z3_OP_BNOT,
    Z3_OP_BXOR,
    Z3_OP_BNAND,
    Z3_OP_BNOR,
    Z3_OP_BXNOR,
    Z3_OP_CONCAT,
    Z3_OP_SIGN_EXT,
    Z3_OP_ZERO_EXT,
    Z3_OP_EXTRACT,
    Z3_OP_REPEAT,
    Z3_OP_BREDOR,
    Z3_OP_BREDAND,
    Z3_OP_BCOMP,
    Z3_OP_BSHL,
    Z3_OP_BLSHR,
    Z3_OP_BASHR,
    Z3_OP_ROTATE_LEFT,
    Z3_OP_ROTATE_RIGHT,
    Z3_OP_EXT_ROTATE_LEFT,
    Z3_OP_EXT_ROTATE_RIGHT,
    Z3_OP_INT2BV,
    Z3_OP_BV2INT,
    Z3_OP_CARRY,
    Z3_OP_XOR3,
    Z3_OP_PR_UNDEF = 0x500,
    Z3_OP_PR_TRUE,
    Z3_OP_PR_ASSERTED,
    Z3_OP_PR_GOAL,
    Z3_OP_PR_MODUS_PONENS,
    Z3_OP_PR_REFLEXIVITY,
    Z3_OP_PR_SYMMETRY,
    Z3_OP_PR_TRANSITIVITY,
    Z3_OP_PR_TRANSITIVITY_STAR,
    Z3_OP_PR_MONOTONICITY,
    Z3_OP_PR_QUANT_INTRO,
    Z3_OP_PR_DISTRIBUTIVITY,
    Z3_OP_PR_AND_ELIM,
    Z3_OP_PR_NOT_OR_ELIM,
    Z3_OP_PR_REWRITE,
    Z3_OP_PR_REWRITE_STAR,
    Z3_OP_PR_PULL_QUANT,
    Z3_OP_PR_PULL_QUANT_STAR,
    Z3_OP_PR_PUSH_QUANT,
    Z3_OP_PR_ELIM_UNUSED_VARS,
    Z3_OP_PR_DER,
    Z3_OP_PR_QUANT_INST,
    Z3_OP_PR_HYPOTHESIS,
    Z3_OP_PR_LEMMA,
    Z3_OP_PR_UNIT_RESOLUTION,
    Z3_OP_PR_IFF_TRUE,
    Z3_OP_PR_IFF_FALSE,
    Z3_OP_PR_COMMUTATIVITY,
    Z3_OP_PR_DEF_AXIOM,
    Z3_OP_PR_DEF_INTRO,
    Z3_OP_PR_APPLY_DEF,
    Z3_OP_PR_IFF_OEQ,
    Z3_OP_PR_NNF_POS,
    Z3_OP_PR_NNF_NEG,
    Z3_OP_PR_NNF_STAR,
    Z3_OP_PR_CNF_STAR,
    Z3_OP_PR_SKOLEMIZE,
    Z3_OP_PR_MODUS_PONENS_OEQ,
    Z3_OP_PR_TH_LEMMA,
    Z3_OP_RA_STORE = 0x600,
    Z3_OP_RA_EMPTY,
    Z3_OP_RA_IS_EMPTY,
    Z3_OP_RA_JOIN,
    Z3_OP_RA_UNION,
    Z3_OP_RA_WIDEN,
    Z3_OP_RA_PROJECT,
    Z3_OP_RA_FILTER,
    Z3_OP_RA_NEGATION_FILTER,
    Z3_OP_RA_RENAME,
    Z3_OP_RA_COMPLEMENT,
    Z3_OP_RA_SELECT,
    Z3_OP_RA_CLONE,
    Z3_OP_FD_LT,
    Z3_OP_LABEL = 0x700,
    Z3_OP_LABEL_LIT,
    Z3_OP_UNINTERPRETED
} Z3_decl_kind;
enum Z3_error_code
Z3 error codes (See Z3_get_error_code).
Z3_OK,
Z3_SORT_ERROR: User tried to build an invalid (type incorrect) AST.
Z3_IOB: Index out of bounds
Z3_INVALID_ARG: Invalid argument was provided
Z3_PARSER_ERROR: An error occurred when parsing a string or file.
Z3_NO_PARSER: Parser output is not available, that is, user didn't invoke Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Z3_INVALID_PATTERN: Invalid pattern was used to build a quantifier.
Z3_MEMOUT_FAIL: A memory allocation failure was encountered.
Z3_FILE_ACCESS_ERRROR: A file could not be accessed.
Z3_INVALID_USAGE: API call is invalid in the current state.
Z3_INTERNAL_FATAL: An error internal to Z3 occurred.
Z3_DEC_REF_ERROR: Trying decrement the reference counter of an AST that was deleted or the reference counter was not initialized with Z3_inc_ref.
Definition at line 1008 of file z3_api.h.
{
    Z3_OK,
    Z3_SORT_ERROR,
    Z3_IOB,
    Z3_INVALID_ARG,
    Z3_PARSER_ERROR,
    Z3_NO_PARSER,
    Z3_INVALID_PATTERN,
    Z3_MEMOUT_FAIL,
    Z3_FILE_ACCESS_ERROR,
    Z3_INTERNAL_FATAL,
    Z3_INVALID_USAGE,
    Z3_DEC_REF_ERROR,
    Z3_EXCEPTION
} Z3_error_code;
enum Z3_error_code
Z3 error codes (See Z3_get_error_code).
Z3_OK: No error.
Z3_SORT_ERROR: User tried to build an invalid (type incorrect) AST.
Z3_IOB: Index out of bounds.
Z3_INVALID_ARG: Invalid argument was provided.
Z3_PARSER_ERROR: An error occurred when parsing a string or file.
Z3_NO_PARSER: Parser output is not available, that is, user didn't invoke Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Z3_INVALID_PATTERN: Invalid pattern was used to build a quantifier.
Z3_MEMOUT_FAIL: A memory allocation failure was encountered.
Z3_FILE_ACCESS_ERRROR: A file could not be accessed.
Z3_INVALID_USAGE: API call is invalid in the current state.
Z3_INTERNAL_FATAL: An error internal to Z3 occurred.
Z3_DEC_REF_ERROR: Trying to decrement the reference counter of an AST that was deleted or the reference counter was not initialized with Z3_inc_ref.
Z3_EXCEPTION: Internal Z3 exception. Additional details can be retrieved using Z3_get_error_msg_ex.
Definition at line 1060 of file z3_api.h.
{
    Z3_OK,
    Z3_SORT_ERROR,
    Z3_IOB,
    Z3_INVALID_ARG,
    Z3_PARSER_ERROR,
    Z3_NO_PARSER,
    Z3_INVALID_PATTERN,
    Z3_MEMOUT_FAIL,
    Z3_FILE_ACCESS_ERROR,
    Z3_INTERNAL_FATAL,
    Z3_INVALID_USAGE,
    Z3_DEC_REF_ERROR,
    Z3_EXCEPTION
} Z3_error_code;
enum Z3_goal_prec
A Goal is essentially a set of formulas. Z3 provide APIs for building strategies/tactics for solving and transforming Goals. Some of these transformations apply under/over approximations.
Z3_GOAL_PRECISE: Approximations/Relaxations were not applied on the goal (sat and unsat answers were preserved).
Z3_GOAL_UNDER: Goal is the product of a under-approximation (sat answers are preserved).
Z3_GOAL_OVER: Goal is the product of an over-approximation (unsat answers are preserved).
Z3_GOAL_UNDER_OVER: Goal is garbage (it is the produce of over and under approximations, sat and unsat answers are not preserved).
Definition at line 1042 of file z3_api.h.
{
    Z3_GOAL_PRECISE,
    Z3_GOAL_UNDER,
    Z3_GOAL_OVER,
    Z3_GOAL_UNDER_OVER
} Z3_goal_prec;
enum Z3_goal_prec
A Goal is essentially a set of formulas. Z3 provide APIs for building strategies/tactics for solving and transforming Goals. Some of these transformations apply under/over approximations.
Z3_GOAL_PRECISE: Approximations/Relaxations were not applied on the goal (sat and unsat answers were preserved).
Z3_GOAL_UNDER: Goal is the product of a under-approximation (sat answers are preserved).
Z3_GOAL_OVER: Goal is the product of an over-approximation (unsat answers are preserved).
Z3_GOAL_UNDER_OVER: Goal is garbage (it is the product of over- and under-approximations, sat and unsat answers are not preserved).
Definition at line 1101 of file z3_api.h.
{
    Z3_GOAL_PRECISE,
    Z3_GOAL_UNDER,
    Z3_GOAL_OVER,
    Z3_GOAL_UNDER_OVER
} Z3_goal_prec;
enum Z3_lbool
Lifted Boolean type: false, undefined, true.
Definition at line 94 of file z3_api.h.
{
    Z3_L_FALSE = -1,
    Z3_L_UNDEF,
    Z3_L_TRUE
} Z3_lbool;
enum Z3_lbool
Lifted Boolean type: false, undefined, true.
Definition at line 130 of file z3_api.h.
{
    Z3_L_FALSE = -1,
    Z3_L_UNDEF,
    Z3_L_TRUE
} Z3_lbool;
enum Z3_parameter_kind
The different kinds of parameters that can be associated with function symbols.
See also:
Z3_get_decl_num_parameters
Z3_get_decl_parameter_kind
Z3_PARAMETER_INT is used for integer parameters.
Z3_PARAMETER_DOUBLE is used for double parameters.
Z3_PARAMETER_RATIONAL is used for parameters that are rational numbers.
Z3_PARAMETER_SORT is used for sort parameters.
Z3_PARAMETER_AST is used for expression parameters.
Z3_PARAMETER_FUNC_DECL is used for function declaration parameters.
Definition at line 126 of file z3_api.h.
{
    Z3_PARAMETER_INT,
    Z3_PARAMETER_DOUBLE,
    Z3_PARAMETER_RATIONAL,
    Z3_PARAMETER_SYMBOL,
    Z3_PARAMETER_SORT,
    Z3_PARAMETER_AST,
    Z3_PARAMETER_FUNC_DECL,
} Z3_parameter_kind;
enum Z3_parameter_kind
The different kinds of parameters that can be associated with function symbols.
See also:
Z3_get_decl_num_parameters
Z3_get_decl_parameter_kind
Z3_PARAMETER_INT is used for integer parameters.
Z3_PARAMETER_DOUBLE is used for double parameters.
Z3_PARAMETER_RATIONAL is used for parameters that are rational numbers.
Z3_PARAMETER_SYMBOL is used for parameters that are symbols.
Z3_PARAMETER_SORT is used for sort parameters.
Z3_PARAMETER_AST is used for expression parameters.
Z3_PARAMETER_FUNC_DECL is used for function declaration parameters.
Definition at line 166 of file z3_api.h.
{
    Z3_PARAMETER_INT,
    Z3_PARAMETER_DOUBLE,
    Z3_PARAMETER_RATIONAL,
    Z3_PARAMETER_SYMBOL,
    Z3_PARAMETER_SORT,
    Z3_PARAMETER_AST,
    Z3_PARAMETER_FUNC_DECL,
} Z3_parameter_kind;
enum Z3_search_failure
The different kinds of search failure types.
Z3_NO_FAILURE: The last search was successful
Z3_UNKNOWN: Undocumented failure reason
Z3_TIMEOUT: Timeout
Z3_MEMOUT_WATERMAK: Search hit a memory high-watermak limit
Z3_CANCELED: External cancel flag was set
Z3_NUM_CONFLICTS: Maximum number of conflicts was reached
Z3_THEORY: Theory is incomplete
Z3_QUANTIFIERS: Logical context contains universal quantifiers
Definition at line 964 of file z3_api.h.
             {
    Z3_NO_FAILURE,
    Z3_UNKNOWN,
    Z3_TIMEOUT,
    Z3_MEMOUT_WATERMARK,
    Z3_CANCELED,
    Z3_NUM_CONFLICTS,
    Z3_THEORY,
    Z3_QUANTIFIERS
} Z3_search_failure;
enum Z3_search_failure
The different kinds of search failure types.
Z3_NO_FAILURE: The last search was successful
Z3_UNKNOWN: Undocumented failure reason
Z3_TIMEOUT: Timeout
Z3_MEMOUT_WATERMAK: Search hit a memory high-watermak limit
Z3_CANCELED: External cancel flag was set
Z3_NUM_CONFLICTS: Maximum number of conflicts was reached
Z3_THEORY: Theory is incomplete
Z3_QUANTIFIERS: Logical context contains universal quantifiers
Definition at line 1013 of file z3_api.h.
             {
    Z3_NO_FAILURE,
    Z3_UNKNOWN,
    Z3_TIMEOUT,
    Z3_MEMOUT_WATERMARK,
    Z3_CANCELED,
    Z3_NUM_CONFLICTS,
    Z3_THEORY,
    Z3_QUANTIFIERS
} Z3_search_failure;
enum Z3_sort_kind
The different kinds of Z3 types (See Z3_get_sort_kind).
Definition at line 140 of file z3_api.h.
{
    Z3_UNINTERPRETED_SORT,
    Z3_BOOL_SORT,
    Z3_INT_SORT,
    Z3_REAL_SORT,
    Z3_BV_SORT,
    Z3_ARRAY_SORT,
    Z3_DATATYPE_SORT,
    Z3_RELATION_SORT,
    Z3_FINITE_DOMAIN_SORT,
    Z3_UNKNOWN_SORT = 1000
} Z3_sort_kind;
enum Z3_sort_kind
The different kinds of Z3 types (See Z3_get_sort_kind).
Definition at line 181 of file z3_api.h.
{
    Z3_UNINTERPRETED_SORT,
    Z3_BOOL_SORT,
    Z3_INT_SORT,
    Z3_REAL_SORT,
    Z3_BV_SORT,
    Z3_ARRAY_SORT,
    Z3_DATATYPE_SORT,
    Z3_RELATION_SORT,
    Z3_FINITE_DOMAIN_SORT,
    Z3_UNKNOWN_SORT = 1000
} Z3_sort_kind;
enum Z3_symbol_kind
In Z3, a symbol can be represented using integers and strings (See Z3_get_symbol_kind).
See also:
Z3_mk_int_symbol
Z3_mk_string_symbol
Definition at line 107 of file z3_api.h.
{
    Z3_INT_SYMBOL,
    Z3_STRING_SYMBOL
} Z3_symbol_kind;
enum Z3_symbol_kind
The different kinds of symbol. In Z3, a symbol can be represented using integers and strings (See Z3_get_symbol_kind).
See also:
Z3_mk_int_symbol
Z3_mk_string_symbol
Definition at line 145 of file z3_api.h.
{
    Z3_INT_SYMBOL,
    Z3_STRING_SYMBOL
} Z3_symbol_kind;
Function Documentation
Z3_probe Z3_API Z3_and_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when p1 and p2 evaluates to true.
Remarks:
For probes, "true" is any value different from 0.
Z3_tactic Z3_API Z3_and_then_tactic (__in Z3_context c, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that applies t1 to a given goal and t2 to every subgoal produced by t1.
Z3_ast Z3_API Z3_app_to_ast (__in Z3_context c, __in Z3_app a)
Convert a Z3_app into Z3_ast. This is just type casting.
Convert a APP_AST into an AST. This is just type casting.
void Z3_API Z3_append_log (__in_z Z3_string string)
Append user-defined string to interaction log.
The interaction log is opened using Z3_open_log. It contains the formulas that are checked using Z3. You can use this command to append comments, for instance.
void Z3_API Z3_append_log (__in Z3_string string)
Append user-defined string to interaction log.
The interaction log is opened using Z3_open_log. It contains the formulas that are checked using Z3. You can use this command to append comments, for instance.
Z3_model Z3_API Z3_apply_result_convert_model (__in Z3_context c, __in Z3_apply_result r, __in unsigned i, __in Z3_model m)
Convert a model for the subgoal Z3_apply_result_get_subgoal(c, r, i) into a model for the original goal g. Where g is the goal used to create r using Z3_tactic_apply(c, t, g).
void Z3_API Z3_apply_result_dec_ref (__in Z3_context c, __in Z3_apply_result r)
Decrement the reference counter of the given Z3_apply_result object.
unsigned Z3_API Z3_apply_result_get_num_subgoals (__in Z3_context c, __in Z3_apply_result r)
Return the number of subgoals in the Z3_apply_result object returned by Z3_tactic_apply.
Z3_goal Z3_API Z3_apply_result_get_subgoal (__in Z3_context c, __in Z3_apply_result r, __in unsigned i)
Return one of the subgoals in the Z3_apply_result object returned by Z3_tactic_apply.
Precondition:
i < Z3_apply_result_get_num_subgoals(c, r)
void Z3_API Z3_apply_result_inc_ref (__in Z3_context c, __in Z3_apply_result r)
Increment the reference counter of the given Z3_apply_result object.
Z3_string Z3_API Z3_apply_result_to_string (__in Z3_context c, __in Z3_apply_result r)
Convert the Z3_apply_result object returned by Z3_tactic_apply into a string.
void Z3_API Z3_assert_cnstr (__in Z3_context c, __in Z3_ast a)
Assert a constraint into the logical context.
Assert a constraing into the logical context.
After one assertion, the logical context may become inconsistent.
The functions Z3_check or Z3_check_and_get_model should be used to check whether the logical context is consistent or not.
See also:
Z3_check
Z3_check_and_get_model
Deprecated:
Subsumed by Z3_solver_assert
After one assertion, the logical context may become inconsistent.
The functions Z3_check or Z3_check_and_get_model should be used to check whether the logical context is consistent or not.
See also:
Z3_check
Z3_check_and_get_model
Referenced by array_example2(), assert_comm_axiom(), assert_hard_constraints(), assert_inj_axiom(), assert_le_k(), assert_retractable_cnstr(), assert_soft_constraints(), bitvector_example2(), demorgan(), error_code_example1(), eval_example1(), find_model_example1(), find_model_example2(), fu_malik_maxsat_step(), get_implied_equalities_example(), model_display_example(), pa_theory_example2(), parser_example1(), parser_example2(), prove(), prove_example1(), prove_example2(), push_pop_example1(), quantifier_example1(), reference_counter_example(), simple_example2(), tst_at_most_one(), and unsat_core_and_proof_example().
Z3_bool Z3_API Z3_ast_map_contains (__in Z3_context c, __in Z3_ast_map m, __in Z3_ast k)
Return true if the map m contains the AST key k.
void Z3_API Z3_ast_map_dec_ref (__in Z3_context c, __in Z3_ast_map m)
Decrement the reference counter of the given AST map.
void Z3_API Z3_ast_map_erase (__in Z3_context c, __in Z3_ast_map m, __in Z3_ast k)
Erase a key from the map.
Z3_ast Z3_API Z3_ast_map_find (__in Z3_context c, __in Z3_ast_map m, __in Z3_ast k)
Return the value associated with the key k.
The procedure invokes the error handler if k is not in the map.
void Z3_API Z3_ast_map_inc_ref (__in Z3_context c, __in Z3_ast_map m)
Increment the reference counter of the given AST map.
void Z3_API Z3_ast_map_insert (__in Z3_context c, __in Z3_ast_map m, __in Z3_ast k, __in Z3_ast v)
Store/Replace a new key, value pair in the given map.
Z3_ast_vector Z3_API Z3_ast_map_keys (__in Z3_context c, __in Z3_ast_map m)
Return the keys stored in the given map.
void Z3_API Z3_ast_map_reset (__in Z3_context c, __in Z3_ast_map m)
Remove all keys from the given map.
unsigned Z3_API Z3_ast_map_size (__in Z3_context c, __in Z3_ast_map m)
Return the size of the given map.
Z3_string Z3_API Z3_ast_map_to_string (__in Z3_context c, __in Z3_ast_map m)
Convert the given map into a string.
Z3_string Z3_API Z3_ast_to_string (__in Z3_context c, __in Z3_ast a)
Convert the given AST node into a string.
Warning:
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_ast_to_string.
See also:
Z3_pattern_to_string
Z3_sort_to_string
Referenced by array_example1(), array_example2(), assert_comm_axiom(), assert_inj_axiom(), Compare(), display_eqc(), display_eqc_parents(), get_implied_equalities_example(), ite_example(), list_example(), mk_counter_circuit(), numeral_example(), pa_theory_example1(), parser_example1(), parser_example2(), parser_example3(), parser_example4(), PATh_final_check(), simple_example1(), smt2parser_example(), substitute_example(), substitute_vars_example(), Th_new_app(), Th_new_assignment(), Th_new_diseq(), Th_new_elem(), Th_new_relevant(), tree_example(), two_contexts_example1(), and unsat_core_and_proof_example().
void Z3_API Z3_ast_vector_dec_ref (__in Z3_context c, __in Z3_ast_vector v)
Decrement the reference counter of the given AST vector.
Z3_ast Z3_API Z3_ast_vector_get (__in Z3_context c, __in Z3_ast_vector v, __in unsigned i)
Return the AST at position i in the AST vector v.
Precondition:
i < Z3_ast_vector_size(c, v)
void Z3_API Z3_ast_vector_inc_ref (__in Z3_context c, __in Z3_ast_vector v)
Increment the reference counter of the given AST vector.
void Z3_API Z3_ast_vector_push (__in Z3_context c, __in Z3_ast_vector v, __in Z3_ast a)
Add the AST a in the end of the AST vector v. The size of v is increased by one.
void Z3_API Z3_ast_vector_resize (__in Z3_context c, __in Z3_ast_vector v, __in unsigned n)
Resize the AST vector v.
void Z3_API Z3_ast_vector_set (__in Z3_context c, __in Z3_ast_vector v, __in unsigned i, __in Z3_ast a)
Update position i of the AST vector v with the AST a.
Precondition:
i < Z3_ast_vector_size(c, v)
unsigned Z3_API Z3_ast_vector_size (__in Z3_context c, __in Z3_ast_vector v)
Return the size of the given AST vector.
Z3_string Z3_API Z3_ast_vector_to_string (__in Z3_context c, __in Z3_ast_vector v)
Convert AST vector into a string.
Z3_ast_vector Z3_API Z3_ast_vector_translate (__in Z3_context s, __in Z3_ast_vector v, __in Z3_context t)
Translate the AST vector v from context s into an AST vector in context t.
unsigned Z3_API Z3_asts_count (__in Z3_context c, __in Z3_asts asts)
Retrieve length of asts array.
Z3_ast Z3_API Z3_asts_get (__in Z3_context c, __in Z3_asts asts, __in unsigned index)
Access element of asts array at index.
Z3_string Z3_API Z3_benchmark_to_smtlib_string (__in Z3_context c, __in_z Z3_string name, __in_z Z3_string logic, __in_z Z3_string status, __in_z Z3_string attributes, __in unsigned num_assumptions, __in_ecount(num_assumptions) Z3_ast const assumptions[], __in Z3_ast formula)
Convert the given benchmark into SMT-LIB formatted string.
Warning:
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_benchmark_to_smtlib_string.
Parameters:
c - context.
name - name of benchmark. The argument is optional.
logic - the benchmark logic.
status - the status string (sat, unsat, or unknown)
attributes - other attributes, such as source, difficulty or category.
num_assumptions - number of assumptions.
assumptions - auxiliary assumptions.
formula - formula to be checked for consistency in conjunction with assumptions.
Z3_string Z3_API Z3_benchmark_to_smtlib_string (__in Z3_context c, __in Z3_string name, __in Z3_string logic, __in Z3_string status, __in Z3_string attributes, __in unsigned num_assumptions, __in_ecount(num_assumptions) Z3_ast const assumptions[], __in Z3_ast formula)
Convert the given benchmark into SMT-LIB formatted string.
Warning:
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_benchmark_to_smtlib_string.
Parameters:
c - context.
name - name of benchmark. The argument is optional.
logic - the benchmark logic.
status - the status string (sat, unsat, or unknown)
attributes - other attributes, such as source, difficulty or category.
num_assumptions - number of assumptions.
assumptions - auxiliary assumptions.
formula - formula to be checked for consistency in conjunction with assumptions.
void Z3_API Z3_block_literals (__in Z3_context c, __in Z3_literals lbls)
Block subsequent checks using the remaining enabled labels.
Deprecated:
This procedure is based on the old Solver API.
Z3_lbool Z3_API Z3_check (__in Z3_context c)
Check whether the given logical context is consistent or not.
The function Z3_check_and_get_model should be used when models are needed.
See also:
Z3_check_and_get_model
Deprecated:
Subsumed by Z3_solver_check
The function Z3_check_and_get_model should be used when models are needed.
See also:
Z3_check_and_get_model
Referenced by demorgan(), fu_malik_maxsat(), and naive_maxsat().
Z3_lbool Z3_API Z3_check_and_get_model (__in Z3_context c, __out Z3_model * m)
Check whether the given logical context is consistent or not.
If the logical context is not unsatisfiable (i.e., the return value is different from Z3_L_FALSE) and model construction is enabled (see Z3_mk_config), then a model is stored in m. Otherwise, the value NULL is stored in m.
The caller is responsible for deleting the model using the function Z3_del_model.
Remarks:
In constrast with the rest of the Z3 API, the reference counter of the model is incremented. This is to guarantee backward compatibility. In previous versions, models did not support reference counting.
Model construction must be enabled using configuration parameters (See, Z3_mk_config).
See also:
Z3_check
Z3_del_model
Deprecated:
Subsumed by Z3_solver_check
If the logical context is not unsatisfiable (i.e., the return value is different from Z3_L_FALSE) and model construction is enabled (see Z3_mk_config), then a model is stored in m. Otherwise, the value 0 is stored in m. The caller is responsible for deleting the model using the function Z3_del_model.
Remarks:
Model construction must be enabled using configuration parameters (See, Z3_mk_config).
See also:
Z3_check
Z3_del_model
Referenced by check(), check2(), error_code_example1(), eval_example1(), naive_maxsat(), prove(), and tst_at_most_one().
Z3_lbool Z3_API Z3_check_assumptions (__in Z3_context c, __in unsigned num_assumptions, __in_ecount(num_assumptions) Z3_ast const assumptions[], __out Z3_model * m, __out Z3_ast * proof, __inout unsigned * core_size, __inout_ecount(num_assumptions) Z3_ast core[])
Check whether the given logical context and optional assumptions is consistent or not.
If the logical context is not unsatisfiable (i.e., the return value is different from Z3_L_FALSE), a non-NULL model argument is passed in, and model construction is enabled (see Z3_mk_config), then a model is stored in m. Otherwise, m is left unchanged.
The caller is responsible for deleting the model using the function Z3_del_model.
Remarks:
If the model argument is non-NULL, then model construction must be enabled using configuration parameters (See, Z3_mk_config).
Parameters:
c logical context.
num_assumptions number of auxiliary assumptions.
assumptions array of auxiliary assumptions
m optional pointer to a model.
proof optional pointer to a proof term.
core_size size of unsatisfiable core.
core pointer to an array receiving unsatisfiable core. The unsatisfiable core is a subset of the assumptions, so the array has the same size as the assumptions. The core array is not populated if core_size is set to 0.
Precondition:
assumptions comprises of propositional literals. In other words, you cannot use compound formulas for assumptions, but should use propositional variables or negations of propositional variables.
Remarks:
In constrast with the rest of the Z3 API, the reference counter of the model is incremented. This is to guarantee backward compatibility. In previous versions, models did not support reference counting.
See also:
Z3_check
Z3_del_model
Deprecated:
Subsumed by Z3_solver_check_assumptions
If the logical context is not unsatisfiable (i.e., the return value is different from Z3_L_FALSE), a non-0 model argument is passed in, and model construction is enabled (see Z3_mk_config), then a model is stored in m. Otherwise, m is left unchanged. The caller is responsible for deleting the model using the function Z3_del_model.
Remarks:
If the model argument is non-0, then model construction must be enabled using configuration parameters (See, Z3_mk_config).
Parameters:
c logical context.
num_assumptions number of auxiliary assumptions.
assumptions array of auxiliary assumptions
m optional pointer to a model.
proof optional pointer to a proof term.
core_size size of unsatisfiable core.
core pointer to an array receiveing unsatisfiable core. The unsatisfiable core is a subset of the assumptions, so the array has the same size as the assumptions. The core array is not populated if core_size is set to 0.
Precondition:
assumptions comprises of propositional literals. In other words, you cannot use compound formulas for assumptions, but should use propositional variables or negations of propositional variables.
See also:
Z3_check
Z3_del_model
Referenced by ext_check(), fu_malik_maxsat_step(), and unsat_core_and_proof_example().
void Z3_API Z3_close_log ()
Close interaction log.
Z3_tactic Z3_API Z3_cond_tactic (__in Z3_context c, __in Z3_probe p, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that applies t1 to a given goal if the probe p evaluates to true, and t2 if p evaluates to false.
Z3_probe Z3_API Z3_const_probe (__in Z3_context x, __in double val)
Return a probe that always evaluates to val.
Z3_string Z3_API Z3_context_to_string (__in Z3_context c)
Convert the given logical context into a string.
This function is mainly used for debugging purposes. It displays the internal structure of a logical context.
Warning:
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_context_to_string.
Deprecated:
This method is obsolete. It just displays the internal representation of the global solver available for backward compatibility reasons.
This function is mainly used for debugging purposes. It displays the internal structure of a logical context.
Warning:
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_context_to_string.
Referenced by simple_example().
void Z3_API Z3_datalog_add_rule (__in Z3_context c, __in Z3_ast horn_rule, __in Z3_symbol name)
Add a universal Horn clause as a named rule. The horn_rule should be of the form:
           horn_rule ::= (forall (bound-vars) horn_rule)
                      |  (=> atoms horn_rule)
                      |  atom
void* Z3_API Z3_datalog_get_context (__in Z3_context c)
Retrieve the user-define state.
void Z3_API Z3_datalog_init (__in Z3_context c, __in void * state)
Initialize the context with a user-defined state.
void Z3_API Z3_datalog_parse_file (__in Z3_context c, Z3_string filename)
Parse a file in Datalog format and process the queries in it.
Z3_ast Z3_API Z3_datalog_query (__in Z3_context c, __in Z3_ast q)
Pose a query against the asserted rules.
The query returns a formula that encodes the set of satisfying instances for the query.
           query ::= (exists (bound-vars) query)
                 |  literals
void Z3_API Z3_datalog_register_relation (__in Z3_context c, __in Z3_func_decl f)
Register relation as Datalog defined. Datalog defined relations have least-fixedpoint semantics. For example, the relation is empty if it does not occur in a head or a fact.
void Z3_API Z3_datalog_set_predicate_representation (__in Z3_context c, __in Z3_func_decl f, __in unsigned num_relations, __in_ecount(num_relations) Z3_symbol const relation_kinds[])
Configure the predicate representation.
It sets the predicate to use a set of domains given by the list of symbols. The domains given by the list of symbols must belong to a set of built-in domains.
void Z3_API Z3_datalog_set_reduce_app_callback (__in Z3_context c, __in Z3_datalog_reduce_app_callback_fptr cb)
Register a callback for buildling terms based on the relational operators.
void Z3_API Z3_datalog_set_reduce_assign_callback (__in Z3_context c, __in Z3_datalog_reduce_assign_callback_fptr cb)
Register a callback to destructive updates.
Registers are identified with terms encoded as fresh constants,
void Z3_API Z3_dec_ref (__in Z3_context c, __in Z3_ast a)
Decrement the reference counter of the given AST. The context c should have been created using Z3_mk_context_rc. This function is a NOOP if c was created using Z3_mk_context.
Referenced by reference_counter_example().
void Z3_API Z3_del_asts (__in Z3_context c, __in Z3_asts asts)
Delete array of asts.
void Z3_API Z3_del_config (__in Z3_config c)
Delete the given configuration object.
See also:
Z3_mk_config
Referenced by demorgan(), error_code_example1(), error_code_example2(), get_implied_equalities_example(), mk_context(), mk_proof_context(), parser_example3(), parser_example5(), quantifier_example1(), and reference_counter_example().
void Z3_API Z3_del_constructor (__in Z3_context c, __in Z3_constructor constr)
Reclaim memory allocated to constructor.
Parameters:
c logical context.
constr constructor.
Referenced by binary_tree_example(), forest_example(), and tree_example().
void Z3_API Z3_del_constructor_list (__in Z3_context c, __in Z3_constructor_list clist)
Reclaim memory allocated for constructor list.
reclaim memory allocated for constructor list.
Each constructor inside the constructor list must be independently reclaimed using Z3_del_constructor.
Parameters:
c logical context.
clist constructor list container.
Referenced by forest_example().
void Z3_API Z3_del_context (__in Z3_context c)
Delete the given logical context.
See also:
Z3_mk_context
Z3_mk_config
Referenced by array_example1(), array_example2(), array_example3(), binary_tree_example(), bitvector_example1(), bitvector_example2(), del_ext_context(), demorgan(), enum_example(), error_code_example1(), error_code_example2(), eval_example1(), find_model_example1(), find_model_example2(), forest_example(), get_implied_equalities_example(), ite_example(), list_example(), model_display_example(), numeral_example(), pa_theory_example1(), pa_theory_example2(), parser_example1(), parser_example2(), parser_example3(), parser_example4(), parser_example5(), prove_example1(), prove_example2(), push_pop_example1(), quantifier_example1(), reference_counter_example(), simple_example(), simple_example1(), simple_example2(), smt2parser_example(), substitute_example(), substitute_vars_example(), tree_example(), tst_at_most_one(), tuple_example1(), two_contexts_example1(), and unsat_core_and_proof_example().
void Z3_API Z3_del_literals (__in Z3_context c, __in Z3_literals lbls)
Delete a labels context.
See also:
Z3_get_relevant_labels
Deprecated:
This procedure is based on the old Solver API.
See also:
Z3_get_relevant_labels
void Z3_API Z3_del_model (__in Z3_context c, __in Z3_model m)
Delete a model object.
See also:
Z3_check_and_get_model
Deprecated:
Subsumed by Z3_solver API
See also:
Z3_check_and_get_model
Referenced by check(), check2(), error_code_example1(), eval_example1(), ext_check(), naive_maxsat(), prove(), tst_at_most_one(), and unsat_core_and_proof_example().
void Z3_API Z3_disable_literal (__in Z3_context c, __in Z3_literals lbls, __in unsigned idx)
Disable label.
The disabled label is not going to be used when blocking the subsequent search.
See also:
Z3_block_literals
Deprecated:
This procedure is based on the old Solver API.
The disabled label is not going to be used when blocking the subsequent search.
See also:
Z3_block_literals
Z3_tactic Z3_API Z3_echo_probe (__in Z3_context c, __in Z3_probe val)
Return a tactic that just displays the value of the given probe in the standard output. This tactic should be used for debugging purposes only.
Z3_tactic Z3_API Z3_echo_tactic (__in Z3_context c, __in_z Z3_string msg)
Return a tactic that just displays the given message in the standard output. This tactic should be used for debugging purposes only.
Z3_probe Z3_API Z3_eq_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is equal to the value returned by p2.
Remarks:
For probes, "true" is any value different from 0.
Z3_bool Z3_API Z3_eval (__in Z3_context c, __in Z3_model m, __in Z3_ast t, __out Z3_ast * v)
Evaluate the AST node t in the given model. Return Z3_TRUE if succeeded, and store the result in v.
The evaluation may fail for the following reasons:
t contains a quantifier.
the model m is partial, that is, it doesn't have a complete interpretation for uninterpreted functions. That is, the option MODEL_PARTIAL=true was used.
t is type incorrect.
Deprecated:
Use Z3_model_eval
The evaluation may fail for the following reasons:
t contains a quantifier.
the model m is partial, that is, it doesn't have a complete interpretation for uninterpreted functions. That is, the option MODEL_PARTIAL=true was used.
t is type incorrect.
Referenced by display_model(), eval_example1(), and get_num_disabled_soft_constraints().
Z3_bool Z3_API Z3_eval_decl (__in Z3_context c, __in Z3_model m, __in Z3_func_decl d, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[], __out Z3_ast * v)
Evaluate declaration given values.
Provides direct way to evaluate declarations without going over terms.
Deprecated:
Consider using Z3_model_eval and Z3_substitute_vars
Provides direct way to evaluate declarations without going over terms.
Z3_bool Z3_API Z3_eval_func_decl (__in Z3_context c, __in Z3_model m, __in Z3_func_decl decl, __out Z3_ast * v)
Return the value of the given constant or function in the given model.
Deprecated:
Consider using Z3_model_eval or Z3_model_get_func_interp
Referenced by error_code_example1().
Z3_tactic Z3_API Z3_fail_if_not_decided_tactic (__in Z3_context c)
Return a tactic that fails if the goal is not trivially satisfiable (i.e., empty) or trivially unsatisfiable (i.e., contains false).
Z3_tactic Z3_API Z3_fail_if_tactic (__in Z3_context c, __in Z3_probe p)
Return a tactic that fails if the probe p evaluates to false.
Z3_tactic Z3_API Z3_fail_tactic (__in Z3_context c)
Return a tactic that always fails.
void Z3_API Z3_fixedpoint_add_fact (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_func_decl r, __in unsigned num_args, __in_ecount(num_args) unsigned args[])
Add a Database fact.
Parameters:
c - context
d - fixed point context
r - relation signature for the row.
num_args - number of columns for the given row.
args - array of the row elements.
The number of arguments num_args should be equal to the number of sorts in the domain of r. Each sort in the domain should be an integral (bit-vector, Boolean or or finite domain sort).
The call has the same effect as adding a rule where is applied to the arguments.
void Z3_API Z3_fixedpoint_add_rule (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_ast rule, __in Z3_symbol name)
Add a universal Horn clause as a named rule. The horn_rule should be of the form:
           horn_rule ::= (forall (bound-vars) horn_rule)
                      |  (=> atoms horn_rule)
                      |  atom
void Z3_API Z3_fixedpoint_assert (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_ast axiom)
Assert a constraint to the fixedpoint context.
The constraints are used as background axioms when the fixedpoint engine uses the PDR mode. They are ignored for standard Datalog mode.
void Z3_API Z3_fixedpoint_dec_ref (__in Z3_context c, __in Z3_fixedpoint d)
Decrement the reference counter of the given fixedpoint context.
Z3_ast Z3_API Z3_fixedpoint_get_answer (__in Z3_context c, __in Z3_fixedpoint d)
Retrieve a formula that encodes satisfying answers to the query.
When used in Datalog mode, the returned answer is a disjunction of conjuncts. Each conjunct encodes values of the bound variables of the query that are satisfied. In PDR mode, the returned answer is a single conjunction.
The previous call to Z3_fixedpoint_query must have returned Z3_L_TRUE.
Z3_string Z3_API Z3_fixedpoint_get_reason_unknown (__in Z3_context c, __in Z3_fixedpoint d)
Retrieve a string that describes the last status returned by Z3_fixedpoint_query.
Use this method when Z3_fixedpoint_query returns Z3_L_UNDEF.
Z3_stats Z3_API Z3_fixedpoint_get_statistics (__in Z3_context c, __in Z3_fixedpoint d)
Retrieve statistics information from the last call to Z3_fixedpoint_query.
void Z3_API Z3_fixedpoint_inc_ref (__in Z3_context c, __in Z3_fixedpoint d)
Increment the reference counter of the given fixedpoint context.
void Z3_API Z3_fixedpoint_init (__in Z3_context c, __in Z3_fixedpoint d, __in void * state)
Initialize the context with a user-defined state.
Z3_lbool Z3_API Z3_fixedpoint_query (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_ast query)
Pose a query against the asserted rules.
           query ::= (exists (bound-vars) query)
                 |  literals
query returns
Z3_L_FALSE if the query is unsatisfiable.
Z3_L_TRUE if the query is satisfiable. Obtain the answer by calling Z3_fixedpoint_get_answer.
Z3_L_UNDEF if the query was interrupted, timed out or otherwise failed.
Z3_lbool Z3_API Z3_fixedpoint_query_relations (__in Z3_context c, __in Z3_fixedpoint d, __in unsigned num_relations, __in_ecount(num_relations) Z3_func_decl const relations[])
Pose multiple queries against the asserted rules.
The queries are encoded as relations (function declarations).
query returns
Z3_L_FALSE if the query is unsatisfiable.
Z3_L_TRUE if the query is satisfiable. Obtain the answer by calling Z3_fixedpoint_get_answer.
Z3_L_UNDEF if the query was interrupted, timed out or otherwise failed.
void Z3_API Z3_fixedpoint_register_relation (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_func_decl f)
Register relation as Fixedpoint defined. Fixedpoint defined relations have least-fixedpoint semantics. For example, the relation is empty if it does not occur in a head or a fact.
void Z3_API Z3_fixedpoint_set_predicate_representation (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_func_decl f, __in unsigned num_relations, __in_ecount(num_relations) Z3_symbol const relation_kinds[])
Configure the predicate representation.
It sets the predicate to use a set of domains given by the list of symbols. The domains given by the list of symbols must belong to a set of built-in domains.
void Z3_API Z3_fixedpoint_set_reduce_app_callback (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_fixedpoint_reduce_app_callback_fptr cb)
Register a callback for buildling terms based on the relational operators.
void Z3_API Z3_fixedpoint_set_reduce_assign_callback (__in Z3_context c, __in Z3_fixedpoint d, __in Z3_fixedpoint_reduce_assign_callback_fptr cb)
Register a callback to destructive updates.
Registers are identified with terms encoded as fresh constants,
Z3_ast_vector Z3_API Z3_fixedpoint_simplify_rules (__in Z3_context c, __in Z3_fixedpoint f, __in unsigned num_rules, __in_ecount(num_rules) Z3_ast rules[], __in unsigned num_outputs, __in_ecount(num_outputs) Z3_func_decl outputs[])
Simplify rules into a set of new rules that are returned. The simplification routines apply inlining, quantifier elimination, and other algebraic simplifications.
Z3_string Z3_API Z3_fixedpoint_to_string (__in Z3_context c, __in Z3_fixedpoint f, __in unsigned num_queries, __in_ecount(num_queries) Z3_ast queries[])
Print the current rules and background axioms as a string.
Parameters:
c - context.
f - fixedpoint context.
num_queries - number of additional queries to print.
queries - additional queries.
Z3_string Z3_API Z3_fixpoint_benchmark_to_string (__in Z3_context c, __in unsigned num_axioms, __in_ecount(num_axioms) Z3_ast axioms[], __in unsigned num_rules, __in_ecount(num_rules) Z3_ast rules[], __in unsigned num_queries, __in_ecount(num_queries) Z3_ast queries[])
Convert a set of axioms, rules and queries to a benchmark in SMT-LIB2 + rules format. This routine can be used for dumping rules.
Z3_asts Z3_API Z3_fixpoint_simplify_rules (__in Z3_context c, __in unsigned num_rules, __in_ecount(num_rules) Z3_ast rules[], __in unsigned num_outputs, __in_ecount(num_outputs) Z3_func_decl outputs[])
Simplify rules into a set of new rules that are returned. The simplification routines apply inlining, quantifier elimination, and other algebraic simplifications.
Z3_ast Z3_API Z3_func_decl_to_ast (__in Z3_context c, __in Z3_func_decl f)
Convert a Z3_func_decl into Z3_ast. This is just type casting.
Convert a Z3_func_decl into Z3_ast. This is just type casting.
void Z3_API Z3_func_entry_dec_ref (__in Z3_context c, __in Z3_func_entry e)
Decrement the reference counter of the given Z3_func_entry object.
Z3_ast Z3_API Z3_func_entry_get_arg (__in Z3_context c, __in Z3_func_entry e, __in unsigned i)
Return an argument of a Z3_func_entry object.
Precondition:
i < Z3_func_entry_get_num_args(c, e)
See also:
Z3_func_interp_get_entry
unsigned Z3_API Z3_func_entry_get_num_args (__in Z3_context c, __in Z3_func_entry e)
Return the number of arguments in a Z3_func_entry object.
See also:
Z3_func_interp_get_entry
Z3_ast Z3_API Z3_func_entry_get_value (__in Z3_context c, __in Z3_func_entry e)
Return the value of this point.
A Z3_func_entry object represents an element in the finite map used to encode a function interpretation.
See also:
Z3_func_interp_get_entry
void Z3_API Z3_func_entry_inc_ref (__in Z3_context c, __in Z3_func_entry e)
Increment the reference counter of the given Z3_func_entry object.
void Z3_API Z3_func_interp_dec_ref (__in Z3_context c, __in Z3_func_interp f)
Decrement the reference counter of the given Z3_func_interp object.
unsigned Z3_API Z3_func_interp_get_arity (__in Z3_context c, __in Z3_func_interp f)
Return the arity (number of arguments) of the given function interpretation.
Z3_ast Z3_API Z3_func_interp_get_else (__in Z3_context c, __in Z3_func_interp f)
Return the 'else' value of the given function interpretation.
A function interpretation is represented as a finite map and an 'else' value. This procedure returns the 'else' value.
Z3_func_entry Z3_API Z3_func_interp_get_entry (__in Z3_context c, __in Z3_func_interp f, unsigned i)
Return a "point" of the given function intepretation. It represents the value of f in a particular point.
Precondition:
i < Z3_func_interp_get_num_entries(c, f)
See also:
Z3_func_interp_get_num_entries
unsigned Z3_API Z3_func_interp_get_num_entries (__in Z3_context c, __in Z3_func_interp f)
Return the number of entries in the given function interpretation.
A function interpretation is represented as a finite map and an 'else' value. Each entry in the finite map represents the value of a function given a set of arguments. This procedure return the number of element in the finite map of f.
void Z3_API Z3_func_interp_inc_ref (__in Z3_context c, __in Z3_func_interp f)
Increment the reference counter of the given Z3_func_interp object.
Z3_probe Z3_API Z3_ge_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than or equal to the value returned by p2.
Remarks:
For probes, "true" is any value different from 0.
Z3_ast Z3_API Z3_get_algebraic_number_lower (__in Z3_context c, __in Z3_ast a, __in unsigned precision)
Return a lower bound for the given real algebraic number. The interval isolating the number is smaller than 1/10^precision. The result is a numeral AST of sort Real.
Precondition:
Z3_is_algebraic_number(c, a)
Z3_ast Z3_API Z3_get_algebraic_number_upper (Z3_context c, Z3_ast a, unsigned precision)
Return a upper bound for the given real algebraic number. The interval isolating the number is smaller than 1/10^precision. The result is a numeral AST of sort Real.
Precondition:
Z3_is_algebraic_number(c, a)
Z3_ast Z3_API Z3_get_app_arg (__in Z3_context c, __in Z3_app a, __in unsigned i)
Return the i-th argument of the given application.
Precondition:
i < Z3_get_num_args(c, a)
Referenced by apply_compare_axiom_for_parents_of(), apply_unit_axiom_for_parents_of(), display_ast(), and PATh_final_check().
Z3_func_decl Z3_API Z3_get_app_decl (__in Z3_context c, __in Z3_app a)
Return the declaration of a constant or function application.
Referenced by apply_compare_axiom_for_parents_of(), apply_unit_axiom_for_parents_of(), Compare(), display_ast(), error_code_example1(), parser_example2(), and PATh_final_check().
unsigned Z3_API Z3_get_app_num_args (__in Z3_context c, __in Z3_app a)
Return the number of argument of an application. If t is an constant, then the number of arguments is 0.
Referenced by display_ast().
unsigned Z3_API Z3_get_arity (__in Z3_context c, __in Z3_func_decl d)
Alias for Z3_get_domain_size.
See also:
Z3_get_domain_size
Z3_sort Z3_API Z3_get_array_sort_domain (__in Z3_context c, __in Z3_sort t)
Return the domain of the given array sort.
Precondition:
Z3_get_sort_kind(c, t) == Z3_ARRAY_SORT
See also:
Z3_mk_array_sort
Z3_get_sort_kind
Referenced by array_example3(), and display_sort().
Z3_sort Z3_API Z3_get_array_sort_range (__in Z3_context c, __in Z3_sort t)
Return the range of the given array sort.
Precondition:
Z3_get_sort_kind(c, t) == Z3_ARRAY_SORT
See also:
Z3_mk_array_sort
Z3_get_sort_kind
Referenced by array_example3(), and display_sort().
void Z3_API Z3_get_array_value (__in Z3_context c, __in Z3_model m, __in Z3_ast v, __in unsigned num_entries, __inout_ecount(num_entries) Z3_ast indices[], __inout_ecount(num_entries) Z3_ast values[], __out Z3_ast * else_value)
An array values is represented as a dictionary plus a default (else) value. This function returns the array graph.
Precondition:
Z3_TRUE == Z3_is_array_value(c, v, &num_entries)
Deprecated:
Use Z3_func_interp objects and Z3_get_as_array_func_decl
Precondition:
Z3_TRUE == Z3_is_array_value(c, v, &num_entries)
Z3_func_decl Z3_API Z3_get_as_array_func_decl (__in Z3_context c, __in Z3_ast a)
Return the function declaration f associated with a (_ as_array f) node.
See also:
Z3_is_as_array
unsigned Z3_API Z3_get_ast_hash (__in Z3_context c, __in Z3_ast a)
Return a hash code for the given AST.
unsigned Z3_API Z3_get_ast_id (__in Z3_context c, Z3_ast t)
Return a unique identifier for t.
Z3_ast_kind Z3_API Z3_get_ast_kind (__in Z3_context c, __in Z3_ast a)
Return the kind of the given AST.
Referenced by display_ast().
Z3_lbool Z3_API Z3_get_bool_value (__in Z3_context c, __in Z3_ast a)
Return Z3_L_TRUE if a is true, Z3_L_FALSE if it is false, and Z3_L_UNDEF otherwise.
unsigned Z3_API Z3_get_bv_sort_size (__in Z3_context c, __in Z3_sort t)
Return the size of the given bit-vector sort.
Precondition:
Z3_get_sort_kind(c, t) == Z3_BV_SORT
See also:
Z3_mk_bv_sort
Z3_get_sort_kind
Referenced by display_sort().
Z3_ast Z3_API Z3_get_context_assignment (__in Z3_context c)
Extract satisfying assignment from context as a conjunction.
This function can be used for debugging purposes. It returns a conjunction of formulas that are assigned to true in the current context. This conjunction will contain not only the assertions that are set to true under the current assignment, but will also include additional literals if there has been a call to Z3_check or Z3_check_and_get_model.
Deprecated:
This method is based on the old solver API.
This function can be used for debugging purposes. It returns a conjunction of formulas that are assigned to true in the current context. This conjunction will contain not only the assertions that are set to true under the current assignment, but will also include additional literals if there has been a call to Z3_check or Z3_check_and_get_model.
Z3_func_decl Z3_API Z3_get_datatype_sort_constructor (__in Z3_context c, __in Z3_sort t, unsigned idx)
Return idx'th constructor.
Precondition:
Z3_get_sort_kind(t) == Z3_DATATYPE_SORT
idx < Z3_get_datatype_sort_num_constructors(c, t)
See also:
Z3_get_datatype_sort_num_constructors
Z3_get_datatype_sort_recognizer
Z3_get_datatype_sort_constructor_accessor
Z3_func_decl Z3_API Z3_get_datatype_sort_constructor_accessor (__in Z3_context c, __in Z3_sort t, unsigned idx_c, unsigned idx_a)
Return idx_a'th accessor for the idx_c'th constructor.
Precondition:
Z3_get_sort_kind(t) == Z3_DATATYPE_SORT
idx_c < Z3_get_datatype_sort_num_constructors(c, t)
idx_a < Z3_get_domain_size(c, Z3_get_datatype_sort_constructor(c, idx_c))
See also:
Z3_get_datatype_sort_num_constructors
Z3_get_datatype_sort_constructor
Z3_get_datatype_sort_recognizer
unsigned Z3_API Z3_get_datatype_sort_num_constructors (__in Z3_context c, __in Z3_sort t)
Return number of constructors for datatype.
Precondition:
Z3_get_sort_kind(t) == Z3_DATATYPE_SORT
See also:
Z3_get_datatype_sort_constructor
Z3_get_datatype_sort_recognizer
Z3_get_datatype_sort_constructor_accessor
Referenced by display_sort().
Z3_func_decl Z3_API Z3_get_datatype_sort_recognizer (__in Z3_context c, __in Z3_sort t, unsigned idx)
Return idx'th recognizer.
Precondition:
Z3_get_sort_kind(t) == Z3_DATATYPE_SORT
idx < Z3_get_datatype_sort_num_constructors(c, t)
See also:
Z3_get_datatype_sort_num_constructors
Z3_get_datatype_sort_constructor
Z3_get_datatype_sort_constructor_accessor
Z3_ast Z3_API Z3_get_decl_ast_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the expresson value associated with an expression parameter.
Precondition:
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_AST
double Z3_API Z3_get_decl_double_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the double value associated with an double parameter.
Precondition:
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_DOUBLE
Z3_func_decl Z3_API Z3_get_decl_func_decl_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the expresson value associated with an expression parameter.
Precondition:
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_FUNC_DECL
int Z3_API Z3_get_decl_int_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the integer value associated with an integer parameter.
Precondition:
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_INT
Z3_decl_kind Z3_API Z3_get_decl_kind (__in Z3_context c, __in Z3_func_decl d)
Return declaration kind corresponding to declaration.
Z3_symbol Z3_API Z3_get_decl_name (__in Z3_context c, __in Z3_func_decl d)
Return the constant declaration name as a symbol.
Referenced by Compare(), display_function_interpretations(), and display_model().
unsigned Z3_API Z3_get_decl_num_parameters (__in Z3_context c, __in Z3_func_decl d)
Return the number of parameters associated with a declaration.
Z3_parameter_kind Z3_API Z3_get_decl_parameter_kind (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the parameter type associated with a declaration.
Parameters:
c the context
d the function declaration
idx is the index of the named parameter it should be between 0 and the number of parameters.
Z3_string Z3_API Z3_get_decl_rational_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the rational value, as a string, associated with a rational parameter.
Precondition:
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_RATIONAL
Z3_sort Z3_API Z3_get_decl_sort_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the sort value associated with a sort parameter.
Precondition:
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_SORT
Z3_symbol Z3_API Z3_get_decl_symbol_parameter (__in Z3_context c, __in Z3_func_decl d, unsigned idx)
Return the double value associated with an double parameter.
Precondition:
Z3_get_decl_parameter_kind(c, d, idx) == Z3_PARAMETER_SYMBOL
Z3_ast Z3_API Z3_get_denominator (__in Z3_context c, __in Z3_ast a)
Return the denominator (as a numeral AST) of a numeral AST of sort Real.
Precondition:
Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST
Z3_sort Z3_API Z3_get_domain (__in Z3_context c, __in Z3_func_decl d, __in unsigned i)
Return the sort of the i-th parameter of the given function declaration.
Precondition:
i < Z3_get_domain_size(d)
See also:
Z3_get_domain_size
Referenced by assert_comm_axiom(), and assert_inj_axiom().
unsigned Z3_API Z3_get_domain_size (__in Z3_context c, __in Z3_func_decl d)
Return the number of parameters of the given declaration.
See also:
Z3_get_arity
Z3_get_domain_size
Referenced by assert_comm_axiom(), and assert_inj_axiom().
Z3_error_code Z3_API Z3_get_error_code (__in Z3_context c)
Return the error code for the last API call.
A call to a Z3 function may return a non Z3_OK error code, when it is not used correctly.
See also:
Z3_set_error_handler
Referenced by error_code_example1().
Z3_string Z3_API Z3_get_error_msg (__in Z3_error_code err)
Return a string describing the given error code.
Deprecated:
Use Z3_get_error_msg_ex instead.
This method has been deprecated, use Z3_get_error_msg_ex instead.
Referenced by error_code_example2(), and parser_example5().
Z3_string Z3_API Z3_get_error_msg_ex (__in Z3_context c, __in Z3_error_code err)
Return a string describing the given error code.
Z3_bool Z3_API Z3_get_finite_domain_sort_size (__in Z3_context c, __in Z3_sort s, __out unsigned __int64 * r)
Store the size of the sort in r. Return Z3_FALSE if the call failed.That is, Z3_get_sort_kind(s) == Z3_FINITE_DOMAIN_SORT.
Store the size of the sort in r. Return Z3_TRUE if the call succeeded. That is, Z3_get_sort_kind(s) == Z3_FINITE_DOMAIN_SORT.
unsigned Z3_API Z3_get_func_decl_id (__in Z3_context c, Z3_func_decl f)
Return a unique identifier for f.
Z3_literals Z3_API Z3_get_guessed_literals (__in Z3_context c)
Retrieve the set of literals that whose assignment were guess, but not propagated during the search.
See also:
Z3_del_literals
Z3_get_num_literals
Z3_get_label_symbol
Z3_get_literal
Deprecated:
This procedure is based on the old Solver API.
See also:
Z3_del_literals
Z3_get_num_literals
Z3_get_label_symbol
Z3_get_literal
Z3_lbool Z3_API Z3_get_implied_equalities (__in Z3_context c, __in unsigned num_terms, __in_ecount(num_terms) Z3_ast const terms[], __out_ecount(num_terms) unsigned class_ids[])
Retrieve congruence class representatives for terms.
The function can be used for relying on Z3 to identify equal terms under the current set of assumptions. The array of terms and array of class identifiers should have the same length. The class identifiers are numerals that are assigned to the same value for their corresponding terms if the current context forces the terms to be equal. You cannot deduce that terms corresponding to different numerals must be all different, (especially when using non-convex theories). All implied equalities are returned by this call. This means that two terms map to the same class identifier if and only if the current context implies that they are equal.
A side-effect of the function is a satisfiability check. The function return Z3_L_FALSE if the current assertions are not satisfiable.
See also:
Z3_check_and_get_model
Z3_check
Deprecated:
Subsumed by Z3_solver API
The function can be used for relying on Z3 to identify equal terms under the current set of assumptions. The array of terms and array of class identifiers should have the same length. The class identifiers are numerals that are assigned to the same value for their corresponding terms if the current context forces the terms to be equal. You cannot deduce that terms corresponding to different numerals must be all different, (especially when using non-convex theories). All implied equalities are returned by this call. This means that two terms map to the same class identifier if and only if the current context implies that they are equal.
A side-effect of the function is a satisfiability check. The function return Z3_L_FALSE if the current assertions are not satisfiable.
See also:
Z3_check_and_get_model
Z3_check
Referenced by get_implied_equalities_example().
unsigned Z3_API Z3_get_index_value (__in Z3_context c, __in Z3_ast a)
Return index of de-Brujin bound variable.
Precondition:
Z3_get_ast_kind(a) == Z3_VAR_AST
Referenced by RawContext::GetVarIndex().
Z3_symbol Z3_API Z3_get_label_symbol (__in Z3_context c, __in Z3_literals lbls, __in unsigned idx)
Retrieve label symbol at idx.
Deprecated:
This procedure is based on the old Solver API.
Z3_ast Z3_API Z3_get_literal (__in Z3_context c, __in Z3_literals lbls, __in unsigned idx)
Retrieve literal expression at idx.
Deprecated:
This procedure is based on the old Solver API.
Z3_func_decl Z3_API Z3_get_model_constant (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the i-th constant in the given model.
Precondition:
i < Z3_get_model_num_constants(c, m)
Deprecated:
use Z3_model_get_const_decl
Precondition:
i < Z3_get_model_num_constants(c, m)
See also:
Z3_eval
Referenced by display_model().
Z3_func_decl Z3_API Z3_get_model_func_decl (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the declaration of the i-th function in the given model.
Precondition:
i < Z3_get_model_num_funcs(c, m)
See also:
Z3_get_model_num_funcs
Deprecated:
use Z3_model_get_func_decl
Precondition:
i < Z3_get_model_num_funcs(c, m)
See also:
Z3_get_model_num_funcs
Referenced by display_function_interpretations().
Z3_ast Z3_API Z3_get_model_func_else (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the 'else' value of the i-th function interpretation in the given model.
A function interpretation is represented as a finite map and an 'else' value.
Precondition:
i < Z3_get_model_num_funcs(c, m)
See also:
Z3_get_model_num_funcs
Z3_get_model_func_num_entries
Z3_get_model_func_entry_num_args
Z3_get_model_func_entry_arg
Deprecated:
Use Z3_func_interp objects
A function interpretation is represented as a finite map and an 'else' value.
Precondition:
i < Z3_get_model_num_funcs(c, m)
See also:
Z3_get_model_num_funcs
Z3_get_model_func_num_entries
Z3_get_model_func_entry_num_args
Z3_get_model_func_entry_arg
Referenced by display_function_interpretations().
Z3_ast Z3_API Z3_get_model_func_entry_arg (__in Z3_context c, __in Z3_model m, __in unsigned i, __in unsigned j, __in unsigned k)
Return the k-th argument of the j-th entry of the i-th function interpretation in the given model.
A function interpretation is represented as a finite map and an 'else' value. This function returns the j-th entry of this map.
An entry represents the value of a function given a set of arguments. That is: it has the following format f(args[0],...,args[num_args - 1]) = val.
Precondition:
i < Z3_get_model_num_funcs(c, m)
j < Z3_get_model_func_num_entries(c, m, i)
k < Z3_get_model_func_entry_num_args(c, m, i, j)
See also:
Z3_get_model_num_funcs
Z3_get_model_func_num_entries
Z3_get_model_func_entry_num_args
Deprecated:
Use Z3_func_interp objects
A function interpretation is represented as a finite map and an 'else' value. This function returns the j-th entry of this map.
An entry represents the value of a function given a set of arguments. That is: it has the following format f(args[0],...,args[num_args - 1]) = val.
Precondition:
i < Z3_get_model_num_funcs(c, m)
j < Z3_get_model_func_num_entries(c, m, i)
k < Z3_get_model_func_entry_num_args(c, m, i, j)
See also:
Z3_get_model_num_funcs
Z3_get_model_func_num_entries
Z3_get_model_func_entry_num_args
Referenced by display_function_interpretations().
unsigned Z3_API Z3_get_model_func_entry_num_args (__in Z3_context c, __in Z3_model m, __in unsigned i, __in unsigned j)
Return the number of arguments of the j-th entry of the i-th function interpretation in the given model.
A function interpretation is represented as a finite map and an 'else' value. This function returns the j-th entry of this map.
An entry represents the value of a function given a set of arguments. That is: it has the following format f(args[0],...,args[num_args - 1]) = val.
Precondition:
i < Z3_get_model_num_funcs(c, m)
j < Z3_get_model_func_num_entries(c, m, i)
See also:
Z3_get_model_num_funcs
Z3_get_model_func_num_entries
Z3_get_model_func_entry_arg
Deprecated:
Use Z3_func_interp objects
A function interpretation is represented as a finite map and an 'else' value. This function returns the j-th entry of this map.
An entry represents the value of a function given a set of arguments. That is: it has the following format f(args[0],...,args[num_args - 1]) = val.
Precondition:
i < Z3_get_model_num_funcs(c, m)
j < Z3_get_model_func_num_entries(c, m, i)
See also:
Z3_get_model_num_funcs
Z3_get_model_func_num_entries
Z3_get_model_func_entry_arg
Referenced by display_function_interpretations().
Z3_ast Z3_API Z3_get_model_func_entry_value (__in Z3_context c, __in Z3_model m, __in unsigned i, __in unsigned j)
Return the return value of the j-th entry of the i-th function interpretation in the given model.
A function interpretation is represented as a finite map and an 'else' value. This function returns the j-th entry of this map.
An entry represents the value of a function given a set of arguments. That is: it has the following format f(args[0],...,args[num_args - 1]) = val.
Precondition:
i < Z3_get_model_num_funcs(c, m)
j < Z3_get_model_func_num_entries(c, m, i)
See also:
Z3_get_model_num_funcs
Z3_get_model_func_num_entries
Deprecated:
Use Z3_func_interp objects
A function interpretation is represented as a finite map and an 'else' value. This function returns the j-th entry of this map.
An entry represents the value of a function given a set of arguments. That is: it has the following format f(args[0],...,args[num_args - 1]) = val.
Precondition:
i < Z3_get_model_num_funcs(c, m)
j < Z3_get_model_func_num_entries(c, m, i)
See also:
Z3_get_model_num_funcs
Z3_get_model_func_num_entries
Referenced by display_function_interpretations().
unsigned Z3_API Z3_get_model_func_num_entries (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the number of entries of the i-th function interpretation in the given model.
A function interpretation is represented as a finite map and an 'else' value.
Precondition:
i < Z3_get_model_num_funcs(c, m)
See also:
Z3_get_model_num_funcs
Z3_get_model_func_else
Z3_get_model_func_entry_num_args
Z3_get_model_func_entry_arg
Deprecated:
Use Z3_func_interp objects
A function interpretation is represented as a finite map and an 'else' value.
Precondition:
i < Z3_get_model_num_funcs(c, m)
See also:
Z3_get_model_num_funcs
Z3_get_model_func_else
Z3_get_model_func_entry_num_args
Z3_get_model_func_entry_arg
Referenced by display_function_interpretations().
unsigned Z3_API Z3_get_model_num_constants (__in Z3_context c, __in Z3_model m)
Return the number of constants assigned by the given model.
See also:
Z3_get_model_constant
Deprecated:
use Z3_model_get_num_consts
See also:
Z3_get_model_constant
Referenced by display_model().
unsigned Z3_API Z3_get_model_num_funcs (__in Z3_context c, __in Z3_model m)
Return the number of function interpretations in the given model.
A function interpretation is represented as a finite map and an 'else' value. Each entry in the finite map represents the value of a function given a set of arguments.
Deprecated:
use Z3_model_get_num_funcs
A function interpretation is represented as a finite map and an 'else' value. Each entry in the finite map represents the value of a function given a set of arguments.
See also:
Z3_get_model_func_decl
Z3_get_model_func_else
Z3_get_model_func_num_entries
Z3_get_model_func_entry_num_args
Z3_get_model_func_entry_arg
Referenced by display_function_interpretations().
unsigned Z3_API Z3_get_num_literals (__in Z3_context c, __in Z3_literals lbls)
Retrieve the number of label symbols that were returned.
See also:
Z3_get_relevant_labels
Deprecated:
This procedure is based on the old Solver API.
See also:
Z3_get_relevant_labels
unsigned Z3_API Z3_get_num_probes (__in Z3_context c)
Return the number of builtin probes available in Z3.
unsigned Z3_API Z3_get_num_scopes (__in Z3_context c)
Retrieve the current scope level.
It retrieves the number of scopes that have been pushed, but not yet popped.
See also:
Z3_push
Z3_pop
Deprecated:
Subsumed by Z3_solver_get_num_scopes.
It retrieves the number of scopes that have been pushed, but not yet popped.
See also:
Z3_push
Z3_pop
Referenced by push_pop_example1().
unsigned Z3_API Z3_get_num_tactics (__in Z3_context c)
Return the number of builtin tactics available in Z3.
Z3_string Z3_API Z3_get_numeral_decimal_string (__in Z3_context c, __in Z3_ast a, __in unsigned precision)
Return numeral as a string in decimal notation. The result has at most precision decimal places.
Precondition:
Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST || Z3_is_algebraic_number(c, a)
Z3_bool Z3_API Z3_get_numeral_int (__in Z3_context c, __in Z3_ast v, __out int * i)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine int. Return Z3_TRUE if the call succeeded.
Precondition:
Z3_get_ast_kind(c, v) == Z3_NUMERAL_AST
See also:
Z3_get_numeral_string
Z3_bool Z3_API Z3_get_numeral_int64 (__in Z3_context c, __in Z3_ast v, __out __int64 * i)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine __int64 int. Return Z3_TRUE if the call succeeded.
Precondition:
Z3_get_ast_kind(c, v) == Z3_NUMERAL_AST
See also:
Z3_get_numeral_string
Z3_bool Z3_API Z3_get_numeral_rational_int64 (__in Z3_context c, __in Z3_ast v, __out __int64 * num, __out __int64 * den)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit as a rational number as machine __int64 int. Return Z3_TRUE if the call succeeded.
Similar to Z3_get_numeral_string, but only succeeds if the value can fit as a reational number as machine __int64 int. Return Z3_TRUE if the call succeeded.
Precondition:
Z3_get_ast_kind(c, v) == Z3_NUMERAL_AST
See also:
Z3_get_numeral_string
Z3_bool Z3_API Z3_get_numeral_small (__in Z3_context c, __in Z3_ast a, __out __int64 * num, __out __int64 * den)
Return numeral value, as a pair of 64 bit numbers if the representation fits.
Parameters:
c logical context.
a term.
num numerator.
den denominator.
Return Z3_TRUE if the numeral value fits in 64 bit numerals, Z3_FALSE otherwise.
Precondition:
Z3_get_ast_kind(a) == Z3_NUMERAL_AST
Z3_string Z3_API Z3_get_numeral_string (__in Z3_context c, __in Z3_ast a)
Return numeral value, as a string of a numeric constant term.
Precondition:
Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST
Referenced by display_ast(), and error_code_example1().
Z3_bool Z3_API Z3_get_numeral_uint (__in Z3_context c, __in Z3_ast v, __out unsigned * u)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine unsigned int. Return Z3_TRUE if the call succeeded.
Precondition:
Z3_get_ast_kind(c, v) == Z3_NUMERAL_AST
See also:
Z3_get_numeral_string
Z3_bool Z3_API Z3_get_numeral_uint64 (__in Z3_context c, __in Z3_ast v, __out unsigned __int64 * u)
Similar to Z3_get_numeral_string, but only succeeds if the value can fit in a machine unsigned __int64 int. Return Z3_TRUE if the call succeeded.
Precondition:
Z3_get_ast_kind(c, v) == Z3_NUMERAL_AST
See also:
Z3_get_numeral_string
Z3_ast Z3_API Z3_get_numerator (__in Z3_context c, __in Z3_ast a)
Return the numerator (as a numeral AST) of a numeral AST of sort Real.
Precondition:
Z3_get_ast_kind(c, a) == Z3_NUMERAL_AST
Z3_bool Z3_API Z3_get_param_value (__in Z3_context c, __in_z Z3_string param_id, __out_z Z3_string_ptr param_value)
Get a configuration parameter.
Returns false if the parameter value does not exist.
See also:
Z3_mk_config
Z3_set_param_value
Z3_bool Z3_API Z3_get_param_value (__in Z3_context c, __in Z3_string param_id, __out Z3_string_ptr param_value)
Get a configuration parameter.
Returns Z3_FALSE if the parameter value does not exist.
See also:
Z3_mk_config
Z3_set_param_value
Z3_ast Z3_API Z3_get_pattern (__in Z3_context c, __in Z3_pattern p, __in unsigned idx)
Return i'th ast in pattern.
unsigned Z3_API Z3_get_pattern_num_terms (__in Z3_context c, __in Z3_pattern p)
Return number of terms in pattern.
Z3_string Z3_API Z3_get_probe_help (__in Z3_context c, __in_z Z3_string name)
Return a string containing a description of the probe with the given name.
Z3_string Z3_API Z3_get_probe_name (__in Z3_context c, unsigned i)
Return the name of the i probe.
Precondition:
i < Z3_get_num_probes(c)
Z3_ast Z3_API Z3_get_quantifier_body (__in Z3_context c, __in Z3_ast a)
Return body of quantifier.
Precondition:
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Z3_symbol Z3_API Z3_get_quantifier_bound_name (__in Z3_context c, __in Z3_ast a, unsigned i)
Return symbol of the i'th bound variable.
Precondition:
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Z3_sort Z3_API Z3_get_quantifier_bound_sort (__in Z3_context c, __in Z3_ast a, unsigned i)
Return sort of the i'th bound variable.
Precondition:
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Z3_ast Z3_API Z3_get_quantifier_no_pattern_ast (__in Z3_context c, __in Z3_ast a, unsigned i)
Return i'th no_pattern.
Precondition:
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
unsigned Z3_API Z3_get_quantifier_num_bound (__in Z3_context c, __in Z3_ast a)
Return number of bound variables of quantifier.
Precondition:
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
unsigned Z3_API Z3_get_quantifier_num_no_patterns (__in Z3_context c, __in Z3_ast a)
Return number of no_patterns used in quantifier.
Precondition:
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
unsigned Z3_API Z3_get_quantifier_num_patterns (__in Z3_context c, __in Z3_ast a)
Return number of patterns used in quantifier.
Precondition:
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Z3_pattern Z3_API Z3_get_quantifier_pattern_ast (__in Z3_context c, __in Z3_ast a, unsigned i)
Return i'th pattern.
Precondition:
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
unsigned Z3_API Z3_get_quantifier_weight (__in Z3_context c, __in Z3_ast a)
Obtain weight of quantifier.
Precondition:
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Z3_sort Z3_API Z3_get_range (__in Z3_context c, __in Z3_func_decl d)
Return the range of the given declaration.
If d is a constant (i.e., has zero arguments), then this function returns the sort of the constant.
Referenced by assert_comm_axiom(), assert_inj_axiom(), and display_sort().
unsigned Z3_API Z3_get_relation_arity (__in Z3_context c, __in Z3_sort s)
Return arity of relation.
Precondition:
Z3_get_sort_kind(s) == Z3_RELATION_SORT
See also:
Z3_get_relation_column
Z3_sort Z3_API Z3_get_relation_column (__in Z3_context c, __in Z3_sort s, unsigned col)
Return sort at i'th column of relation sort.
Precondition:
Z3_get_sort_kind(c, s) == Z3_RELATION_SORT
col < Z3_get_relation_arity(c, s)
See also:
Z3_get_relation_arity
Z3_literals Z3_API Z3_get_relevant_labels (__in Z3_context c)
Retrieve the set of labels that were relevant in the context of the current satisfied context.
See also:
Z3_del_literals
Z3_get_num_literals
Z3_get_label_symbol
Z3_get_literal
Deprecated:
This procedure is based on the old Solver API.
See also:
Z3_del_literals
Z3_get_num_literals
Z3_get_label_symbol
Z3_get_literal
Z3_literals Z3_API Z3_get_relevant_literals (__in Z3_context c)
Retrieve the set of literals that satisfy the current context.
See also:
Z3_del_literals
Z3_get_num_literals
Z3_get_label_symbol
Z3_get_literal
Deprecated:
This procedure is based on the old Solver API.
See also:
Z3_del_literals
Z3_get_num_literals
Z3_get_label_symbol
Z3_get_literal
Z3_search_failure Z3_API Z3_get_search_failure (__in Z3_context c)
Retrieve reason for search failure.
If a call to Z3_check or Z3_check_and_get_model returns Z3_L_UNDEF, use this facility to determine the more detailed cause of search failure.
Deprecated:
Subsumed by Z3_solver_get_reason_unknown
If a call to Z3_check or Z3_check_and_get_model returns Z3_L_UNDEF, use this facility to determine the more detailed cause of search failure.
Referenced by quantifier_example1().
Z3_ast Z3_API Z3_get_smtlib_assumption (__in Z3_context c, __in unsigned i)
Return the i-th assumption parsed by the last call to Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Precondition:
i < Z3_get_smtlib_num_assumptions(c)
Referenced by get_soft_constraints(), and parser_example4().
Z3_func_decl Z3_API Z3_get_smtlib_decl (__in Z3_context c, __in unsigned i)
Return the i-th declaration parsed by the last call to Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Precondition:
i < Z3_get_smtlib_num_decls(c)
Referenced by parser_example4().
Z3_string Z3_API Z3_get_smtlib_error (__in Z3_context c)
Retrieve that last error message information generated from parsing.
Referenced by parser_example5().
Z3_ast Z3_API Z3_get_smtlib_formula (__in Z3_context c, __in unsigned i)
Return the i-th formula parsed by the last call to Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Precondition:
i < Z3_get_smtlib_num_formulas(c)
Referenced by assert_comm_axiom(), get_hard_constraints(), parser_example1(), parser_example2(), parser_example3(), and parser_example4().
unsigned Z3_API Z3_get_smtlib_num_assumptions (__in Z3_context c)
Return the number of SMTLIB assumptions parsed by Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Referenced by get_soft_constraints(), and parser_example4().
unsigned Z3_API Z3_get_smtlib_num_decls (__in Z3_context c)
Return the number of declarations parsed by Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Referenced by parser_example4().
unsigned Z3_API Z3_get_smtlib_num_formulas (__in Z3_context c)
Return the number of SMTLIB formulas parsed by the last call to Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Referenced by get_hard_constraints(), parser_example1(), and parser_example4().
unsigned Z3_API Z3_get_smtlib_num_sorts (__in Z3_context c)
Return the number of sorts parsed by Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Z3_sort Z3_API Z3_get_smtlib_sort (__in Z3_context c, __in unsigned i)
Return the i-th sort parsed by the last call to Z3_parse_smtlib_string or Z3_parse_smtlib_file.
Precondition:
i < Z3_get_smtlib_num_sorts(c)
Z3_sort Z3_API Z3_get_sort (__in Z3_context c, __in Z3_ast a)
Return the sort of an AST node.
The AST node must be a constant, application, numeral, bound variable, or quantifier.
Referenced by display_ast(), and mk_tuple_update().
unsigned Z3_API Z3_get_sort_id (__in Z3_context c, Z3_sort s)
Return a unique identifier for s.
Z3_sort_kind Z3_API Z3_get_sort_kind (__in Z3_context c, __in Z3_sort t)
Return the sort kind (e.g., array, tuple, int, bool, etc).
See also:
Z3_sort_kind
Referenced by array_example3(), display_sort(), and mk_tuple_update().
Z3_symbol Z3_API Z3_get_sort_name (__in Z3_context c, __in Z3_sort d)
Return the sort name as a symbol.
Referenced by display_sort().
int Z3_API Z3_get_symbol_int (__in Z3_context c, __in Z3_symbol s)
Return the symbol int value.
Precondition:
Z3_get_symbol_kind(s) == Z3_INT_SYMBOL
See also:
Z3_mk_int_symbol
Referenced by display_symbol().
Z3_symbol_kind Z3_API Z3_get_symbol_kind (__in Z3_context c, __in Z3_symbol s)
Return Z3_INT_SYMBOL if the symbol was constructed using Z3_mk_int_symbol, and Z3_STRING_SYMBOL if the symbol was constructed using Z3_mk_string_symbol.
Referenced by display_symbol().
Z3_string Z3_API Z3_get_symbol_string (__in Z3_context c, __in Z3_symbol s)
Return the symbol name.
Precondition:
Z3_get_symbol_string(s) == Z3_STRING_SYMBOL
Warning:
The returned buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_get_symbol_string.
See also:
Z3_mk_string_symbol
Referenced by Compare(), and display_symbol().
Z3_string Z3_API Z3_get_tactic_help (__in Z3_context c, __in_z Z3_string name)
Return a string containing a description of the tactic with the given name.
Z3_string Z3_API Z3_get_tactic_name (__in Z3_context c, unsigned i)
Return the name of the idx tactic.
Precondition:
i < Z3_get_num_tactics(c)
Z3_func_decl Z3_API Z3_get_tuple_sort_field_decl (__in Z3_context c, __in Z3_sort t, __in unsigned i)
Return the i-th field declaration (i.e., projection function declaration) of the given tuple sort.
Precondition:
Z3_get_sort_kind(t) == Z3_DATATYPE_SORT
i < Z3_get_tuple_sort_num_fields(c, t)
See also:
Z3_mk_tuple_sort
Z3_get_sort_kind
Referenced by display_sort(), and mk_tuple_update().
Z3_func_decl Z3_API Z3_get_tuple_sort_mk_decl (__in Z3_context c, __in Z3_sort t)
Return the constructor declaration of the given tuple sort.
Precondition:
Z3_get_sort_kind(c, t) == Z3_DATATYPE_SORT
See also:
Z3_mk_tuple_sort
Z3_get_sort_kind
Referenced by mk_tuple_update().
unsigned Z3_API Z3_get_tuple_sort_num_fields (__in Z3_context c, __in Z3_sort t)
Return the number of fields of the given tuple sort.
Precondition:
Z3_get_sort_kind(c, t) == Z3_DATATYPE_SORT
See also:
Z3_mk_tuple_sort
Z3_get_sort_kind
Referenced by display_sort(), and mk_tuple_update().
void Z3_API Z3_get_version (__out unsigned * major, __out unsigned * minor, __out unsigned * build_number, __out unsigned * revision_number)
Return Z3 version number information.
Referenced by display_version().
void Z3_API Z3_goal_assert (__in Z3_context c, __in Z3_goal g, __in Z3_ast a)
Add a new formula a to the given goal.
Add a new formula a to the given goal. The formula will not be tracked during unsat core generation. The procedure Z3_goal_assert_ex should be used if a should be tracked during unsat core generation.
void Z3_API Z3_goal_assert_ex (__in Z3_context c, __in Z3_goal g, __in Z3_ast a)
Similar to Z3_goal_assert, but the given formula is tracked during unsat core generation. Unsat core generation must have been enabled when the given goal was created.
void Z3_API Z3_goal_dec_ref (__in Z3_context c, __in Z3_goal g)
Decrement the reference counter of the given goal.
unsigned Z3_API Z3_goal_depth (__in Z3_context c, __in Z3_goal g)
Return the depth of the given goal. It tracks how many transformations were applied to it.
Z3_ast Z3_API Z3_goal_formula (__in Z3_context c, __in Z3_goal g, __in unsigned idx)
Return a formula from the given goal.
Return a formula form the given goal.
Precondition:
idx < Z3_goal_size(c, g)
void Z3_API Z3_goal_inc_ref (__in Z3_context c, __in Z3_goal g)
Increment the reference counter of the given goal.
Z3_bool Z3_API Z3_goal_inconsistent (__in Z3_context c, __in Z3_goal g)
Return true if the given goal contains the formula false.
Z3_bool Z3_API Z3_goal_is_decided_sat (__in Z3_context c, __in Z3_goal g)
Return true if the goal is empty, and it is precise or the product of a under approximation.
Z3_bool Z3_API Z3_goal_is_decided_unsat (__in Z3_context c, __in Z3_goal g)
Return true if the goal contains false, and it is precise or the product of an over approximation.
unsigned Z3_API Z3_goal_num_exprs (__in Z3_context c, __in Z3_goal g)
Return the number of formulas, subformulas and terms in the given goal.
Z3_goal_prec Z3_API Z3_goal_precision (__in Z3_context c, __in Z3_goal g)
Return the "precision" of the given goal. Goals can be transformed using over and under approximations. A under approximation is applied when the objective is to find a model for a given goal. An over approximation is applied when the objective is to find a proof for a given goal.
void Z3_API Z3_goal_reset (__in Z3_context c, __in Z3_goal g)
Erase all formulas from the given goal.
unsigned Z3_API Z3_goal_size (__in Z3_context c, __in Z3_goal g)
Return the number of formulas in the given goal.
Z3_string Z3_API Z3_goal_to_string (__in Z3_context c, __in Z3_goal g)
Convert a goal into a string.
Z3_goal Z3_API Z3_goal_translate (__in Z3_context source, __in Z3_goal g, __in Z3_context target)
Copy a goal g from the context source to a the context target.
Z3_probe Z3_API Z3_gt_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than the value returned by p2.
Remarks:
For probes, "true" is any value different from 0.
void Z3_API Z3_inc_ref (__in Z3_context c, __in Z3_ast a)
Increment the reference counter of the given AST. The context c should have been created using Z3_mk_context_rc. This function is a NOOP if c was created using Z3_mk_context.
Referenced by reference_counter_example().
void Z3_API Z3_interrupt (__in Z3_context c)
Interrupt the execution of a Z3 procedure. This procedure can be used to interrupt: solvers, simplifiers and tactics.
Z3_bool Z3_API Z3_is_algebraic_number (__in Z3_context c, __in Z3_ast a)
Return true if the give AST is a real algebraic number.
Z3_bool Z3_API Z3_is_array_value (__in Z3_context c, __in Z3_model m, __in Z3_ast v, __out unsigned * num_entries)
Determine whether the term encodes an array value. A term encodes an array value if it is a nested sequence of applications of store on top of a constant array. The indices to the stores have to be values (for example, integer constants) so that equality between the indices can be evaluated. Array values are useful for representing interpretations for arrays.
Return the number of entries mapping to non-default values of the array.
Deprecated:
Use Z3_is_as_array
Return the number of entries mapping to non-default values of the array.
Z3_bool Z3_API Z3_is_as_array (__in Z3_context c, __in Z3_ast a)
The (_ as-array f) AST node is a construct for assigning interpretations for arrays in Z3. It is the array such that forall indices i we have that (select (_ as-array f) i) is equal to (f i). This procedure returns Z3_TRUE if the a is an as-array AST node.
Z3 current solvers have minimal support for as_array nodes.
See also:
Z3_get_as_array_func_decl
Z3_bool Z3_API Z3_is_eq_ast (__in Z3_context c, __in Z3_ast t1, Z3_ast t2)
compare terms.
Referenced by get_num_disabled_soft_constraints().
Z3_bool Z3_API Z3_is_eq_func_decl (__in Z3_context c, __in Z3_func_decl f1, Z3_func_decl f2)
compare terms.
Z3_bool Z3_API Z3_is_eq_sort (__in Z3_context c, __in Z3_sort s1, __in Z3_sort s2)
compare sorts.
Z3_bool Z3_API Z3_is_quantifier_forall (__in Z3_context c, __in Z3_ast a)
Determine if quantifier is universal.
Precondition:
Z3_get_ast_kind(a) == Z3_QUANTIFIER_AST
Z3_bool Z3_API Z3_is_well_sorted (__in Z3_context c, __in Z3_ast t)
Return true if the given expression t is well sorted.
Z3_probe Z3_API Z3_le_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than or equal to the value returned by p2.
Remarks:
For probes, "true" is any value different from 0.
Z3_probe Z3_API Z3_lt_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than the value returned by p2.
Remarks:
For probes, "true" is any value different from 0.
Z3_ast Z3_API Z3_mk_add (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing args[0] + ... + args[num_args-1].
The array args must have num_args elements. All arguments must have int or real sort.
Remarks:
The number of arguments must be greater than zero.
Referenced by eval_example1(), find_model_example2(), and prove_example2().
Z3_ast Z3_API Z3_mk_and (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing args[0] and ... and args[num_args-1].
The array args must have num_args elements. All arguments must have Boolean sort.
Remarks:
The number of arguments must be greater than zero.
Referenced by demorgan(), mk_binary_and(), tuple_example1(), and unsat_core_and_proof_example().
Z3_ast Z3_API Z3_mk_app (__in Z3_context c, __in Z3_func_decl d, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create a constant or function application.
See also:
Z3_mk_func_decl
Referenced by assert_inj_axiom(), binary_tree_example(), display_model(), enum_example(), forest_example(), get_implied_equalities_example(), list_example(), mk_binary_app(), mk_tuple_update(), mk_unary_app(), substitute_example(), substitute_vars_example(), and tree_example().
Z3_ast Z3_API Z3_mk_array_default (__in Z3_context c, __in Z3_ast array)
Access the array default value. Produces the default range value, for arrays that can be represented as finite maps with a default range value.
Parameters:
c logical context.
array array value whose default range value is accessed.
Z3_sort Z3_API Z3_mk_array_sort (__in Z3_context c, __in Z3_sort domain, __in Z3_sort range)
Create an array type.
We usually represent the array type as: [domain -> range]. Arrays are usually used to model the heap/memory in software verification.
See also:
Z3_mk_select
Z3_mk_store
Referenced by array_example1(), array_example2(), and array_example3().
Z3_ast_map Z3_API Z3_mk_ast_map (__in Z3_context c)
Return an empty mapping from AST to AST.
Remarks:
Reference counting must be used to manage AST maps, even when the Z3_context was created using Z3_mk_context instead of Z3_mk_context_rc.
Z3_ast_vector Z3_API Z3_mk_ast_vector (__in Z3_context c)
Return an empty AST vector.
Remarks:
Reference counting must be used to manage AST vectors, even when the Z3_context was created using Z3_mk_context instead of Z3_mk_context_rc.
Z3_sort Z3_API Z3_mk_bool_sort (__in Z3_context c)
Create the Boolean type.
This type is used to create propositional variables and predicates.
Referenced by array_example2(), array_example3(), assert_retractable_cnstr(), demorgan(), mk_bool_var(), mk_fresh_bool_var(), mk_pa_theory(), mk_simple_theory(), reference_counter_example(), and two_contexts_example1().
Z3_ast Z3_API Z3_mk_bound (__in Z3_context c, __in unsigned index, __in Z3_sort ty)
Create a bound variable.
Bound variables are indexed by de-Bruijn indices. It is perhaps easiest to explain the meaning of de-Bruijn indices by indicating the compilation process from non-de-Bruijn formulas to de-Bruijn format.
       abs(forall (x1) phi) = forall (x1) abs1(phi, x1, 0)
       abs(forall (x1, x2) phi) = abs(forall (x1) abs(forall (x2) phi))
       abs1(x, x, n) = b_n
       abs1(y, x, n) = y
       abs1(f(t1,...,tn), x, n) = f(abs1(t1,x,n), ..., abs1(tn,x,n))
       abs1(forall (x1) phi, x, n) = forall (x1) (abs1(phi, x, n+1))
The last line is significant: the index of a bound variable is different depending on the scope in which it appears. The deeper x appears, the higher is its index.
Parameters:
c logical context
index de-Bruijn index
ty sort of the bound variable
See also:
Z3_mk_forall
Z3_mk_exists
Referenced by assert_inj_axiom(), and substitute_vars_example().
Z3_ast Z3_API Z3_mk_bv2int (__in Z3_context c, __in Z3_ast t1, Z3_bool is_signed)
Create an integer from the bit-vector argument t1. If is_signed is false, then the bit-vector t1 is treated as unsigned. So the result is non-negative and in the range [0..2^N-1], where N are the number of bits in t1. If is_signed is true, t1 is treated as a signed bit-vector.
NB. This function is essentially treated as uninterpreted. So you cannot expect Z3 to precisely reflect the semantics of this function when solving constraints with this function.
The node t1 must have a bit-vector sort.
Z3_sort Z3_API Z3_mk_bv_sort (__in Z3_context c, __in unsigned sz)
Create a bit-vector type of the given size.
This type can also be seen as a machine integer.
Remarks:
The size of the bitvector type must be greater than zero.
Referenced by bitvector_example1(), and bitvector_example2().
Z3_ast Z3_API Z3_mk_bvadd (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Standard two's complement addition.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvadd_no_overflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2, Z3_bool is_signed)
Create a predicate that checks that the bit-wise addition of t1 and t2 does not overflow.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvadd_no_underflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create a predicate that checks that the bit-wise signed addition of t1 and t2 does not underflow.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvand (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise and.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvashr (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Arithmetic shift right.
It is like logical shift right except that the most significant bits of the result always copy the most significant bit of the second argument.
NB. The semantics of shift operations varies between environments. This definition does not necessarily capture directly the semantics of the programming language or assembly architecture you are modeling.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvlshr (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Logical shift right.
It is equivalent to unsigned division by 2^x where x is the value of the third argument.
NB. The semantics of shift operations varies between environments. This definition does not necessarily capture directly the semantics of the programming language or assembly architecture you are modeling.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvmul (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Standard two's complement multiplication.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by bitvector_example2().
Z3_ast Z3_API Z3_mk_bvmul_no_overflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2, Z3_bool is_signed)
Create a predicate that checks that the bit-wise multiplication of t1 and t2 does not overflow.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvmul_no_underflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create a predicate that checks that the bit-wise signed multiplication of t1 and t2 does not underflow.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvnand (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise nand.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvneg (__in Z3_context c, __in Z3_ast t1)
Standard two's complement unary minus.
The node t1 must have bit-vector sort.
Z3_ast Z3_API Z3_mk_bvneg_no_overflow (__in Z3_context c, __in Z3_ast t1)
Check that bit-wise negation does not overflow when t1 is interpreted as a signed bit-vector.
The node t1 must have bit-vector sort.
Z3_ast Z3_API Z3_mk_bvnor (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise nor.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvnot (__in Z3_context c, __in Z3_ast t1)
Bitwise negation.
The node t1 must have a bit-vector sort.
Z3_ast Z3_API Z3_mk_bvor (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise or.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvredand (__in Z3_context c, __in Z3_ast t1)
Take conjunction of bits in vector, return vector of length 1.
The node t1 must have a bit-vector sort.
Z3_ast Z3_API Z3_mk_bvredor (__in Z3_context c, __in Z3_ast t1)
Take disjunction of bits in vector, return vector of length 1.
The node t1 must have a bit-vector sort.
Z3_ast Z3_API Z3_mk_bvsdiv (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed division.
It is defined in the following way:
The floor of t1/t2 if t2 is different from zero, and t1*t2 >= 0.
The ceiling of t1/t2 if t2 is different from zero, and t1*t2 < 0.
If t2 is zero, then the result is undefined.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvsdiv_no_overflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create a predicate that checks that the bit-wise signed division of t1 and t2 does not overflow.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvsge (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed greater than or equal to.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvsgt (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed greater than.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvshl (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Shift left.
It is equivalent to multiplication by 2^x where x is the value of the third argument.
NB. The semantics of shift operations varies between environments. This definition does not necessarily capture directly the semantics of the programming language or assembly architecture you are modeling.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvsle (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed less than or equal to.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by bitvector_example1().
Z3_ast Z3_API Z3_mk_bvslt (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed less than.
It abbreviates:
      (or (and (= (extract[|m-1|:|m-1|] t1) bit1)
               (= (extract[|m-1|:|m-1|] t2) bit0))
          (and (= (extract[|m-1|:|m-1|] t1) (extract[|m-1|:|m-1|] t2))
               (bvult t1 t2)))
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvsmod (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed remainder (sign follows divisor).
If t2 is zero, then the result is undefined.
The nodes t1 and t2 must have the same bit-vector sort.
See also:
Z3_mk_bvsrem
Z3_ast Z3_API Z3_mk_bvsrem (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Two's complement signed remainder (sign follows dividend).
It is defined as t1 - (t1 /s t2) * t2, where /s represents signed division. The most significant bit (sign) of the result is equal to the most significant bit of t1.
If t2 is zero, then the result is undefined.
The nodes t1 and t2 must have the same bit-vector sort.
See also:
Z3_mk_bvsmod
Z3_ast Z3_API Z3_mk_bvsub (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Standard two's complement subtraction.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by bitvector_example1(), and bitvector_example2().
Z3_ast Z3_API Z3_mk_bvsub_no_overflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create a predicate that checks that the bit-wise signed subtraction of t1 and t2 does not overflow.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvsub_no_underflow (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2, Z3_bool is_signed)
Create a predicate that checks that the bit-wise subtraction of t1 and t2 does not underflow.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvudiv (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned division.
It is defined as the floor of t1/t2 if t2 is different from zero. If t2 is zero, then the result is undefined.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvuge (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned greater than or equal to.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvugt (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned greater than.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvule (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned less than or equal to.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvult (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned less than.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvurem (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Unsigned remainder.
It is defined as t1 - (t1 /u t2) * t2, where /u represents unsigned division.
If t2 is zero, then the result is undefined.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvxnor (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise xnor.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_bvxor (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Bitwise exclusive-or.
The nodes t1 and t2 must have the same bit-vector sort.
Referenced by bitvector_example2().
Z3_ast Z3_API Z3_mk_concat (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Concatenate the given bit-vectors.
The nodes t1 and t2 must have (possibly different) bit-vector sorts
The result is a bit-vector of size n1+n2, where n1 (n2) is the size of t1 (t2).
Z3_config Z3_API Z3_mk_config ()
Create a configuration.
Configurations are created in order to assign parameters prior to creating contexts for Z3 interaction. For example, if the users wishes to use model generation, then call:
Z3_set_param_value(cfg, "MODEL", "true")
See also:
Z3_set_param_value
Z3_del_config
Configurations are created in order to assign parameters prior to creating contexts for Z3 interaction. For example, if the users whishes to use model generation, then call:
Z3_set_param_value(cfg, "MODEL", "true")
See also:
Z3_set_param_value
Z3_del_config
Referenced by demorgan(), error_code_example1(), error_code_example2(), get_implied_equalities_example(), mk_context(), mk_proof_context(), parser_example3(), parser_example5(), quantifier_example1(), and reference_counter_example().
Z3_ast Z3_API Z3_mk_const (__in Z3_context c, __in Z3_symbol s, __in Z3_sort ty)
Declare and create a constant.
This function is a shorthand for:
       \conly Z3_func_decl d = Z3_mk_func_decl(c, s, 0, 0, ty);
       \conly Z3_ast n            = Z3_mk_app(c, d, 0, 0);
       \conly
See also:
Z3_mk_func_decl
Z3_mk_app
Referenced by array_example2(), demorgan(), mk_var(), prove_example1(), push_pop_example1(), reference_counter_example(), and two_contexts_example1().
Z3_ast Z3_API Z3_mk_const_array (__in Z3_context c, __in Z3_sort domain, __in Z3_ast v)
Create the constant array.
The resulting term is an array, such that a select on an arbitrary index produces the value v.
Parameters:
c logical context.
domain domain sort for the array.
v value that the array maps to.
Z3_constructor Z3_API Z3_mk_constructor (__in Z3_context c, __in Z3_symbol name, __in Z3_symbol recognizer, __in unsigned num_fields, __in_ecount(num_fields) Z3_symbol const field_names[], __in_ecount(num_fields) Z3_sort const sorts[], __in_ecount(num_fields) unsigned sort_refs[])
Create a constructor.
Parameters:
c logical context.
name constructor name.
recognizer name of recognizer function.
num_fields number of fields in constructor.
field_names names of the constructor fields.
sorts field sorts, 0 if the field sort refers to a recursive sort.
sort_refs reference to datatype sort that is an argument to the constructor; if the corresponding sort reference is 0, then the value in sort_refs should be an index referring to one of the recursive datatypes that is declared.
BEGIN_MLAPI_EXCLUDE Z3_constructor Z3_API Z3_mk_constructor (__in Z3_context c, __in Z3_symbol name, __in Z3_symbol recognizer, __in unsigned num_fields, __in_ecount(num_fields) Z3_symbol const field_names[], __in_ecount(num_fields) Z3_sort_opt const sorts[], __in_ecount(num_fields) unsigned sort_refs[])
Create a constructor.
Parameters:
c logical context.
name constructor name.
recognizer name of recognizer function.
num_fields number of fields in constructor.
field_names names of the constructor fields.
sorts field sorts, 0 if the field sort refers to a recursive sort.
sort_refs reference to datatype sort that is an argument to the constructor; if the corresponding sort reference is 0, then the value in sort_refs should be an index referring to one of the recursive datatypes that is declared.
Referenced by binary_tree_example(), forest_example(), and tree_example().
Z3_constructor_list Z3_API Z3_mk_constructor_list (__in Z3_context c, __in unsigned num_constructors, __in_ecount(num_constructors) Z3_constructor const constructors[])
Create list of constructors.
Parameters:
c logical context.
num_constructors number of constructors in list.
constructors list of constructors.
Referenced by forest_example().
Z3_context Z3_API Z3_mk_context (__in Z3_config c)
Create a context using the given configuration.
After a context is created, the configuration cannot be changed, although some parameters can be changed using Z3_update_param_value. All main interaction with Z3 happens in the context of a Z3_context.
See also:
Z3_del_context
Deprecated:
Use Z3_mk_context_rc
After a context is created, the configuration cannot be changed. All main interaction with Z3 happens in the context of a Z3_context.
See also:
Z3_del_context
Referenced by demorgan(), get_implied_equalities_example(), mk_context(), and mk_context_custom().
Z3_context Z3_API Z3_mk_context_rc (__in Z3_config c)
Create a context using the given configuration. This function is similar to Z3_mk_context. However, in the context returned by this function, the user is responsible for managing Z3_ast reference counters. Managing reference counters is a burden and error-prone, but allows the user to use the memory more efficiently. The user must invoke Z3_inc_ref for any Z3_ast returned by Z3, and Z3_dec_ref whenever the Z3_ast is not needed anymore. This idiom is similar to the one used in BDD (binary decision diagrams) packages such as CUDD.
Remark: Z3_sort, Z3_func_decl, Z3_app, Z3_pattern are Z3_ast's.
After a context is created, the configuration cannot be changed. All main interaction with Z3 happens in the context of a Z3_context.
Referenced by reference_counter_example().
Z3_sort Z3_API Z3_mk_datatype (__in Z3_context c, __in Z3_symbol name, __in unsigned num_constructors, __inout_ecount(num_constructors) Z3_constructor constructors[])
Create datatype, such as lists, trees, records, enumerations or unions of records. The datatype may be recursive. Return the datatype sort.
Parameters:
c logical context.
name name of datatype.
num_constructors number of constructors passed in.
constructors array of constructor containers.
Referenced by binary_tree_example(), and tree_example().
void Z3_API Z3_mk_datatypes (__in Z3_context c, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __out_ecount(num_sorts) Z3_sort sorts[], __inout_ecount(num_sorts) Z3_constructor_list constructor_lists[])
Create mutually recursive datatypes.
Parameters:
c logical context.
num_sorts number of datatype sorts.
sort_names names of datatype sorts.
sorts array of datattype sorts.
constructor_lists list of constructors, one list per sort.
Referenced by forest_example().
Z3_ast Z3_API Z3_mk_distinct (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing distinct(args[0], ..., args[num_args-1]).
The distinct construct is used for declaring the arguments pairwise distinct. That is, Forall 0 <= i < j < num_args. not args[i] = args[j].
All arguments must have the same sort.
Remarks:
The number of arguments of a distinct construct must be greater than one.
Referenced by array_example2().
Z3_ast Z3_API Z3_mk_div (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Create an AST node representing arg1 div arg2.
The arguments must either both have int type or both have real type. If the arguments have int type, then the result type is an int type, otherwise the the result type is real.
Z3_ast Z3_API Z3_mk_empty_set (__in Z3_context c, __in Z3_sort domain)
Create the empty set.
Referenced by RawContext::MkEmptySet().
Z3_sort Z3_API Z3_mk_enumeration_sort (__in Z3_context c, __in Z3_symbol name, __in unsigned n, __in_ecount(n) Z3_symbol const enum_names[], __out_ecount(n) Z3_func_decl enum_consts[], __out_ecount(n) Z3_func_decl enum_testers[])
Create a enumeration sort.
An enumeration sort with n elements. This function will also declare the functions corresponding to the enumerations.
Parameters:
c logical context
name name of the enumeration sort.
n number of elemenets in enumeration sort.
enum_names names of the enumerated elements.
enum_consts constants corresponding to the enumerated elements.
enum_testers predicates testing if terms of the enumeration sort correspond to an enumeration.
For example, if this function is called with three symbols A, B, C and the name S, then s is a sort whose name is S, and the function returns three terms corresponding to A, B, C in enum_consts. The array enum_testers has three predicates of type (s -> Bool). The first predicate (corresponding to A) is true when applied to A, and false otherwise. Similarly for the other predicates.
Referenced by enum_example().
Z3_ast Z3_API Z3_mk_eq (__in Z3_context c, __in Z3_ast l, __in Z3_ast r)
Create an AST node representing l = r.
The nodes l and r must have the same type.
Referenced by apply_unit_axiom_for_parents_of(), array_example1(), assert_inj_axiom(), binary_tree_example(), bitvector_example2(), enum_example(), find_model_example2(), forest_example(), get_implied_equalities_example(), incremental_example1(), list_example(), model_display_example(), numeral_example(), pa_theory_example2(), prove_example1(), prove_example2(), quantifier_example1(), simple_example1(), simple_example2(), tree_example(), and tuple_example1().
Z3_ast Z3_API Z3_mk_exists (__in Z3_context c, __in unsigned weight, __in unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in unsigned num_decls, __in_ecount(num_decls) Z3_sort const sorts[], __in_ecount(num_decls) Z3_symbol const decl_names[], __in Z3_ast body)
Create an exists formula. Similar to Z3_mk_forall.
See also:
Z3_mk_pattern
Z3_mk_bound
Z3_mk_forall
Z3_mk_quantifier
Z3_mk_pattern
Z3_mk_bound
Z3_mk_forall
Z3_ast Z3_API Z3_mk_exists_const (__in Z3_context c, unsigned weight, unsigned num_bound, __in_ecount(num_bound) Z3_app const bound[], unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in Z3_ast body)
Similar to Z3_mk_forall_const.
Create an existential quantifier using a list of constants that will form the set of bound variables.
Parameters:
c logical context.
weight quantifiers are associated with weights indicating the importance of using the quantifier during instantiation. By default, pass the weight 0.
num_bound number of constants to be abstracted into bound variables.
bound array of constants to be abstracted into bound variables.
num_patterns number of patterns.
patterns array containing the patterns created using Z3_mk_pattern.
body the body of the quantifier.
See also:
Z3_mk_pattern
Z3_mk_forall_const
Z3_ast Z3_API Z3_mk_ext_rotate_left (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Rotate bits of t1 to the left t2 times.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_ext_rotate_right (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Rotate bits of t1 to the right t2 times.
The nodes t1 and t2 must have the same bit-vector sort.
Z3_ast Z3_API Z3_mk_extract (__in Z3_context c, __in unsigned high, __in unsigned low, __in Z3_ast t1)
Extract the bits high down to low from a bitvector of size m to yield a new bitvector of size n, where n = high - low + 1.
The node t1 must have a bit-vector sort.
Z3_ast Z3_API Z3_mk_false (__in Z3_context c)
Create an AST node representing false.
Referenced by assert_le_k(), ite_example(), mk_adder(), mk_adder_pairs(), RawContext::MkFalse(), and PATh_reduce_app().
Z3_sort Z3_API Z3_mk_finite_domain_sort (__in Z3_context c, __in Z3_symbol name, __in unsigned __int64 size)
Create a named finite domain sort.
To create constants that belong to the finite domain, use the APIs for creating numerals and pass a numeric constant together with the sort returned by this call.
See also:
Z3_get_finite_domain_sort_size.
Z3_fixedpoint Z3_API Z3_mk_fixedpoint (__in Z3_context c)
Create a new fixedpoint context.
Remarks:
User must use Z3_fixedpoint_inc_ref and Z3_fixedpoint_dec_ref to manage fixedpoint objects. Even if the context was created using Z3_mk_context instead of Z3_mk_context_rc.
Z3_ast Z3_API Z3_mk_forall (__in Z3_context c, __in unsigned weight, __in unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in unsigned num_decls, __in_ecount(num_decls) Z3_sort const sorts[], __in_ecount(num_decls) Z3_symbol const decl_names[], __in Z3_ast body)
Create a forall formula. It takes an expression body that contains bound variables of the same sorts as the sorts listed in the array sorts. The bound variables are de-Bruijn indices created using Z3_mk_bound. The array decl_names contains the names that the quantified formula uses for the bound variables. Z3 applies the convention that the last element in the decl_names and sorts array refers to the variable with index 0, the second to last element of decl_names and sorts refers to the variable with index 1, etc.
Create a forall formula.
Parameters:
c logical context.
weight quantifiers are associated with weights indicating the importance of using the quantifier during instantiation. By default, pass the weight 0.
num_patterns number of patterns.
patterns array containing the patterns created using Z3_mk_pattern.
num_decls number of variables to be bound.
sorts the sorts of the bound variables.
decl_names names of the bound variables
body the body of the quantifier.
See also:
Z3_mk_pattern
Z3_mk_bound
Z3_mk_exists
Referenced by assert_inj_axiom().
Z3_ast Z3_API Z3_mk_forall_const (__in Z3_context c, unsigned weight, unsigned num_bound, __in_ecount(num_bound) Z3_app const bound[], unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in Z3_ast body)
Create a universal quantifier using a list of constants that will form the set of bound variables.
Parameters:
c logical context.
weight quantifiers are associated with weights indicating the importance of using the quantifier during instantiation. By default, pass the weight 0.
num_bound number of constants to be abstracted into bound variables.
bound array of constants to be abstracted into bound variables.
num_patterns number of patterns.
patterns array containing the patterns created using Z3_mk_pattern.
body the body of the quantifier.
See also:
Z3_mk_pattern
Z3_mk_exists_const
Z3_ast Z3_API Z3_mk_fresh_const (__in Z3_context c, __in_z Z3_string prefix, __in Z3_sort ty)
Declare and create a fresh constant.
This function is a shorthand for:
 Z3_func_decl d = Z3_mk_fresh_func_decl(c, prefix, 0, 0, ty); Z3_ast n = Z3_mk_app(c, d, 0, 0);
Remarks:
If prefix is NULL, then it is assumed to be the empty string.
See also:
Z3_mk_func_decl
Z3_mk_app
Z3_ast Z3_API Z3_mk_fresh_const (__in Z3_context c, __in Z3_string prefix, __in Z3_sort ty)
Declare and create a fresh constant.
This function is a shorthand for:
 Z3_func_decl d = Z3_mk_fresh_func_decl(c, prefix, 0, 0, ty); Z3_ast n = Z3_mk_app(c, d, 0, 0);
Remarks:
If prefix is NULL, then it is assumed to be the empty string.
See also:
Z3_mk_func_decl
Z3_mk_app
Referenced by assert_retractable_cnstr(), and mk_fresh_bool_var().
Z3_func_decl Z3_API Z3_mk_fresh_func_decl (__in Z3_context c, __in_z Z3_string prefix, __in unsigned domain_size, __in_ecount(domain_size) Z3_sort const domain[], __in Z3_sort range)
Declare a fresh constant or function.
Z3 will generate an unique name for this function declaration. If prefix is different from NULL, then the name generate by Z3 will start with prefix.
Remarks:
If prefix is NULL, then it is assumed to be the empty string.
See also:
Z3_mk_func_decl
Z3_func_decl Z3_API Z3_mk_fresh_func_decl (__in Z3_context c, __in Z3_string prefix, __in unsigned domain_size, __in_ecount(domain_size) Z3_sort const domain[], __in Z3_sort range)
Declare a fresh constant or function.
Z3 will generate an unique name for this function declaration. If prefix is different from NULL, then the name generate by Z3 will start with prefix.
Remarks:
If prefix is NULL, then it is assumed to be the empty string.
See also:
Z3_mk_func_decl
Referenced by assert_inj_axiom().
Z3_ast Z3_API Z3_mk_full_set (__in Z3_context c, __in Z3_sort domain)
Create the full set.
Referenced by RawContext::MkFullSet().
Z3_func_decl Z3_API Z3_mk_func_decl (__in Z3_context c, __in Z3_symbol s, __in unsigned domain_size, __in_ecount(domain_size) Z3_sort const domain[], __in Z3_sort range)
Declare a constant or function.
Parameters:
c logical context.
s name of the constant or function.
domain_size number of arguments. It is 0 when declaring a constant.
domain array containing the sort of each argument. The array must contain domain_size elements. It is 0 when declaring a constant.
range sort of the constant or the return sort of the function.
After declaring a constant or function, the function Z3_mk_app can be used to create a constant or function application.
See also:
Z3_mk_app
Parameters:
c logical context.
s name of the constant or function.
domain_size number of arguments. It is 0 when declaring a constant.
domain array containing the sort of each argument. The array must contain domain_size elements. It is 0 whe declaring a constant.
range sort of the constant or the return sort of the function.
After declaring a constant or function, the function Z3_mk_app can be used to create a constant or function application.
See also:
Z3_mk_app
Referenced by get_implied_equalities_example(), parser_example3(), prove_example1(), prove_example2(), quantifier_example1(), substitute_example(), and substitute_vars_example().
Z3_ast Z3_API Z3_mk_ge (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create greater than or equal to.
The nodes t1 and t2 must have the same sort, and must be int or real.
Referenced by binary_tree_example(), and push_pop_example1().
Z3_goal Z3_API Z3_mk_goal (__in Z3_context c, __in Z3_bool models, __in Z3_bool unsat_cores, __in Z3_bool proofs)
Create a goal (aka problem). A goal is essentially a set of formulas, that can be solved and/or transformed using tactics and solvers.
If models == true, then model generation is enabled for the new goal.
If unsat_cores == true, then unsat core generation is enabled for the new goal.
If proofs == true, then proof generation is enabled for the new goal. Remark, the Z3 context c must have been created with proof generation support.
Remarks:
Reference counting must be used to manage goals, even when the Z3_context was created using Z3_mk_context instead of Z3_mk_context_rc.
Z3_ast Z3_API Z3_mk_gt (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create greater than.
The nodes t1 and t2 must have the same sort, and must be int or real.
Referenced by eval_example1(), find_model_example2(), incremental_example1(), and push_pop_example1().
Z3_ast Z3_API Z3_mk_iff (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create an AST node representing t1 iff t2.
The nodes t1 and t2 must have Boolean sort.
Referenced by bitvector_example1(), demorgan(), and error_code_example2().
Z3_ast Z3_API Z3_mk_implies (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create an AST node representing t1 implies t2.
The nodes t1 and t2 must have Boolean sort.
Referenced by array_example1(), forest_example(), list_example(), tree_example(), and tuple_example1().
Z3_func_decl Z3_API Z3_mk_injective_function (__in Z3_context c, __in Z3_symbol s, unsigned domain_size, __in_ecount(domain_size) Z3_sort const domain[], __in Z3_sort range)
Create injective function declaration.
Deprecated:
This method just asserts a (universally quantified) formula that asserts that the new function is injective. It is compatible with the old interface for solving: Z3_assert_cnstr, Z3_check_assumptions, etc.
Z3_ast Z3_API Z3_mk_int (__in Z3_context c, __in int v, __in Z3_sort ty)
Create a numeral of an int, bit-vector, or finite-domain sort.
Create a numeral of a given sort.
This function can be use to create numerals that fit in a machine integer. It is slightly faster than Z3_mk_numeral since it is not necessary to parse a string.
See also:
Z3_mk_numeral
Referenced by mk_int().
Z3_ast Z3_API Z3_mk_int2bv (__in Z3_context c, __in unsigned n, __in Z3_ast t1)
Create an n bit bit-vector from the integer argument t1.
NB. This function is essentially treated as uninterpreted. So you cannot expect Z3 to precisely reflect the semantics of this function when solving constraints with this function.
The node t1 must have integer sort.
Z3_ast Z3_API Z3_mk_int2real (__in Z3_context c, __in Z3_ast t1)
Coerce an integer to a real.
There is also a converse operation exposed. It follows the semantics prescribed by the SMT-LIB standard.
You can take the floor of a real by creating an auxiliary integer constant k and and asserting mk_int2real(k) <= t1 < mk_int2real(k)+1.
The node t1 must have sort integer.
See also:
Z3_mk_real2int
Z3_mk_is_int
Z3_ast Z3_API Z3_mk_int64 (__in Z3_context c, __in __int64 v, __in Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
Create a numeral of a given sort.
This function can be use to create numerals that fit in a machine __int64 integer. It is slightly faster than Z3_mk_numeral since it is not necessary to parse a string.
See also:
Z3_mk_numeral
Z3_sort Z3_API Z3_mk_int_sort (__in Z3_context c)
Create the integer type.
Create an integer type.
This type is not the int type found in programming languages. A machine integer can be represented using bit-vectors. The function Z3_mk_bv_sort creates a bit-vector type.
See also:
Z3_mk_bv_sort
Referenced by array_example1(), array_example3(), binary_tree_example(), get_implied_equalities_example(), list_example(), mk_int(), mk_int_var(), parser_example3(), prove_example2(), push_pop_example1(), quantifier_example1(), substitute_example(), and substitute_vars_example().
Z3_symbol Z3_API Z3_mk_int_symbol (__in Z3_context c, __in int i)
Create a Z3 symbol using an integer.
Symbols are used to name several term and type constructors.
NB. Not all integers can be passed to this function. The legal range of unsigned integers is 0 to 2^30-1.
See also:
Z3_mk_string_symbol
Referenced by array_example2(), assert_inj_axiom(), demorgan(), and two_contexts_example1().
Z3_ast Z3_API Z3_mk_is_int (__in Z3_context c, __in Z3_ast t1)
Check if a real number is an integer.
See also:
Z3_mk_int2real
Z3_mk_real2int
Z3_ast Z3_API Z3_mk_ite (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2, __in Z3_ast t3)
Create an AST node representing an if-then-else: ite(t1, t2, t3).
The node t1 must have Boolean sort, t2 and t3 must have the same sort. The sort of the new node is equal to the sort of t2 and t3.
Referenced by ite_example(), pa_theory_example1(), and simple_example1().
Z3_ast Z3_API Z3_mk_label (__in Z3_context c, __in Z3_symbol s, Z3_bool is_pos, Z3_ast f)
Create a labeled formula.
Parameters:
c logical context.
s name of the label.
is_pos label polarity.
f formula being labeled.
A label behaves as an identity function, so the truth value of the labeled formula is unchanged. Labels are used for identifying useful sub-formulas when generating counter-examples.
Deprecated:
Labels are only supported by the old Solver API. This feature is not essential (it can be simulated using auxiliary Boolean variables). It is only available for backward compatibility.
Parameters:
c logical context.
s name of the label.
is_pos label polarity.
f formula being labeled.
A label behaves as an identity function, so the truth value of the labeled formula is unchanged. Labels are used for identifying useful sub-formulas when generating counter-examples.
Z3_ast Z3_API Z3_mk_le (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create less than or equal to.
The nodes t1 and t2 must have the same sort, and must be int or real.
Referenced by get_implied_equalities_example(), prove_example2(), and push_pop_example1().
Z3_sort Z3_API Z3_mk_list_sort (__in Z3_context c, __in Z3_symbol name, __in Z3_sort elem_sort, __out Z3_func_decl * nil_decl, __out Z3_func_decl * is_nil_decl, __out Z3_func_decl * cons_decl, __out Z3_func_decl * is_cons_decl, __out Z3_func_decl * head_decl, __out Z3_func_decl * tail_decl)
Create a list sort.
A list sort over elem_sort This function declares the corresponding constructors and testers for lists.
Parameters:
c logical context
name name of the list sort.
elem_sort sort of list elements.
nil_decl declaration for the empty list.
is_nil_decl test for the empty list.
cons_decl declaration for a cons cell.
is_cons_decl cons cell test.
head_decl list head.
tail_decl list tail.
Referenced by list_example().
Z3_ast Z3_API Z3_mk_lt (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create less than.
The nodes t1 and t2 must have the same sort, and must be int or real.
Referenced by eval_example1(), find_model_example2(), incremental_example1(), and prove_example2().
Z3_ast Z3_API Z3_mk_map (__in Z3_context c, __in Z3_func_decl f, unsigned n, __in Z3_ast const * args)
map f on the the argument arrays.
The n nodes args must be of array sorts [domain_i -> range_i]. The function declaration f must have type range_1 .. range_n -> range. v must have sort range. The sort of the result is [domain_i -> range].
See also:
Z3_mk_array_sort
Z3_mk_store
Z3_mk_select
Z3_ast Z3_API Z3_mk_mod (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Create an AST node representing arg1 mod arg2.
The arguments must have int type.
Z3_ast Z3_API Z3_mk_mul (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing args[0] * ... * args[num_args-1].
The array args must have num_args elements. All arguments must have int or real sort.
Remarks:
Z3 has limited support for non-linear arithmetic.
The number of arguments must be greater than zero.
Z3_ast Z3_API Z3_mk_not (__in Z3_context c, __in Z3_ast a)
Create an AST node representing not(a).
The node a must have Boolean sort.
Referenced by apply_compare_axiom_for_parents_of(), assert_le_k(), assert_retractable_cnstr(), binary_tree_example(), demorgan(), enum_example(), find_model_example2(), forest_example(), fu_malik_maxsat_step(), list_example(), numeral_example(), prove(), prove_example2(), quantifier_example1(), simple_example2(), tree_example(), and unsat_core_and_proof_example().
Z3_ast Z3_API Z3_mk_numeral (__in Z3_context c, __in_z Z3_string numeral, __in Z3_sort ty)
Create a numeral of a given sort.
Parameters:
c logical context.
numeral A string representing the numeral value in decimal notation. If the given sort is a real, then the numeral can be a rational, that is, a string of the form [num]* / [num]*.
ty The sort of the numeral. In the current implementation, the given sort can be an int, real, or bit-vectors of arbitrary size.
See also:
Z3_mk_int
Z3_mk_unsigned_int
Z3_ast Z3_API Z3_mk_numeral (__in Z3_context c, __in Z3_string numeral, __in Z3_sort ty)
Create a numeral of a given sort.
Parameters:
c logical context.
numeral A string representing the numeral value in decimal notation. If the given sort is a real, then the numeral can be a rational, that is, a string of the form [num]* / [num]*.
ty The sort of the numeral. In the current implementation, the given sort can be an int, real, finite-domain, or bit-vectors of arbitrary size.
See also:
Z3_mk_int
Z3_mk_unsigned_int
Referenced by bitvector_example1(), bitvector_example2(), numeral_example(), push_pop_example1(), substitute_example(), and tuple_example1().
Z3_ast Z3_API Z3_mk_or (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing args[0] or ... or args[num_args-1].
The array args must have num_args elements. All arguments must have Boolean sort.
Remarks:
The number of arguments must be greater than zero.
Referenced by array_example1(), assert_retractable_cnstr(), demorgan(), enum_example(), forest_example(), list_example(), mk_binary_or(), mk_ternary_or(), model_display_example(), pa_theory_example2(), simple_example2(), tree_example(), and unsat_core_and_proof_example().
Z3_params Z3_API Z3_mk_params (__in Z3_context c)
Create a Z3 (empty) parameter set. Starting at Z3 4.0, parameter sets are used to configure many components such as: simplifiers, tactics, solvers, etc.
Create a Z3 (empty) parameter set. Starting at Z3 3.3, parameter sets are used to configure many components such as: simplifiers, tactics, solvers, etc.
Remarks:
Reference counting must be used to manage parameter sets, even when the Z3_context was created using Z3_mk_context instead of Z3_mk_context_rc.
Z3_pattern Z3_API Z3_mk_pattern (__in Z3_context c, __in unsigned num_patterns, __in_ecount(num_patterns) Z3_ast const terms[])
Create a pattern for quantifier instantiation.
Z3 uses pattern matching to instantiate quantifiers. If a pattern is not provided for a quantifier, then Z3 will automatically compute a set of patterns for it. However, for optimal performance, the user should provide the patterns.
Patterns comprise a list of terms. The list should be non-empty. If the list comprises of more than one term, it is a called a multi-pattern.
In general, one can pass in a list of (multi-)patterns in the quantifier constructor.
See also:
Z3_mk_forall
Z3_mk_exists
Referenced by assert_inj_axiom().
Z3_ast Z3_API Z3_mk_power (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Create an AST node representing arg1^arg2.
The arguments must have int or real type.
Z3_probe Z3_API Z3_mk_probe (__in Z3_context c, __in_z Z3_string name)
Return a probe associated with the given name. The complete list of probes may be obtained using the procedures Z3_get_num_probes and Z3_get_probe_name. It may also be obtained using the command (help-tactics) in the SMT 2.0 front-end.
Probes are used to inspect a goal (aka problem) and collect information that may be used to decide which solver and/or preprocessing step will be used.
Z3_probe Z3_API Z3_mk_probe (__in Z3_context c, __in Z3_string name)
Return a probe associated with the given name. The complete list of probes may be obtained using the procedures Z3_get_num_probes and Z3_get_probe_name. It may also be obtained using the command (help-tactics) in the SMT 2.0 front-end.
Probes are used to inspect a goal (aka problem) and collect information that may be used to decide which solver and/or preprocessing step will be used.
Z3_ast Z3_API Z3_mk_quantifier (__in Z3_context c, __in Z3_bool is_forall, __in unsigned weight, __in unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in unsigned num_decls, __in_ecount(num_decls) Z3_sort const sorts[], __in_ecount(num_decls) Z3_symbol const decl_names[], __in Z3_ast body)
Create a quantifier - universal or existential, with pattern hints. See the documentation for Z3_mk_forall for an explanation of the parameters.
Create a quantifier - universal or existential, with pattern hints.
Parameters:
c logical context.
is_forall flag to indicate if this is a universal or existential quantifier.
weight quantifiers are associated with weights indicating the importance of using the quantifier during instantiation. By default, pass the weight 0.
num_patterns number of patterns.
patterns array containing the patterns created using Z3_mk_pattern.
num_decls number of variables to be bound.
sorts array of sorts of the bound variables.
decl_names names of the bound variables.
body the body of the quantifier.
See also:
Z3_mk_pattern
Z3_mk_bound
Z3_mk_forall
Z3_mk_exists
Z3_ast Z3_API Z3_mk_quantifier_const (__in Z3_context c, Z3_bool is_forall, unsigned weight, unsigned num_bound, __in_ecount(num_bound) Z3_app const bound[], unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in Z3_ast body)
Create a universal or existential quantifier using a list of constants that will form the set of bound variables.
Z3_ast Z3_API Z3_mk_quantifier_const_ex (__in Z3_context c, Z3_bool is_forall, unsigned weight, __in Z3_symbol quantifier_id, __in Z3_symbol skolem_id, unsigned num_bound, __in_ecount(num_bound) Z3_app const bound[], unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], unsigned num_no_patterns, __in_ecount(num_no_patterns) Z3_ast const no_patterns[], __in Z3_ast body)
Create a universal or existential quantifier using a list of constants that will form the set of bound variables.
Z3_ast Z3_API Z3_mk_quantifier_ex (__in Z3_context c, __in Z3_bool is_forall, __in unsigned weight, __in Z3_symbol quantifier_id, __in Z3_symbol skolem_id, __in unsigned num_patterns, __in_ecount(num_patterns) Z3_pattern const patterns[], __in unsigned num_no_patterns, __in_ecount(num_no_patterns) Z3_ast const no_patterns[], __in unsigned num_decls, __in_ecount(num_decls) Z3_sort const sorts[], __in_ecount(num_decls) Z3_symbol const decl_names[], __in Z3_ast body)
Create a quantifier - universal or existential, with pattern hints, no patterns, and attributes.
Parameters:
c logical context.
is_forall flag to indicate if this is a universal or existential quantifier.
quantifier_id identifier to identify quantifier
skolem_id identifier to identify skolem constants introduced by quantifier.
weight quantifiers are associated with weights indicating the importance of using the quantifier during instantiation. By default, pass the weight 0.
num_patterns number of patterns.
patterns array containing the patterns created using Z3_mk_pattern.
num_no_patterns number of patterns.
no_patterns array containing the patterns created using Z3_mk_pattern.
num_decls number of variables to be bound.
sorts array of sorts of the bound variables.
decl_names names of the bound variables.
body the body of the quantifier.
See also:
Z3_mk_pattern
Z3_mk_bound
Z3_mk_forall
Z3_mk_exists
Z3_ast Z3_API Z3_mk_real (__in Z3_context c, __in_z int num, __in_z int den)
Create a real from a fraction.
Parameters:
c logical context.
num numerator of rational.
den denomerator of rational.
Precondition:
den != 0
See also:
Z3_mk_numeral
Z3_mk_int
Z3_mk_unsigned_int
Z3_ast Z3_API Z3_mk_real (__in Z3_context c, __in int num, __in int den)
Create a real from a fraction.
Parameters:
c logical context.
num numerator of rational.
den denomerator of rational.
Precondition:
den != 0
See also:
Z3_mk_numeral
Z3_mk_int
Z3_mk_unsigned_int
Z3_ast Z3_API Z3_mk_real2int (__in Z3_context c, __in Z3_ast t1)
Coerce a real to an integer.
The semantics of this function follows the SMT-LIB standard for the function to_int
See also:
Z3_mk_int2real
Z3_mk_is_int
Z3_sort Z3_API Z3_mk_real_sort (__in Z3_context c)
Create the real type.
Create a real type.
This type is not a floating point number. Z3 does not have support for floating point numbers yet.
Referenced by mk_real_var(), numeral_example(), and tuple_example1().
Z3_ast Z3_API Z3_mk_rem (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Create an AST node representing arg1 rem arg2.
The arguments must have int type.
Z3_ast Z3_API Z3_mk_repeat (__in Z3_context c, __in unsigned i, __in Z3_ast t1)
Repeat the given bit-vector up length i.
The node t1 must have a bit-vector sort.
Z3_ast Z3_API Z3_mk_rotate_left (__in Z3_context c, __in unsigned i, __in Z3_ast t1)
Rotate bits of t1 to the left i times.
The node t1 must have a bit-vector sort.
Z3_ast Z3_API Z3_mk_rotate_right (__in Z3_context c, __in unsigned i, __in Z3_ast t1)
Rotate bits of t1 to the right i times.
The node t1 must have a bit-vector sort.
Z3_ast Z3_API Z3_mk_select (__in Z3_context c, __in Z3_ast a, __in Z3_ast i)
Array read. The argument a is the array and i is the index of the array that gets read.
The node a must have an array sort [domain -> range], and i must have the sort domain. The sort of the result is range.
See also:
Z3_mk_array_sort
Z3_mk_store
Referenced by array_example1().
Z3_ast Z3_API Z3_mk_set_add (__in Z3_context c, __in Z3_ast set, __in Z3_ast elem)
Add an element to a set.
The first argument must be a set, the second an element.
Referenced by RawContext::MkSetAdd().
Z3_ast Z3_API Z3_mk_set_complement (__in Z3_context c, __in Z3_ast arg)
Take the complement of a set.
Referenced by RawContext::MkSetComplement().
Z3_ast Z3_API Z3_mk_set_del (__in Z3_context c, __in Z3_ast set, __in Z3_ast elem)
Remove an element to a set.
The first argument must be a set, the second an element.
Referenced by RawContext::MkSetDel().
Z3_ast Z3_API Z3_mk_set_difference (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Take the set difference between two sets.
Referenced by RawContext::MkSetDifference().
Z3_ast Z3_API Z3_mk_set_intersect (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Take the intersection of a list of sets.
Z3_ast Z3_API Z3_mk_set_member (__in Z3_context c, __in Z3_ast elem, __in Z3_ast set)
Check for set membership.
The first argument should be an element type of the set.
Referenced by RawContext::MkSetMember().
Z3_sort Z3_API Z3_mk_set_sort (__in Z3_context c, __in Z3_sort ty)
Create Set type.
Referenced by RawContext::MkSetSort().
Z3_ast Z3_API Z3_mk_set_subset (__in Z3_context c, __in Z3_ast arg1, __in Z3_ast arg2)
Check for subsetness of sets.
Referenced by RawContext::MkSetSubset().
Z3_ast Z3_API Z3_mk_set_union (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Take the union of a list of sets.
Z3_ast Z3_API Z3_mk_sign_ext (__in Z3_context c, __in unsigned i, __in Z3_ast t1)
Sign-extend of the given bit-vector to the (signed) equivalent bitvector of size m+i, where m is the size of the given bit-vector.
The node t1 must have a bit-vector sort.
Z3_solver Z3_API Z3_mk_simple_solver (__in Z3_context c)
Create a new (incremental) solver.
Z3_solver Z3_API Z3_mk_solver (__in Z3_context c)
Create a new (incremental) solver. This solver also uses a set of builtin tactics for handling the first check-sat command, and check-sat commands that take more than a given number of milliseconds to be solved.
Remarks:
User must use Z3_solver_inc_ref and Z3_solver_dec_ref to manage solver objects. Even if the context was created using Z3_mk_context instead of Z3_mk_context_rc.
Z3_solver Z3_API Z3_mk_solver_for_logic (__in Z3_context c, __in Z3_symbol logic)
Create a new solver customized for the given logic. It behaves like Z3_mk_solver if the logic is unknown or unsupported.
Remarks:
User must use Z3_solver_inc_ref and Z3_solver_dec_ref to manage solver objects. Even if the context was created using Z3_mk_context instead of Z3_mk_context_rc.
Z3_solver Z3_API Z3_mk_solver_from_tactic (__in Z3_context c, __in Z3_tactic t)
Create a new solver that is implemented using the given tactic. The solver supports the commands Z3_solver_push and Z3_solver_pop, but it will always solve each Z3_solver_check from scratch.
Z3_ast Z3_API Z3_mk_store (__in Z3_context c, __in Z3_ast a, __in Z3_ast i, __in Z3_ast v)
Array update.
The node a must have an array sort [domain -> range], i must have sort domain, v must have sort range. The sort of the result is [domain -> range]. The semantics of this function is given by the theory of arrays described in the SMT-LIB standard. See http://smtlib.org for more details. The result of this function is an array that is equal to a (with respect to select) on all indices except for i, where it maps to v (and the select of a with respect to i may be a different value).
See also:
Z3_mk_array_sort
Z3_mk_select
Referenced by array_example1().
Z3_symbol Z3_API Z3_mk_string_symbol (__in Z3_context c, __in_z Z3_string s)
Create a Z3 symbol using a C string.
Symbols are used to name several term and type constructors.
See also:
Z3_mk_int_symbol
Z3_symbol Z3_API Z3_mk_string_symbol (__in Z3_context c, __in Z3_string s)
Create a Z3 symbol using a C string.
Symbols are used to name several term and type constructors.
See also:
Z3_mk_int_symbol
Referenced by assert_comm_axiom(), binary_tree_example(), enum_example(), forest_example(), get_implied_equalities_example(), list_example(), mk_pa_theory(), mk_simple_theory(), mk_var(), model_display_example(), parser_example2(), parser_example3(), PATh_mk_string_value(), prove_example1(), prove_example2(), push_pop_example1(), quantifier_example1(), reference_counter_example(), substitute_example(), substitute_vars_example(), tree_example(), and tuple_example1().
Z3_ast Z3_API Z3_mk_sub (__in Z3_context c, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Create an AST node representing args[0] - ... - args[num_args - 1].
The array args must have num_args elements. All arguments must have int or real sort.
Remarks:
The number of arguments must be greater than zero.
Referenced by prove_example2().
Z3_tactic Z3_API Z3_mk_tactic (__in Z3_context c, __in_z Z3_string name)
Return a tactic associated with the given name. The complete list of tactics may be obtained using the procedures Z3_get_num_tactics and Z3_get_tactic_name. It may also be obtained using the command (help-tactics) in the SMT 2.0 front-end.
Tactics are the basic building block for creating custom solvers for specific problem domains.
Z3_tactic Z3_API Z3_mk_tactic (__in Z3_context c, __in Z3_string name)
Return a tactic associated with the given name. The complete list of tactics may be obtained using the procedures Z3_get_num_tactics and Z3_get_tactic_name. It may also be obtained using the command (help-tactics) in the SMT 2.0 front-end.
Tactics are the basic building block for creating custom solvers for specific problem domains.
Z3_theory Z3_API Z3_mk_theory (__in Z3_context c, __in_z Z3_string th_name, __in Z3_theory_data data)
Create a new user defined theory. The new theory will be identified by the name th_name. A theory must be created before asserting any assertion to the given context. Return NULL in case of failure.
data is a pointer to an external data-structure that may be used to store theory specific additional data.
Z3_theory Z3_API Z3_mk_theory (__in Z3_context c, __in Z3_string th_name, __in Z3_theory_data data)
Create a new user defined theory. The new theory will be identified by the name th_name. A theory must be created before asserting any assertion to the given context. Return NULL in case of failure.
data is a pointer to an external data-structure that may be used to store theory specific additional data.
Referenced by mk_pa_theory(), mk_simple_theory(), and model_display_example().
Z3_ast Z3_API Z3_mk_true (__in Z3_context c)
Create an AST node representing true.
Referenced by assert_le_k(), get_num_disabled_soft_constraints(), RawContext::MkTrue(), PATh_reduce_app(), and Th_reduce_app().
Z3_sort Z3_API Z3_mk_tuple_sort (__in Z3_context c, __in Z3_symbol mk_tuple_name, __in unsigned num_fields, __in_ecount(num_fields) Z3_symbol const field_names[], __in_ecount(num_fields) Z3_sort const field_sorts[], __out Z3_func_decl * mk_tuple_decl, __out_ecount(num_fields) Z3_func_decl proj_decl[])
Create a tuple type.
A tuple with n fields has a constructor and n projections. This function will also declare the constructor and projection functions.
Parameters:
c logical context
mk_tuple_name name of the constructor function associated with the tuple type.
num_fields number of fields in the tuple type.
field_names name of the projection functions.
field_sorts type of the tuple fields.
mk_tuple_decl output parameter that will contain the constructor declaration.
proj_decl output parameter that will contain the projection function declarations. This field must be a buffer of size num_fields allocated by the user.
Referenced by tuple_example1().
Z3_ast Z3_API Z3_mk_unary_minus (__in Z3_context c, __in Z3_ast arg)
Create an AST node representing -arg.
The arguments must have int or real type.
Z3_sort Z3_API Z3_mk_uninterpreted_sort (__in Z3_context c, __in Z3_symbol s)
Create a free (uninterpreted) type using the given name (symbol).
Two free types are considered the same iff the have the same name.
Referenced by prove_example1().
Z3_ast Z3_API Z3_mk_unsigned_int (__in Z3_context c, __in unsigned v, __in Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
Create a numeral of a given sort.
This function can be use to create numerals that fit in a machine unsinged integer. It is slightly faster than Z3_mk_numeral since it is not necessary to parse a string.
See also:
Z3_mk_numeral
Z3_ast Z3_API Z3_mk_unsigned_int64 (__in Z3_context c, __in unsigned __int64 v, __in Z3_sort ty)
Create a numeral of a int, bit-vector, or finite-domain sort.
Create a numeral of a given sort.
This function can be use to create numerals that fit in a machine unsigned __int64 integer. It is slightly faster than Z3_mk_numeral since it is not necessary to parse a string.
See also:
Z3_mk_numeral
Z3_ast Z3_API Z3_mk_xor (__in Z3_context c, __in Z3_ast t1, __in Z3_ast t2)
Create an AST node representing t1 xor t2.
The nodes t1 and t2 must have Boolean sort.
Referenced by find_model_example1(), mk_full_adder(), and reference_counter_example().
Z3_ast Z3_API Z3_mk_zero_ext (__in Z3_context c, __in unsigned i, __in Z3_ast t1)
Extend the given bit-vector with zeros to the (unsigned) equivalent bitvector of size m+i, where m is the size of the given bit-vector.
The node t1 must have a bit-vector sort.
void Z3_API Z3_model_dec_ref (__in Z3_context c, __in Z3_model m)
Decrement the reference counter of the given model.
Z3_bool Z3_API Z3_model_eval (__in Z3_context c, __in Z3_model m, __in Z3_ast t, __in Z3_bool model_completion, __out Z3_ast * v)
Evaluate the AST node t in the given model. Return Z3_TRUE if succeeded, and store the result in v.
If model_completion is Z3_TRUE, then Z3 will assign an interpretation for any constant or function that does not have an interpretation in m. These constants and functions were essentially don't cares.
The evaluation may fail for the following reasons:
t contains a quantifier.
the model m is partial, that is, it doesn't have a complete interpretation for uninterpreted functions. That is, the option MODEL_PARTIAL=true was used.
t is type incorrect.
Z3_func_decl Z3_API Z3_model_get_const_decl (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the i-th constant in the given model.
Precondition:
i < Z3_model_get_num_consts(c, m)
See also:
Z3_model_eval
Z3_ast Z3_API Z3_model_get_const_interp (__in Z3_context c, __in Z3_model m, __in Z3_func_decl a)
Return the interpretation (i.e., assignment) of constant a in the model m. Return NULL, if the model does not assign an interpretation for a. That should be interpreted as: the value of a does not matter.
Precondition:
Z3_get_arity(c, a) == 0
Z3_func_decl Z3_API Z3_model_get_func_decl (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return the declaration of the i-th function in the given model.
Precondition:
i < Z3_model_get_num_funcs(c, m)
See also:
Z3_model_get_num_funcs
Z3_func_interp Z3_API Z3_model_get_func_interp (__in Z3_context c, __in Z3_model m, __in Z3_func_decl f)
Return the interpretation of the function f in the model m. Return NULL, if the model does not assign an interpretation for f. That should be interpreted as: the f does not matter.
Precondition:
Z3_get_arity(c, f) > 0
Remarks:
Reference counting must be used to manage Z3_func_interp objects, even when the Z3_context was created using Z3_mk_context instead of Z3_mk_context_rc.
unsigned Z3_API Z3_model_get_num_consts (__in Z3_context c, __in Z3_model m)
Return the number of constants assigned by the given model.
See also:
Z3_model_get_const_decl
unsigned Z3_API Z3_model_get_num_funcs (__in Z3_context c, __in Z3_model m)
Return the number of function interpretations in the given model.
A function interpretation is represented as a finite map and an 'else' value. Each entry in the finite map represents the value of a function given a set of arguments.
unsigned Z3_API Z3_model_get_num_sorts (__in Z3_context c, __in Z3_model m)
Return the number of uninterpreted sorts that m assigs an interpretation to.
Z3 also provides an intepretation for uninterpreted sorts used in a formua. The interpretation for a sort s is a finite set of distinct values. We say this finite set is the "universe" of s.
See also:
Z3_model_get_sort
Z3_model_get_sort_universe
Z3_sort Z3_API Z3_model_get_sort (__in Z3_context c, __in Z3_model m, __in unsigned i)
Return a uninterpreted sort that m assigns an interpretation.
Precondition:
i < Z3_model_get_num_sorts(c, m)
See also:
Z3_model_get_num_sorts
Z3_model_get_sort_universe
Z3_ast_vector Z3_API Z3_model_get_sort_universe (__in Z3_context c, __in Z3_model m, __in Z3_sort s)
Return the finite set of distinct values that represent the interpretation for sort s.
See also:
Z3_model_get_num_sorts
Z3_model_get_sort
void Z3_API Z3_model_inc_ref (__in Z3_context c, __in Z3_model m)
Increment the reference counter of the given model.
Z3_string Z3_API Z3_model_to_string (__in Z3_context c, __in Z3_model m)
Convert the given model into a string.
Warning:
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_model_to_string.
Referenced by check(), eval_example1(), prove(), and tst_at_most_one().
Z3_probe Z3_API Z3_not_probe (__in Z3_context x, __in Z3_probe p)
Return a probe that evaluates to "true" when p does not evaluate to true.
Remarks:
For probes, "true" is any value different from 0.
Z3_bool Z3_API Z3_open_log (__in_z Z3_string filename)
Log interaction to a file.
Z3_bool Z3_API Z3_open_log (__in Z3_string filename)
Log interaction to a file.
Z3_tactic Z3_API Z3_or_else_tactic (__in Z3_context c, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that first applies t1 to a given goal, if it fails then returns the result of t2 applied to the given goal.
Z3_probe Z3_API Z3_or_probe (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when p1 or p2 evaluates to true.
Remarks:
For probes, "true" is any value different from 0.
void Z3_API Z3_params_dec_ref (__in Z3_context c, __in Z3_params p)
Decrement the reference counter of the given parameter set.
void Z3_API Z3_params_inc_ref (__in Z3_context c, __in Z3_params p)
Increment the reference counter of the given parameter set.
void Z3_API Z3_params_set_bool (__in Z3_context c, __in Z3_params p, __in Z3_symbol k, __in Z3_bool v)
Add a Boolean parameter k with value v to the parameter set p.
void Z3_API Z3_params_set_double (__in Z3_context c, __in Z3_params p, __in Z3_symbol k, __in double v)
Add a double parameter k with value v to the parameter set p.
void Z3_API Z3_params_set_symbol (__in Z3_context c, __in Z3_params p, __in Z3_symbol k, __in Z3_symbol v)
Add a symbol parameter k with value v to the parameter set p.
void Z3_API Z3_params_set_uint (__in Z3_context c, __in Z3_params p, __in Z3_symbol k, __in unsigned v)
Add a unsigned parameter k with value v to the parameter set p.
Z3_string Z3_API Z3_params_to_string (__in Z3_context c, __in Z3_params p)
Convert a parameter set into a string. This function is mainly used for printing the contents of a parameter set.
Z3_ast Z3_API Z3_parse_smtlib2_file (__in Z3_context c, __in_z Z3_string file_name, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Similar to Z3_parse_smtlib2_string, but reads the benchmark from a file.
Z3_ast Z3_API Z3_parse_smtlib2_file (__in Z3_context c, __in Z3_string file_name, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Similar to Z3_parse_smtlib2_string, but reads the benchmark from a file.
Z3_ast Z3_API Z3_parse_smtlib2_string (__in Z3_context c, __in_z Z3_string str, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Parse the given string using the SMT-LIB2 parser.
It returns a formula comprising of the conjunction of assertions in the scope (up to push/pop) at the end of the string.
Z3_ast Z3_API Z3_parse_smtlib2_string (__in Z3_context c, __in Z3_string str, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Parse the given string using the SMT-LIB2 parser.
It returns a formula comprising of the conjunction of assertions in the scope (up to push/pop) at the end of the string.
Referenced by smt2parser_example().
void Z3_API Z3_parse_smtlib_file (__in Z3_context c, __in_z Z3_string file_name, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Similar to Z3_parse_smtlib_string, but reads the benchmark from a file.
void Z3_API Z3_parse_smtlib_file (__in Z3_context c, __in Z3_string file_name, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Similar to Z3_parse_smtlib_string, but reads the benchmark from a file.
Referenced by smtlib_maxsat().
void Z3_API Z3_parse_smtlib_string (__in Z3_context c, __in_z Z3_string str, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Parse the given string using the SMT-LIB parser.
The symbol table of the parser can be initialized using the given sorts and declarations. The symbols in the arrays sort_names and decl_names don't need to match the names of the sorts and declarations in the arrays sorts and decls. This is an useful feature since we can use arbitrary names to reference sorts and declarations defined using the C API.
The formulas, assumptions and declarations defined in str can be extracted using the functions: Z3_get_smtlib_num_formulas, Z3_get_smtlib_formula, Z3_get_smtlib_num_assumptions, Z3_get_smtlib_assumption, Z3_get_smtlib_num_decls, and Z3_get_smtlib_decl.
void Z3_API Z3_parse_smtlib_string (__in Z3_context c, __in Z3_string str, __in unsigned num_sorts, __in_ecount(num_sorts) Z3_symbol const sort_names[], __in_ecount(num_sorts) Z3_sort const sorts[], __in unsigned num_decls, __in_ecount(num_decls) Z3_symbol const decl_names[], __in_ecount(num_decls) Z3_func_decl const decls[])
Parse the given string using the SMT-LIB parser.
The symbol table of the parser can be initialized using the given sorts and declarations. The symbols in the arrays sort_names and decl_names don't need to match the names of the sorts and declarations in the arrays sorts and decls. This is an useful feature since we can use arbitrary names to reference sorts and declarations defined using the C API.
The formulas, assumptions and declarations defined in str can be extracted using the functions: Z3_get_smtlib_num_formulas, Z3_get_smtlib_formula, Z3_get_smtlib_num_assumptions, Z3_get_smtlib_assumption, Z3_get_smtlib_num_decls, and Z3_get_smtlib_decl.
Referenced by assert_comm_axiom(), parser_example1(), parser_example2(), parser_example3(), parser_example4(), and parser_example5().
Z3_ast Z3_API Z3_parse_z3_file (__in Z3_context c, __in_z Z3_string file_name)
Similar to Z3_parse_z3_string, but reads the benchmark from a file.
Z3_ast Z3_API Z3_parse_z3_file (__in Z3_context c, __in Z3_string file_name)
Similar to Z3_parse_z3_string, but reads the benchmark from a file.
Z3_ast Z3_API Z3_parse_z3_string (__in Z3_context c, __in_z Z3_string str)
Parse the given string using the Z3 native parser.
Return the conjunction of asserts made in the input.
END_MLAPI_EXCLUDE Z3_ast Z3_API Z3_parse_z3_string (__in Z3_context c, __in Z3_string str)
Parse the given string using the Z3 native parser.
Return the conjunction of asserts made in the input.
Z3_ast Z3_API Z3_pattern_to_ast (__in Z3_context c, __in Z3_pattern p)
Convert a Z3_pattern into Z3_ast. This is just type casting.
void Z3_API Z3_persist_ast (__in Z3_context c, __in Z3_ast a, __in unsigned num_scopes)
Persist AST through num_scopes pops. This function is only relevant if c was created using Z3_mk_context. If c was created using Z3_mk_context_rc, this function is a NOOP.
Normally, for contexts created using Z3_mk_context, references to terms are no longer valid when popping scopes beyond the level where the terms are created. If you want to reference a term below the scope where it was created, use this method to specify how many pops the term should survive. The num_scopes should be at most equal to the number of calls to Z3_push subtracted with the calls to Z3_pop.
Deprecated:
Z3 users should move to Z3_mk_context_rc and use the reference counting APIs for managing AST nodes.
Normally, for contexts created using Z3_mk_context, references to terms are no longer valid when popping scopes beyond the level where the terms are created. If you want to reference a term below the scope where it was created, use this method to specify how many pops the term should survive. The num_scopes should be at most equal to the number of calls to Z3_push subtracted with the calls to Z3_pop.
void Z3_API Z3_pop (__in Z3_context c, __in unsigned num_scopes)
Backtrack.
Restores the context from the top of the stack, and pops it off the stack. Any changes to the logical context (by Z3_assert_cnstr or other functions) between the matching Z3_push and Z3_pop operators are flushed, and the context is completely restored to what it was right before the Z3_push.
See also:
Z3_push
Deprecated:
Subsumed by Z3_solver_pop
Restores the context from the top of the stack, and pops it off the stack. Any changes to the logical context (by Z3_assert_cnstr or other functions) between the matching Z3_push and Z3_pop operators are flushed, and the context is completely restored to what it was right before the Z3_push.
See also:
Z3_push
Referenced by prove(), push_pop_example1(), and reference_counter_example().
Z3_probe Z3_API Z3_probe_and (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when p1 and p2 evaluates to true.
Remarks:
For probes, "true" is any value different from 0.0.
double Z3_API Z3_probe_apply (__in Z3_context c, __in Z3_probe p, __in Z3_goal g)
Execute the probe over the goal. The probe always produce a double value. "Boolean" probes return 0.0 for false, and a value different from 0.0 for true.
Z3_probe Z3_API Z3_probe_const (__in Z3_context x, __in double val)
Return a probe that always evaluates to val.
void Z3_API Z3_probe_dec_ref (__in Z3_context c, __in Z3_probe p)
Decrement the reference counter of the given probe.
Z3_probe Z3_API Z3_probe_eq (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is equal to the value returned by p2.
Remarks:
For probes, "true" is any value different from 0.0.
Z3_probe Z3_API Z3_probe_ge (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than or equal to the value returned by p2.
Remarks:
For probes, "true" is any value different from 0.0.
Z3_string Z3_API Z3_probe_get_descr (__in Z3_context c, __in Z3_string name)
Return a string containing a description of the probe with the given name.
Z3_probe Z3_API Z3_probe_gt (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is greater than the value returned by p2.
Remarks:
For probes, "true" is any value different from 0.0.
void Z3_API Z3_probe_inc_ref (__in Z3_context c, __in Z3_probe p)
Increment the reference counter of the given probe.
Z3_probe Z3_API Z3_probe_le (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than or equal to the value returned by p2.
Remarks:
For probes, "true" is any value different from 0.0.
Z3_probe Z3_API Z3_probe_lt (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when the value returned by p1 is less than the value returned by p2.
Remarks:
For probes, "true" is any value different from 0.0.
Z3_probe Z3_API Z3_probe_not (__in Z3_context x, __in Z3_probe p)
Return a probe that evaluates to "true" when p does not evaluate to true.
Remarks:
For probes, "true" is any value different from 0.0.
Z3_probe Z3_API Z3_probe_or (__in Z3_context x, __in Z3_probe p1, __in Z3_probe p2)
Return a probe that evaluates to "true" when p1 or p2 evaluates to true.
Remarks:
For probes, "true" is any value different from 0.0.
void Z3_API Z3_push (__in Z3_context c)
Create a backtracking point.
The logical context can be viewed as a stack of contexts. The scope level is the number of elements on this stack. The stack of contexts is simulated using trail (undo) stacks.
See also:
Z3_pop
Deprecated:
Subsumed by Z3_solver_push
The logical context can be viewed as a stack of contexts. The scope level is the number of elements on this stack. The stack of contexts is simulated using trail (undo) stacks.
See also:
Z3_pop
Referenced by prove(), push_pop_example1(), and reference_counter_example().
void Z3_API Z3_query_constructor (__in Z3_context c, __in Z3_constructor constr, __in unsigned num_fields, __out Z3_func_decl * constructor, __out Z3_func_decl * tester, __out_ecount(num_fields) Z3_func_decl accessors[])
Query constructor for declared functions.
Query constructor for declared funcions.
Parameters:
c logical context.
constr constructor container. The container must have been passed in to a Z3_mk_datatype call.
num_fields number of accessor fields in the constructor.
constructor constructor function declaration.
tester constructor test function declaration.
accessors array of accessor function declarations.
Referenced by binary_tree_example(), forest_example(), and tree_example().
Z3_tactic Z3_API Z3_repeat_tactic (__in Z3_context c, __in Z3_tactic t, unsigned max)
Return a tactic that keeps applying t until the goal is not modified anymore or the maximum number of iterations max is reached.
void Z3_API Z3_reset_memory (void)
Reset all allocated resources.
Use this facility on out-of memory errors. It allows discharging the previous state and resuming afresh. Any pointers previously returned by the API become invalid.
void Z3_API Z3_set_ast_print_mode (__in Z3_context c, __in Z3_ast_print_mode mode)
Select mode for the format used for pretty-printing AST nodes.
The default mode for pretty printing AST nodes is to produce SMT-LIB style output where common subexpressions are printed at each occurrence. The mode is called Z3_PRINT_SMTLIB_FULL. To print shared common subexpressions only once, use the Z3_PRINT_LOW_LEVEL mode. To print in way that conforms to SMT-LIB standards and uses let expressions to share common sub-expressions use Z3_PRINT_SMTLIB_COMPLIANT.
See also:
Z3_ast_to_string
Z3_pattern_to_string
Z3_func_decl_to_string
void Z3_API Z3_set_delete_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when theory t is deleted. This callback should be used to delete external data-structures associated with the given theory.
The callback has the form f(t), where
t is the given theory
See also:
Z3_mk_theory
Z3_theory_get_ext_data
Referenced by mk_pa_theory(), and mk_simple_theory().
void Z3_API Z3_set_error (__in Z3_context c, __in Z3_error_code e)
Set an error.
void Z3_API Z3_set_error_handler (__in Z3_context c, __in Z3_error_handler h)
Register a Z3 error handler.
A call to a Z3 function may return a non Z3_OK error code, when it is not used correctly. An error handler can be registered and will be called in this case. To disable the use of the error handler, simply register with h=NULL.
Warning:
Log files, created using Z3_open_log, may be potentially incomplete/incorrect if error handlers are used.
See also:
Z3_get_error_code
A call to a Z3 function may return a non Z3_OK error code, when it is not used correctly. An error handler can be registered and will be called in this case. To disable the use of the error handler, simply register with h=NULL.
When logging is enabled, this function can only be used with h=NULL.
See also:
Z3_get_error_code
Referenced by mk_context_custom().
void Z3_API Z3_set_final_check_callback (__in Z3_theory t, __in Z3_theory_final_check_callback_fptr f)
Set a callback that is invoked before Z3 starts building a model. A theory may use this callback to perform expensive operations.
The callback has the form f(t), where
t is the given theory
If the theory returns Z3_false, Z3 will assume that theory is giving up, and it will assume that it was not possible to decide if the asserted constraints are satisfiable or not.
The callback has the form f(t), where
t is the given theory
If the theory return Z3_false, Z3 will assume that theory is giving up, and it will assume that it was not possible to decide if the asserted constraints are satisfiable or not.
Referenced by mk_pa_theory(), and mk_simple_theory().
void Z3_API Z3_set_init_search_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when Z3 starts searching for a satisfying assignment.
The callback has the form f(t), where
t is the given theory
Referenced by mk_simple_theory().
Z3_bool Z3_API Z3_set_logic (__in Z3_context c, __in_z Z3_string logic)
Set the SMTLIB logic to be used in the given logical context. It is incorrect to invoke this function after invoking Z3_check, Z3_check_and_get_model, Z3_check_assumptions and Z3_push. Return Z3_TRUE if the logic was changed successfully, and Z3_FALSE otherwise.
Z3_bool Z3_API Z3_set_logic (__in Z3_context c, __in Z3_string logic)
Set the SMTLIB logic to be used in the given logical context. It is incorrect to invoke this function after invoking Z3_check, Z3_check_and_get_model, Z3_check_assumptions and Z3_push. Return Z3_TRUE if the logic was changed successfully, and Z3_FALSE otherwise.
Deprecated:
Subsumed by Z3_mk_solver_for_logic
void Z3_API Z3_set_new_app_callback (__in Z3_theory t, __in Z3_theory_ast_callback_fptr f)
Set a callback that is invoked when a theory application is finally added into the logical context. Note that, not every application contained in an asserted expression is actually added into the logical context because it may be simplified during a preprocessing step.
The callback has the form f(t, n), where
t is the given theory
n is a theory application, that is, an expression of the form g(...) where g is a theory operator.
Remarks:
An expression n added to the logical context at search level n, will remain in the logical context until this level is backtracked.
Referenced by mk_simple_theory().
void Z3_API Z3_set_new_assignment_callback (__in Z3_theory t, __in Z3_theory_ast_bool_callback_fptr f)
Set a callback that is invoked when a theory predicate is assigned to true/false by Z3.
The callback has the form f(t, p, v), where:
t is the given theory
p is the assigned predicate.
v is the value (true/false) assigned to p.
Referenced by mk_simple_theory().
void Z3_API Z3_set_new_diseq_callback (__in Z3_theory t, __in Z3_theory_ast_ast_callback_fptr f)
Set a callback that is invoked when a disequality s_1 != s_2 is found by the logical context.
The callback has the form f(t, s_1, s_2), where:
t is the given theory
s_1 is the left-hand-side
s_2 is the right-hand-side
Referenced by mk_simple_theory().
void Z3_API Z3_set_new_elem_callback (__in Z3_theory t, __in Z3_theory_ast_callback_fptr f)
Set a callback that is invoked when an expression of sort s, where s is an interpreted sort of the theory t, is finally added into the logical context. Note that, not every expression contained in an asserted expression is actually added into the logical context because it may be simplified during a preprocessing step.
The callback has the form f(t, n), where
t is the given theory
n is an expression of sort s, where s is an interpreted sort of t.
Remarks:
An expression n added to the logical context at search level n, will remain in the logical context until this level is backtracked.
Referenced by mk_simple_theory().
void Z3_API Z3_set_new_eq_callback (__in Z3_theory t, __in Z3_theory_ast_ast_callback_fptr f)
Set a callback that is invoked when an equality s_1 = s_2 is found by the logical context.
The callback has the form f(t, s_1, s_2), where:
t is the given theory
s_1 is the left-hand-side
s_2 is the right-hand-side
Referenced by mk_pa_theory(), and mk_simple_theory().
void Z3_API Z3_set_new_relevant_callback (__in Z3_theory t, __in Z3_theory_ast_callback_fptr f)
Set a callback that is invoked when an expression is marked as relevant during the search. This callback is only invoked when relevancy propagation is enabled.
The callback has the form f(t, n), where:
t is the given theory
n is the relevant expression
Referenced by mk_simple_theory().
void Z3_API Z3_set_param_value (__in Z3_config c, __in_z Z3_string param_id, __in_z Z3_string param_value)
Set a configuration parameter.
The list of all configuration parameters can be obtained using the Z3 executable:
       z3.exe -ini?
See also:
Z3_mk_config
void Z3_API Z3_set_param_value (__in Z3_config c, __in Z3_string param_id, __in Z3_string param_value)
Set a configuration parameter.
The list of all configuration parameters can be obtained using the Z3 executable:
       z3.exe -ini?
See also:
Z3_mk_config
Referenced by get_implied_equalities_example(), mk_context(), mk_context_custom(), mk_proof_context(), parser_example3(), quantifier_example1(), and reference_counter_example().
void Z3_API Z3_set_pop_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when Z3 backtracks a case-split.
When a case-split is backtracked we say the search level is decreased.
The callback has the form f(t), where
t is the given theory
Referenced by mk_simple_theory().
void Z3_API Z3_set_push_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when Z3 creates a case-split (aka backtracking point).
When a case-split is created we say the search level is increased.
The callback has the form f(t), where
t is the given theory
Referenced by mk_simple_theory().
void Z3_API Z3_set_reduce_app_callback (__in Z3_theory t, __in Z3_reduce_app_callback_fptr f)
Set a callback for simplifying operators of the given theory. The callback f is invoked by Z3's simplifier.
It is of the form f(t, d, n, args, r), where:
t is the given theory
d is the declaration of the theory operator
n is the number of arguments in the array args
args are arguments for the theory operator
r should contain the result: an expression equivalent to d(args[0], ..., args[n-1]).
If f(t, d, n, args, r) returns false, then r is ignored, and Z3 assumes that no simplification was performed.
Referenced by mk_pa_theory(), and mk_simple_theory().
void Z3_API Z3_set_reduce_distinct_callback (__in Z3_theory t, __in Z3_reduce_distinct_callback_fptr f)
Set a callback for simplifying the atom distinct(s_1, ..., s_n), when the sort of s_1, ..., s_n is an interpreted sort of the given theory. The callback f is invoked by Z3's simplifier.
It has the form f(t, n, args, r), where:
t is the given theory
n is the number of arguments in the array args
args are arguments for distinct.
r should contain the result: an expression equivalent to distinct(s_1, ..., s_n).
If f(t, n, args, r) returns false, then r is ignored, and Z3 assumes that no simplification was performed.
void Z3_API Z3_set_reduce_eq_callback (__in Z3_theory t, __in Z3_reduce_eq_callback_fptr f)
Set a callback for simplifying the atom s_1 = s_2, when the sort of s_1 and s_2 is an interpreted sort of the given theory. The callback f is invoked by Z3's simplifier.
It has the form f(t, s_1, s_2, r), where:
t is the given theory
s_1 is the left-hand-side
s_2 is the right-hand-side
r should contain the result: an expression equivalent to s_1 = s_2.
If f(t, s_1, s_2, r) returns false, then r is ignored, and Z3 assumes that no simplification was performed.
void Z3_API Z3_set_reset_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when the logical context is reset by the user. This callback is useful for reseting any data-structure maintained by the user theory solver.
The callback has the form f(t), where
t is the given theory
Referenced by mk_simple_theory().
void Z3_API Z3_set_restart_callback (__in Z3_theory t, __in Z3_theory_callback_fptr f)
Set a callback that is invoked when Z3 restarts the search for a satisfying assignment.
The callback has the form f(t), where
t is the given theory
Referenced by mk_simple_theory().
void Z3_API Z3_set_simplifier_callback (__in Z3_context c, __in void * user_context, __in Z3_simplify_ast_fn * simplifier)
Register a user-supplied simplification function. The simplifier gets invoked during pre-processing.
The arguments to the Z3_simplify_ast_fptr callback are:
Parameters:
user-context - user supplied context.
ast_in - expression to be simplified
ast_out - simplified expression
proof_out - optional proof object for simplification. The callback returns a Boolean. Output values are ignored if the return value is Z3_FALSE, If the return value is Z3_TRUE and the ast_out output parameter contains an expression, then Z3 performs a rewrite of ast_in to ast_out. If the proof object is valid, then Z3 tracks the rewrite using the associated proof step. The leaf of the returned proof object must be an equality between ast_in and ast_out. The proof object is ignored if proof generation is not turned on.
At most one simplification routine is used. If a user calls the API twice with two different simplification routines, then only the last routine is used. Z3 applies simplification on subterms; the user simplificaiton routine does not need to apply simplification recursively.
Z3_ast Z3_API Z3_simplify (__in Z3_context c, __in Z3_ast a)
Interface to simplifier.
Provides an interface to the AST simplifier used by Z3.
Referenced by pa_theory_example1(), and simple_example1().
Z3_ast Z3_API Z3_simplify_ex (__in Z3_context c, __in Z3_ast a, __in Z3_params p)
Interface to simplifier.
Provides an interface to the AST simplifier used by Z3. This procedure is similar to Z3_simplify, but the behavior of the simplifier can be configured using the given parameter set.
Provides an interface to the AST simplifier used by Z3. This procedure is similar to Z3_simplify_ex, but the behavior of the simplifier can be configured using the given parameter set.
Z3_string Z3_API Z3_simplify_get_help (__in Z3_context c)
Return a string describing all available parameters.
Z3_tactic Z3_API Z3_skip_tactic (__in Z3_context c)
Return a tactic that just return the given goal.
void Z3_API Z3_soft_check_cancel (__in Z3_context c)
Cancel an ongoing check.
Notifies the current check to abort and return. This method should be called from a different thread than the one performing the check.
Deprecated:
Use Z3_interrupt instead.
Notifies the current check to abort and return. This method should be called from a different thread than the one performing the check.
Remarks:
Deprecated, use Z3_interrupt instead.
void Z3_API Z3_solver_assert (__in Z3_context c, __in Z3_solver s, __in Z3_ast a)
Assert a constraint into the solver.
The functions Z3_solver_check and Z3_solver_check_assumptions should be used to check whether the logical context is consistent or not.
Z3_lbool Z3_API Z3_solver_check (__in Z3_context c, __in Z3_solver s)
Check whether the assertions in a given solver are consistent or not.
The function Z3_solver_get_model retrieves a model if the assertions are not unsatisfiable (i.e., the result is not Z3_L_FALSE) and model construction is enabled.
The function Z3_solver_get_proof retrieves a proof if proof generation was enabled when the context was created, and the assertions are unsatisfiable (i.e., the result is Z3_L_FALSE).
Z3_lbool Z3_API Z3_solver_check_assumptions (__in Z3_context c, __in Z3_solver s, __in unsigned num_assumptions, __in_ecount(num_assumptions) Z3_ast const assumptions[])
Check whether the assertions in the given solver and optional assumptions are consistent or not.
The function Z3_solver_get_unsat_core retrieves the subset of the assumptions used in the unsatisfiability proof produced by Z3.
See also:
Z3_solver_check
void Z3_API Z3_solver_dec_ref (__in Z3_context c, __in Z3_solver s)
Decrement the reference counter of the given solver.
Z3_ast_vector Z3_API Z3_solver_get_assertions (__in Z3_context c, __in Z3_solver s)
Return the set of asserted formulas as a goal object.
Z3_string Z3_API Z3_solver_get_help (__in Z3_context c, __in Z3_solver s)
Return a string describing all solver available parameters.
Z3_model Z3_API Z3_solver_get_model (__in Z3_context c, __in Z3_solver s)
Retrieve the model for the last Z3_solver_check or Z3_solver_check_assumptions.
The error handler is invoked if a model is not available because the commands above were not invoked for the given solver, or if the result was Z3_L_FALSE.
unsigned Z3_API Z3_solver_get_num_scopes (__in Z3_context c, __in Z3_solver s)
Return the number of backtracking points.
See also:
Z3_solver_push
Z3_solver_pop
Z3_ast Z3_API Z3_solver_get_proof (__in Z3_context c, __in Z3_solver s)
Retrieve the proof for the last Z3_solver_check or Z3_solver_check_assumptions.
The error handler is invoked if proof generation is not enabled, or if the commands above were not invoked for the given solver, or if the result was different from Z3_L_FALSE.
Z3_string Z3_API Z3_solver_get_reason_unknown (__in Z3_context c, __in Z3_solver s)
Return a brief justification for an "unknown" result (i.e., Z3_L_UNDEF) for the commands Z3_solver_check and Z3_solver_check_assumptions.
Z3_stats Z3_API Z3_solver_get_statistics (__in Z3_context c, __in Z3_solver s)
Return statistics for the given solver.
Remarks:
User must use Z3_stats_inc_ref and Z3_stats_dec_ref to manage Z3_stats objects.
Z3_ast_vector Z3_API Z3_solver_get_unsat_core (__in Z3_context c, __in Z3_solver s)
Retrieve the unsat core for the last Z3_solver_check_assumptions The unsat core is a subset of the assumptions a.
void Z3_API Z3_solver_inc_ref (__in Z3_context c, __in Z3_solver s)
Increment the reference counter of the given solver.
void Z3_API Z3_solver_pop (__in Z3_context c, __in Z3_solver s, unsigned n)
Backtrack n backtracking points.
See also:
Z3_solver_push
Precondition:
n <= Z3_solver_get_num_scopes(c, s)
void Z3_API Z3_solver_push (__in Z3_context c, __in Z3_solver s)
Create a backtracking point.
The solver contains a stack of assertions.
See also:
Z3_solver_pop
void Z3_API Z3_solver_reset (__in Z3_context c, __in Z3_solver s)
Remove all assertions from the solver.
void Z3_API Z3_solver_set_params (__in Z3_context c, __in Z3_solver s, __in Z3_params p)
Set the given solver using the given parameters.
Z3_string Z3_API Z3_solver_to_string (__in Z3_context c, __in Z3_solver s)
Convert a solver into a string.
Z3_ast Z3_API Z3_sort_to_ast (__in Z3_context c, __in Z3_sort s)
Convert a Z3_sort into Z3_ast. This is just type casting.
Convert a Z3_sort into Z3_ast. This is just type casting.
Referenced by reference_counter_example().
Z3_string Z3_API Z3_statistics_to_string (__in Z3_context c)
Return runtime statistics as a string.
This function is mainly used for debugging purposes. It displays statistics of the search activity.
Warning:
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_context_to_string.
Deprecated:
This method is based on the old solver API. Use Z3_stats_to_string when using the new solver API.
This function is mainly used for debugging purposes. It displays statistics of the search activity.
Warning:
The result buffer is statically allocated by Z3. It will be automatically deallocated when Z3_del_context is invoked. So, the buffer is invalidated in the next call to Z3_context_to_string.
Referenced by RawContext::StatisticsToString().
void Z3_API Z3_stats_dec_ref (__in Z3_context c, __in Z3_stats s)
Decrement the reference counter of the given statistics object.
double Z3_API Z3_stats_get_double_value (__in Z3_context c, __in Z3_stats s, __in unsigned idx)
Return the double value of the given statistical data.
Precondition:
idx < Z3_stats_size(c, s) && Z3_stats_is_double(c, s)
Z3_string Z3_API Z3_stats_get_key (__in Z3_context c, __in Z3_stats s, __in unsigned idx)
Return the key (a string) for a particular statistical data.
Precondition:
idx < Z3_stats_size(c, s)
unsigned Z3_API Z3_stats_get_uint_value (__in Z3_context c, __in Z3_stats s, __in unsigned idx)
Return the unsigned value of the given statistical data.
Precondition:
idx < Z3_stats_size(c, s) && Z3_stats_is_uint(c, s)
void Z3_API Z3_stats_inc_ref (__in Z3_context c, __in Z3_stats s)
Increment the reference counter of the given statistics object.
Z3_bool Z3_API Z3_stats_is_double (__in Z3_context c, __in Z3_stats s, __in unsigned idx)
Return Z3_TRUE if the given statistical data is a double.
Precondition:
idx < Z3_stats_size(c, s)
Z3_bool Z3_API Z3_stats_is_uint (__in Z3_context c, __in Z3_stats s, __in unsigned idx)
Return Z3_TRUE if the given statistical data is a unsigned integer.
Precondition:
idx < Z3_stats_size(c, s)
unsigned Z3_API Z3_stats_size (__in Z3_context c, __in Z3_stats s)
Return the number of statistical data in s.
Z3_string Z3_API Z3_stats_to_string (__in Z3_context c, __in Z3_stats s)
Convert a statistics into a string.
Z3_ast Z3_API Z3_substitute (__in Z3_context c, __in Z3_ast a, __in unsigned num_exprs, __in_ecount(num_exprs) Z3_ast const from[], __in_ecount(num_exprs) Z3_ast const to[])
Substitute every occurrence of from[i] in a with to[i], for i smaller than num_exprs. The result is the new AST. The arrays from and to must have size num_exprs. For every i smaller than num_exprs, we must have that sort of from[i] must be equal to sort of to[i].
Referenced by substitute_example().
Z3_ast Z3_API Z3_substitute_vars (__in Z3_context c, __in Z3_ast a, __in unsigned num_exprs, __in_ecount(num_exprs) Z3_ast const to[])
Substitute the free variables in a with the expressions in to. For every i smaller than num_exprs, the variable with de-Bruijn index i is replaced with term to[i].
Referenced by substitute_vars_example().
Z3_tactic Z3_API Z3_tactic_and_then (__in Z3_context c, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that applies t1 to a given goal and t2 to every subgoal produced by t1.
Z3_apply_result Z3_API Z3_tactic_apply (__in Z3_context c, __in Z3_tactic t, __in Z3_goal g)
Apply tactic t to the goal g.
Z3_apply_result Z3_API Z3_tactic_apply_ex (Z3_context c, Z3_tactic t, Z3_goal g, Z3_params p)
Apply tactic t to the goal g using the parameter set p.
Z3_tactic Z3_API Z3_tactic_cond (__in Z3_context c, __in Z3_probe p, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that applies t1 to a given goal if the probe p evaluates to true, and t2 if p evaluates to false.
void Z3_API Z3_tactic_dec_ref (__in Z3_context c, __in Z3_tactic g)
Decrement the reference counter of the given tactic.
Z3_tactic Z3_API Z3_tactic_fail (__in Z3_context c)
Return a tactic that always fails.
Z3_tactic Z3_API Z3_tactic_fail_if (__in Z3_context c, __in Z3_probe p)
Return a tactic that fails if the probe p evaluates to false.
Z3_tactic Z3_API Z3_tactic_fail_if_not_decided (__in Z3_context c)
Return a tactic that fails if the goal is not trivially satisfiable (i.e., empty) or trivially unsatisfiable (i.e., contains false).
Z3_string Z3_API Z3_tactic_get_descr (__in Z3_context c, __in Z3_string name)
Return a string containing a description of the tactic with the given name.
Z3_string Z3_API Z3_tactic_get_help (__in Z3_context c, __in Z3_tactic t)
Return a string containing a description of parameters accepted by the given tactic.
void Z3_API Z3_tactic_inc_ref (__in Z3_context c, __in Z3_tactic t)
Increment the reference counter of the given tactic.
Z3_tactic Z3_API Z3_tactic_or_else (__in Z3_context c, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that first applies t1 to a given goal, if it fails then returns the result of t2 applied to the given goal.
Z3_tactic Z3_API Z3_tactic_par_and_then (__in Z3_context c, __in Z3_tactic t1, __in Z3_tactic t2)
Return a tactic that applies t1 to a given goal and then t2 to every subgoal produced by t1. The subgoals are processed in parallel.
Z3_tactic Z3_API Z3_tactic_par_or (__in Z3_context c, __in unsigned num, __in_ecount(num) Z3_tactic const ts[])
Return a tactic that applies the given tactics in parallel.
Z3_tactic Z3_API Z3_tactic_repeat (__in Z3_context c, __in Z3_tactic t, unsigned max)
Return a tactic that keeps applying t until the goal is not modified anymore or the maximum number of iterations max is reached.
Z3_tactic Z3_API Z3_tactic_skip (__in Z3_context c)
Return a tactic that just return the given goal.
Z3_tactic Z3_API Z3_tactic_try_for (__in Z3_context c, __in Z3_tactic t, __in unsigned ms)
Return a tactic that applies t to a given goal for ms milliseconds. If t does not terminate in ms milliseconds, then it fails.
Z3_tactic Z3_API Z3_tactic_using_params (__in Z3_context c, __in Z3_tactic t, __in Z3_params p)
Return a tactic that applies t using the given set of parameters.
Z3_tactic Z3_API Z3_tactic_when (__in Z3_context c, __in Z3_probe p, __in Z3_tactic t)
Return a tactic that applies t to a given goal is the probe p evaluates to true. If p evaluates to false, then the new tactic behaves like the skip tactic.
void Z3_API Z3_theory_assert_axiom (__in Z3_theory t, __in Z3_ast ax)
Assert a theory axiom/lemmas during the search.
An axiom added at search level n will remain in the logical context until level n is backtracked.
The callbacks for push (Z3_set_push_callback) and pop (Z3_set_pop_callback) can be used to track when the search level is increased (i.e., new case-split) and decreased (i.e., case-split is backtracked).
Z3 tracks the theory axioms asserted. So, multiple assertions of the same axiom are ignored.
Referenced by apply_compare_axiom_for_parents_of(), and apply_unit_axiom_for_parents_of().
void Z3_API Z3_theory_assume_eq (__in Z3_theory t, __in Z3_ast lhs, __in Z3_ast rhs)
Inform to the logical context that lhs and rhs have the same interpretation in the model being built by theory t. If lhs = rhs is inconsistent with other theories, then the logical context will backtrack.
For more information, see the paper "Model-Based Theory Combination" in the Z3 website.
void Z3_API Z3_theory_enable_axiom_simplification (__in Z3_theory t, __in Z3_bool flag)
Enable/disable the simplification of theory axioms asserted using Z3_theory_assert_axiom. By default, the simplification of theory specific operators is disabled. That is, the reduce theory callbacks are not invoked for theory axioms. The default behavior is useful when asserting axioms stating properties of theory operators.
Z3_ast Z3_API Z3_theory_get_app (__in Z3_theory t, __in unsigned i)
Return the i-th application of the given theory in the logical context.
See also:
Z3_theory_get_num_apps
Referenced by PATh_final_check().
Z3_context Z3_API Z3_theory_get_context (__in Z3_theory t)
Return the context where the given theory is installed.
Referenced by apply_compare_axiom_for_parents_of(), apply_unit_axiom_for_parents_of(), Compare(), display_eqc(), display_eqc_parents(), PATh_final_check(), PATh_mk_string_value(), PATh_new_eq(), PATh_reduce_app(), Th_new_app(), Th_new_assignment(), Th_new_diseq(), Th_new_elem(), Th_new_eq(), Th_new_relevant(), and Th_reduce_app().
Z3_ast Z3_API Z3_theory_get_elem (__in Z3_theory t, __in unsigned i)
Return the i-th elem of the given theory in the logical context.
See also:
Z3_theory_get_num_elems
Z3_ast Z3_API Z3_theory_get_eqc_next (__in Z3_theory t, __in Z3_ast n)
Return the next element in the equivalence class containing n.
The elements in an equivalence class are organized in a circular list. You can traverse the list by calling this function multiple times using the result from the previous call. This is illustrated in the code snippet below.
           Z3_ast curr = n;
           do
             curr = Z3_theory_get_eqc_next(theory, curr);
           while (curr != n);
Referenced by apply_compare_axiom_for_parents_of(), apply_unit_axiom_for_parents_of(), display_eqc(), display_eqc_parents(), and get_eqc_value().
Z3_ast Z3_API Z3_theory_get_eqc_root (__in Z3_theory t, __in Z3_ast n)
Return the root of the equivalence class containing n.
Referenced by apply_compare_axiom_for_parents_of(), display_eqc(), and Th_new_eq().
Z3_theory_data Z3_API Z3_theory_get_ext_data (__in Z3_theory t)
Return a pointer to the external data-structure supplied to the function Z3_mk_theory.
See also:
Z3_mk_theory
Referenced by apply_compare_axiom_for_parents_of(), apply_unit_axiom_for_parents_of(), pa_theory_example1(), pa_theory_example2(), PATh_delete(), PATh_final_check(), PATh_mk_string_value(), PATh_new_eq(), PATh_reduce_app(), simple_example1(), simple_example2(), Th_delete(), Th_new_eq(), and Th_reduce_app().
unsigned Z3_API Z3_theory_get_num_apps (__in Z3_theory t)
Return the number of theory applications in the logical context. These are the expressions notified using the callback Z3_set_new_app_callback.
Referenced by PATh_final_check().
unsigned Z3_API Z3_theory_get_num_elems (__in Z3_theory t)
Return the number of expressions of the given theory in the logical context. These are the expressions notified using the callback Z3_set_new_elem_callback.
unsigned Z3_API Z3_theory_get_num_parents (__in Z3_theory t, __in Z3_ast n)
Return the number of parents of n that are operators of the given theory.
Referenced by apply_compare_axiom_for_parents_of(), apply_unit_axiom_for_parents_of(), and display_eqc_parents().
Z3_ast Z3_API Z3_theory_get_parent (__in Z3_theory t, __in Z3_ast n, __in unsigned i)
Return the i-th parent of n. See Z3_theory_get_num_parents.
Referenced by apply_compare_axiom_for_parents_of(), apply_unit_axiom_for_parents_of(), and display_eqc_parents().
Z3_bool Z3_API Z3_theory_is_decl (__in Z3_theory t, __in Z3_func_decl d)
Return Z3_TRUE if d is an interpreted theory declaration.
Z3_bool Z3_API Z3_theory_is_value (__in Z3_theory t, __in Z3_ast n)
Return Z3_TRUE if n is an interpreted theory value.
Referenced by Compare(), and get_eqc_value().
Z3_ast Z3_API Z3_theory_mk_constant (__in Z3_context c, __in Z3_theory t, __in Z3_symbol n, __in Z3_sort s)
Create an interpreted constant for the given theory.
Referenced by mk_simple_theory().
Z3_func_decl Z3_API Z3_theory_mk_func_decl (__in Z3_context c, __in Z3_theory t, __in Z3_symbol n, __in unsigned domain_size, __in_ecount(domain_size) Z3_sort const domain[], __in Z3_sort range)
Create an interpreted function declaration for the given theory.
Referenced by mk_pa_theory(), and mk_simple_theory().
Z3_sort Z3_API Z3_theory_mk_sort (__in Z3_context c, __in Z3_theory t, __in Z3_symbol s)
Create an interpreted theory sort.
Referenced by mk_pa_theory(), mk_simple_theory(), and model_display_example().
Z3_ast Z3_API Z3_theory_mk_value (__in Z3_context c, __in Z3_theory t, __in Z3_symbol n, __in Z3_sort s)
Create an interpreted theory constant value. Values are assumed to be different from each other.
Referenced by model_display_example(), and PATh_mk_string_value().
Z3_app Z3_API Z3_to_app (__in Z3_context c, __in Z3_ast a)
Convert an ast into an APP_AST. This is just type casting.
Convert an AST into a APP_AST. This is just type casting.
Precondition:
 Z3_get_ast_kind(c, a) == \c Z3_APP_AST
Warning:
This conversion is only safe if Z3_get_ast_kind returns Z3_app.
Referenced by apply_compare_axiom_for_parents_of(), apply_unit_axiom_for_parents_of(), Compare(), display_ast(), error_code_example1(), parser_example2(), and PATh_final_check().
Z3_func_decl Z3_API Z3_to_func_decl (__in Z3_context c, __in Z3_ast a)
Convert an AST into a FUNC_DECL_AST. This is just type casting.
Precondition:
 Z3_get_ast_kind(c, a) == Z3_FUNC_DECL_AST
void Z3_API Z3_toggle_warning_messages (__in Z3_bool enabled)
Enable/disable printing warning messages to the console.
Warnings are printed after passing true, warning messages are suppressed after calling this method with false.
Z3_ast Z3_API Z3_translate (__in Z3_context source, __in Z3_ast a, __in Z3_context target)
Translate/Copy the AST a from context source to context target. AST a must have been created using context source.
Precondition:
source != target
Z3_tactic Z3_API Z3_try_for_tactic (__in Z3_context c, __in Z3_tactic t, __in unsigned ms)
Return a tactic that applies t to a given goal for ms milliseconds. If t does not terminate in ms milliseconds, then it fails.
void Z3_API Z3_update_param_value (__in Z3_context c, __in_z Z3_string param_id, __in_z Z3_string param_value)
Update a mutable configuration parameter.
The list of all configuration parameters can be obtained using the Z3 executable:
       z3.exe -ini?
Only a few configuration parameters are mutable once the context is created. The error handler is invoked when trying to modify an immutable parameter.
See also:
Z3_set_param_value
void Z3_API Z3_update_param_value (__in Z3_context c, __in Z3_string param_id, __in Z3_string param_value)
Update a mutable configuration parameter.
The list of all configuration parameters can be obtained using the Z3 executable:
       z3.exe -ini?
Only a few configuration parameters are mutable once the context is created. The error handler is invoked when trying to modify an immutable parameter.
See also:
Z3_set_param_value
Z3_ast Z3_API Z3_update_term (__in Z3_context c, __in Z3_ast a, __in unsigned num_args, __in_ecount(num_args) Z3_ast const args[])
Update the arguments of term a using the arguments args. The number of arguments num_args should coincide with the number of arguments to a. If a is a quantifier, then num_args has to be 1.
Z3_tactic Z3_API Z3_using_params_tactic (__in Z3_context c, __in Z3_tactic t, __in Z3_params p)
Return a tactic that applies t using the given set of parameters.
Z3_tactic Z3_API Z3_when_tactic (__in Z3_context c, __in Z3_probe p, __in Z3_tactic t)
Return a tactic that applies t to a given goal is the probe p evaluates to true. If p evaluates to false, then the new tactic behaves like the skip tactic.
Last modified Thu Aug 9 16:34:44 2012